// Chromium family, second pass: what a page may reach, and what the browser
// reports on its own account.
import type { ChromiumPolicy } from "../../type/policy.ts";

type Row = [
  string,
  string,
  string,
  ChromiumPolicy["bad"],
  string,
  ChromiumPolicy["category"],
  number,
  string,
  string,
  string,
];

const C = "profile.default_content_setting_values";

const ROWS: Row[] = [
  [
    "nfc",
    `${C}.nfc`,
    "3",
    "<2",
    "2",
    "security",
    62,
    "Sites may ask for NFC access",
    "a page talking to contactless hardware",
    "Requests are refused.",
  ],
  [
    "vr",
    `${C}.vr`,
    "3",
    "<2",
    "2",
    "privacy",
    33,
    "Sites may query VR hardware",
    "another hardware signal exposed on request",
    "Requests are refused.",
  ],
  [
    "ar",
    `${C}.ar`,
    "3",
    "<2",
    "2",
    "privacy",
    32,
    "Sites may query AR hardware",
    "camera-adjacent capability exposed on request",
    "Requests are refused.",
  ],
  [
    "camera-pan",
    `${C}.camera_pan_tilt_zoom`,
    "3",
    "<2",
    "2",
    "privacy",
    48,
    "Sites may control camera movement",
    "a page that has your camera can also aim it",
    "Requests are refused; ordinary camera use is unaffected.",
  ],
  [
    "font-access",
    `${C}.local_fonts`,
    "3",
    "<2",
    "2",
    "privacy",
    47,
    "Sites may enumerate your installed fonts",
    "the font list is one of the strongest fingerprints a browser can hand over",
    "Requests are refused; pages still render with the fonts they ask for.",
  ],
  [
    "auto-picture",
    `${C}.auto_picture_in_picture`,
    "3",
    "<2",
    "2",
    "settings",
    18,
    "Sites may start picture-in-picture on their own",
    "a video pops out over your work without a click",
    "Requests are refused.",
  ],
  [
    "captured-surface",
    `${C}.captured_surface_control`,
    "3",
    "<2",
    "2",
    "security",
    61,
    "Sites sharing your screen may also scroll and zoom it",
    "a screen-share becomes partial remote control",
    "Requests are refused; sharing still works.",
  ],
  [
    "smart-card",
    `${C}.smart_card_guard`,
    "3",
    "<2",
    "2",
    "security",
    63,
    "Sites may ask for smart card access",
    "a page talking directly to an authentication token",
    "Requests are refused.",
  ],
  [
    "web-printing",
    `${C}.web_printing`,
    "3",
    "<2",
    "2",
    "privacy",
    20,
    "Sites may print without a dialog",
    "a page can send documents to your printer unprompted",
    "Requests are refused.",
  ],
  [
    "keyboard-lock",
    `${C}.keyboard_lock`,
    "3",
    "<2",
    "2",
    "security",
    60,
    "Sites may capture system keyboard shortcuts",
    "a full-screen page can swallow the keys you would use to leave it",
    "Requests are refused.",
  ],
  [
    "pointer-lock",
    `${C}.pointer_lock`,
    "3",
    "<2",
    "2",
    "settings",
    17,
    "Sites may capture your mouse pointer",
    "a page can hide and hold the cursor",
    "Requests are refused; games will ask.",
  ],
  [
    "background-sync",
    "background_sync.enabled",
    "true",
    "true",
    "false",
    "privacy",
    46,
    "Sites may sync in the background after you leave",
    "a page keeps talking to its server once its tab is closed",
    "Pages sync while you have them open instead.",
  ],
  [
    "password-leak-detect",
    "profile.password_manager_leak_detection",
    "true",
    "true",
    "false",
    "privacy",
    45,
    "Saved passwords are checked against a remote breach service",
    "a hashed form of your credentials is sent for lookup — a real protection with a real disclosure",
    "Nothing about saving or filling passwords changes.",
  ],
  [
    "url-keyed-metrics",
    "url_keyed_anonymized_data_collection.enabled",
    "false",
    "true",
    "false",
    "privacy",
    59,
    "URL-keyed data collection is on",
    "measurements are reported tied to the pages you visit",
    "Browsing is unaffected.",
  ],
  [
    "feedback-allowed",
    "user_feedback_allowed",
    "true",
    "true",
    "false",
    "privacy",
    30,
    "In-product feedback reporting is enabled",
    "a channel that can carry screenshots and page content",
    "You can still report a problem deliberately.",
  ],
  [
    "network-time",
    "network_time.network_time_mapping",
    "true",
    "true",
    "false",
    "privacy",
    16,
    "The browser queries a network time service",
    "a periodic request identifying the browser",
    "The system clock is used instead.",
  ],
  [
    "domain-reliability",
    "domain_reliability.allowed_by_enterprise_policy",
    "true",
    "true",
    "false",
    "privacy",
    44,
    "Connection failures are reported upstream",
    "which sites failed to load, and from where, is sent for analysis",
    "Nothing about loading changes.",
  ],
  [
    "autofill-assistant",
    "autofill_assistant.consent",
    "true",
    "true",
    "false",
    "privacy",
    29,
    "Automated browsing assistance is consented to",
    "a feature that reads page content to act on your behalf",
    "Nothing you use manually changes.",
  ],
  [
    "media-engagement",
    "media.engagement.record",
    "true",
    "true",
    "false",
    "privacy",
    28,
    "Media engagement is scored per site",
    "a per-site record of how much you watch and listen",
    "Autoplay decisions fall back to the default policy.",
  ],
  [
    "side-panel-companion",
    "side_panel.companion_enabled",
    "true",
    "true",
    "false",
    "privacy",
    27,
    "The browsing companion panel is enabled",
    "page content can be sent to a remote assistant",
    "The panel stops; browsing is unchanged.",
  ],
  [
    "quic-enabled",
    "net.quic_allowed",
    "true",
    "false",
    "true",
    "performance",
    26,
    "QUIC is disabled",
    "connections fall back to TCP, which is slower on lossy links",
    "Restores the default. Turn it off again if a proxy or firewall mishandles UDP.",
  ],
  [
    "prerender",
    "net.prediction_options_state",
    "1",
    "<2",
    "2",
    "privacy",
    43,
    "Pages are pre-rendered before you click",
    "the browser loads pages you have not chosen to visit, and the servers see it",
    "Prediction stops; loading is unaffected.",
  ],
  [
    "signin-promo",
    "signin.promo_shown_count",
    "0",
    ">5",
    "0",
    "settings",
    8,
    "Sign-in prompts have been shown repeatedly",
    "reported so persistent nagging is visible",
    "Resets the counter; the prompt setting itself is separate.",
  ],
  [
    "default-browser-nag",
    "browser.default_browser_setting_enabled",
    "true",
    "true",
    "false",
    "settings",
    10,
    "The browser checks whether it is the default at every start",
    "a dialog between you and the page you opened it for",
    "It still works as the default browser if it is one.",
  ],
  [
    "extensions-sideload",
    "extensions.ui.developer_mode",
    "false",
    "true",
    "false",
    "security",
    64,
    "Developer mode is enabled in the extension manager",
    "unpacked extensions can be loaded from disk, which is how a malicious one usually arrives",
    "Turn it off unless you are developing an extension.",
  ],
  [
    "safe-browsing-extended",
    "safebrowsing.extended_reporting_enabled",
    "false",
    "true",
    "false",
    "privacy",
    58,
    "Extended Safe Browsing reporting is on",
    "page content can be included in the reports it sends",
    "Standard protection is unaffected.",
  ],
  [
    "dns-over-https-off",
    "dns_over_https.mode",
    '"off"',
    "~off",
    '"automatic"',
    "privacy",
    57,
    "Encrypted DNS is switched off in the browser",
    "every name the browser looks up is visible to the network, whatever the traffic is encrypted with",
    "`automatic` uses encrypted DNS where your resolver supports it and falls back where it does not.",
  ],
  [
    "https-first-balanced",
    "https_first_balanced_mode_enabled",
    "false",
    "false",
    "true",
    "security",
    56,
    "HTTPS-First is not enabled for typed addresses",
    "a URL you type is tried over plain HTTP first",
    "The browser tries HTTPS first and falls back with a warning.",
  ],
];

export const CHROMIUM2_POLICIES: ChromiumPolicy[] = ROWS.map(
  (
    [id, path, fallback, bad, safe, category, weight, title, detail, because],
  ) => ({
    id: `cr2-${id}`,
    title,
    category,
    severity: weight >= 50 ? "major" as const : "minor" as const,
    weight,
    path,
    fallback,
    bad,
    safe,
    detail,
    because,
  }),
);
