// Chromium-family browser preferences — Chromium, Chrome, Brave, Edge,
// Vivaldi, Opera. They all keep the same JSON with the same key names.
//
// The content-setting rows use Chromium's own numbering: 1 is allow, 2 is
// block, 3 is ask. Blocking a capability outright is a real change, so the
// rows here block only the ones a page has no business having by default —
// and never the camera or microphone, which would break every call you take.
import type { ChromiumPolicy } from "../../type/policy.ts";

/** [id, path, fallback, bad, safe, cat, weight, title, detail, because] */
type Row = [
  string,
  string,
  string,
  ChromiumPolicy["bad"],
  string,
  ChromiumPolicy["category"],
  number,
  string,
  string,
  string,
];

const CONTENT = "profile.default_content_setting_values";

const ROWS: Row[] = [
  // --------------------------------------------------------------- privacy
  [
    "metrics",
    "user_experience_metrics.reporting_enabled",
    "false",
    "true",
    "false",
    "privacy",
    60,
    "Usage metrics are reported",
    "what you do in the browser is measured and uploaded",
    "Browsing is unaffected. Only the upload stops.",
  ],
  [
    "safebrowsing-enhanced",
    "safebrowsing.enhanced",
    "false",
    "true",
    "false",
    "privacy",
    59,
    "Enhanced Safe Browsing is on",
    "the URL of every page you visit is sent for scoring, not just a hash prefix",
    "Standard Safe Browsing stays on and still blocks known malware and phishing.",
  ],
  [
    "safebrowsing-reporting",
    "safebrowsing.scout_reporting_enabled",
    "false",
    "true",
    "false",
    "privacy",
    58,
    "Security incident reports are sent automatically",
    "page content can be included in a report you never saw",
    "Protection is unchanged; only the outbound report stops.",
  ],
  [
    "url-suggest",
    "search.suggest_enabled",
    "true",
    "true",
    "false",
    "privacy",
    57,
    "Every keystroke in the address bar goes to your search engine",
    "the search engine receives what you type before you press Enter, including things you never search for",
    "Suggestions stop; searching is unchanged.",
  ],
  [
    "alt-error-pages",
    "alternate_error_pages.enabled",
    "true",
    "true",
    "false",
    "privacy",
    56,
    "Failed URLs are sent for suggestions",
    "a mistyped or private address is uploaded to build an error page",
    "You get the browser's own error page instead.",
  ],
  [
    "spelling-service",
    "spellcheck.use_spelling_service",
    "false",
    "true",
    "false",
    "privacy",
    55,
    "Text you type is sent for spell-checking",
    "everything typed into a text box goes to a remote service",
    "The local dictionary still works.",
  ],
  [
    "dns-prefetch",
    "dns_prefetching.enabled",
    "true",
    "true",
    "false",
    "privacy",
    41,
    "The browser resolves links you have not clicked",
    "your resolver learns about pages you only looked at",
    "Clicking a link is imperceptibly slower.",
  ],
  [
    "network-prediction",
    "net.network_prediction_options",
    "1",
    "<2",
    "2",
    "privacy",
    40,
    "The browser preconnects to sites it guesses you will visit",
    "servers hear from you for pages you never open",
    "Prediction stops. Pages still load normally.",
  ],
  [
    "do-not-track",
    "enable_do_not_track",
    "false",
    "false",
    "true",
    "privacy",
    22,
    "The Do Not Track header is not sent",
    "sites are not told you object to being tracked",
    "A header is added. Nothing about page rendering changes.",
  ],

  // ------------------------------------------------------------ WebRTC leak
  [
    "webrtc-ip",
    "webrtc.ip_handling_policy",
    '"default"',
    "~default",
    '"disable_non_proxied_udp"',
    "privacy",
    74,
    "WebRTC reveals your local and real IP addresses",
    "any page with a script can read the addresses of every network interface, including behind a VPN",
    "Calls still work over the proxied path. Undo if a video call stops connecting.",
  ],
  [
    "webrtc-routes",
    "webrtc.multiple_routes_enabled",
    "true",
    "true",
    "false",
    "privacy",
    73,
    "WebRTC probes every network interface",
    "the second half of the address leak above",
    "Calls still connect over the default route.",
  ],
  [
    "webrtc-udp",
    "webrtc.nonproxied_udp_enabled",
    "true",
    "true",
    "false",
    "privacy",
    72,
    "WebRTC bypasses your proxy for UDP",
    "traffic you routed through a proxy or VPN goes around it",
    "Media follows the proxy like everything else.",
  ],

  // --------------------------------------------------------------- autofill
  [
    "autofill-cards",
    "autofill.credit_card_enabled",
    "true",
    "true",
    "false",
    "security",
    54,
    "Payment-card autofill is enabled",
    "card details can be filled into fields you cannot see",
    "Cards can still be typed in.",
  ],
  [
    "autofill-profile",
    "autofill.profile_enabled",
    "true",
    "true",
    "false",
    "privacy",
    53,
    "Address autofill is enabled",
    "your address can be filled into a hidden field by a hostile page",
    "Addresses can still be pasted.",
  ],
  [
    "payments-query",
    "payments.can_make_payment_enabled",
    "true",
    "true",
    "false",
    "privacy",
    39,
    "Sites may ask whether you can make a payment",
    "a fingerprinting signal available to any page, with no prompt",
    "Payment flows still work when you start one.",
  ],

  // ------------------------------------------------------------- background
  [
    "background-mode",
    "background_mode.enabled",
    "false",
    "true",
    "false",
    "resource",
    52,
    "The browser keeps running after you close it",
    "extensions and pages stay live, using memory and network, with no window to show for it",
    "Closing the last window closes the browser.",
  ],
  [
    "download-prompt",
    "download.prompt_for_download",
    "false",
    "false",
    "true",
    "security",
    51,
    "Downloads are saved without asking",
    "a drive-by download lands in your Downloads folder with no interaction at all",
    "You are asked where to save each file.",
  ],

  [
    "sync-disabled",
    "sync.requested",
    "false",
    "true",
    "false",
    "privacy",
    50,
    "Browser sync is on",
    "history, tabs, passwords and settings are uploaded to the vendor's account",
    "Sync stops. Nothing already synced is deleted, locally or remotely.",
  ],
  [
    "signin-allowed",
    "signin.allowed",
    "true",
    "true",
    "false",
    "privacy",
    38,
    "The browser may sign you into your web account automatically",
    "signing into a vendor site signs the browser in too, which links your browsing to that account",
    "Signing into a site no longer signs the browser in.",
  ],
  [
    "translate",
    "translate.enabled",
    "true",
    "true",
    "false",
    "privacy",
    37,
    "Page translation is enabled",
    "page content is sent to a translation service to offer the prompt",
    "The prompt stops. You can still translate a page deliberately.",
  ],
  [
    "search-autocomplete",
    "search.suggest_enabled_by_policy",
    "true",
    "true",
    "false",
    "privacy",
    36,
    "Search suggestions are enabled by policy",
    "the second switch that sends your keystrokes to a search engine",
    "Suggestions stop; searching is unchanged.",
  ],
  [
    "safe-browsing-standard",
    "safebrowsing.enabled",
    "true",
    "false",
    "true",
    "security",
    77,
    "Safe Browsing is switched off entirely",
    "known malware and phishing sites load without a warning",
    "Standard Safe Browsing checks hash prefixes locally. It is not the enhanced mode that uploads full URLs.",
  ],
  [
    "https-only",
    "https_only_mode_enabled",
    "false",
    "false",
    "true",
    "security",
    78,
    "HTTPS-First mode is off",
    "a page can load over plain HTTP without you noticing",
    "The browser tries HTTPS first and warns before falling back.",
  ],
  [
    "insecure-downloads",
    "download_restrictions",
    "0",
    "=0",
    "1",
    "security",
    62,
    "Dangerous downloads are not blocked",
    "the browser's own classification of a malicious download is not acted on",
    "Downloads flagged as malicious are blocked. Everything else is unaffected.",
  ],
  [
    "printing-preview",
    "printing.print_preview_sticky_settings.appState",
    "null",
    "~cloud",
    '"{}"',
    "privacy",
    18,
    "Print settings remember a cloud printer",
    "documents you print are routed through a remote service",
    "The remembered destination is cleared. Local printers are unaffected.",
  ],
  [
    "media-router",
    "media_router.cast_allow_all_ips",
    "false",
    "true",
    "false",
    "security",
    61,
    "Cast discovery reaches beyond your local subnet",
    "the browser probes for cast devices on networks it should not be scanning",
    "Discovery returns to the local subnet.",
  ],
  [
    "webauthn-remote",
    "webauthn.remote_proxied_requests_allowed",
    "false",
    "true",
    "false",
    "security",
    60,
    "Proxied WebAuthn requests are allowed",
    "a remote session can drive your security key",
    "Your security key works locally as before.",
  ],
  [
    "sandbox-network",
    `${CONTENT}.local_network_access`,
    "3",
    "<2",
    "2",
    "security",
    75,
    "Sites may reach devices on your local network",
    "a public web page can scan and talk to your router, printers and cameras",
    "Requests are refused. Sites you allow individually still work.",
  ],
  [
    "window-management",
    `${CONTENT}.window_placement`,
    "3",
    "<2",
    "2",
    "privacy",
    35,
    "Sites may enumerate your displays",
    "the number, size and arrangement of your monitors is a strong fingerprint",
    "Requests are refused.",
  ],
  [
    "storage-access",
    `${CONTENT}.storage_access`,
    "3",
    "<2",
    "2",
    "privacy",
    34,
    "Embedded third parties may request cross-site storage",
    "the mechanism that gives a tracker its cookies back inside an iframe",
    "Requests are refused. First-party storage is unaffected.",
  ],
  [
    "protocol-handlers",
    `${CONTENT}.protocol_handlers`,
    "3",
    "<2",
    "2",
    "security",
    59,
    "Sites may register themselves as protocol handlers",
    "a page can claim mailto: or a custom scheme and intercept those links",
    "Requests are refused. Handlers you already set stay.",
  ],
  [
    "fileedit-guard",
    `${CONTENT}.file_system_read_guard`,
    "3",
    "<2",
    "2",
    "security",
    76,
    "Sites may ask to read directories on your disk",
    "one grant hands a page a handle to a whole folder, and it keeps working later",
    "Requests are refused.",
  ],
  // --------------------------------------------------- capability defaults
  [
    "geolocation",
    `${CONTENT}.geolocation`,
    "3",
    "<2",
    "2",
    "privacy",
    71,
    "Sites may ask for your location",
    "a permission prompt is one misclick away from your coordinates",
    "Requests are refused outright. Undo, or allow the one site that needs it.",
  ],
  [
    "notifications",
    `${CONTENT}.notifications`,
    "3",
    "<2",
    "2",
    "privacy",
    70,
    "Sites may ask to send notifications",
    "the most abused prompt on the web, and each grant is a channel into your desktop",
    "Requests are refused. Sites you already allowed keep working.",
  ],
  [
    "auto-downloads",
    `${CONTENT}.automatic_downloads`,
    "3",
    "<2",
    "2",
    "security",
    69,
    "Sites may download multiple files automatically",
    "a page can drop a set of files into your Downloads folder",
    "Multiple downloads are refused; a single one you click still works.",
  ],
  [
    "midi",
    `${CONTENT}.midi_sysex`,
    "3",
    "<2",
    "2",
    "security",
    45,
    "Sites may ask for MIDI device access",
    "system-exclusive MIDI access can reprogram attached hardware",
    "Requests are refused.",
  ],
  [
    "serial",
    `${CONTENT}.serial_guard`,
    "3",
    "<2",
    "2",
    "security",
    68,
    "Sites may ask for serial port access",
    "a web page talking to a serial device is a direct line to attached hardware",
    "Requests are refused.",
  ],
  [
    "hid",
    `${CONTENT}.hid_guard`,
    "3",
    "<2",
    "2",
    "security",
    67,
    "Sites may ask for raw HID access",
    "a page could read from — or write to — an attached input device",
    "Requests are refused.",
  ],
  [
    "usb",
    `${CONTENT}.usb_guard`,
    "3",
    "<2",
    "2",
    "security",
    66,
    "Sites may ask for USB device access",
    "a page could talk to attached USB hardware directly",
    "Requests are refused.",
  ],
  [
    "bluetooth",
    `${CONTENT}.bluetooth_guard`,
    "3",
    "<2",
    "2",
    "security",
    65,
    "Sites may ask for Bluetooth access",
    "a page could reach devices paired with this machine",
    "Requests are refused.",
  ],
  [
    "sensors",
    `${CONTENT}.sensors`,
    "1",
    "<2",
    "2",
    "privacy",
    44,
    "Sites may read motion and light sensors",
    "sensor readings identify a device and can infer what is around it",
    "Access is refused.",
  ],
  [
    "idle-detection",
    `${CONTENT}.idle_detection`,
    "3",
    "<2",
    "2",
    "privacy",
    43,
    "Sites may detect when you are away from the machine",
    "a page learns your working pattern minute by minute",
    "Requests are refused.",
  ],
  [
    "clipboard",
    `${CONTENT}.clipboard`,
    "3",
    "<2",
    "2",
    "security",
    64,
    "Sites may ask to read your clipboard",
    "whatever you last copied — often a password — becomes readable by a page",
    "Requests are refused. Pasting yourself still works.",
  ],
  [
    "file-write",
    `${CONTENT}.file_system_write_guard`,
    "3",
    "<2",
    "2",
    "security",
    63,
    "Sites may ask to write files on your disk",
    "a page gets a handle it can keep writing through",
    "Requests are refused.",
  ],
  [
    "popups",
    `${CONTENT}.popups`,
    "2",
    "<2",
    "2",
    "security",
    42,
    "Sites may open pop-up windows",
    "pop-ups are still the delivery mechanism for a good share of scams",
    "Pop-ups are blocked; the button to allow one per site remains.",
  ],
];

export const CHROMIUM_POLICIES: ChromiumPolicy[] = ROWS.map(
  (
    [id, path, fallback, bad, safe, category, weight, title, detail, because],
  ) => ({
    id: `cr-${id}`,
    title,
    category,
    severity: weight >= 60 ? "major" as const : "minor" as const,
    weight,
    path,
    localState: path.startsWith("user_experience_metrics") ? true : undefined,
    fallback,
    bad,
    safe,
    detail,
    because,
  }),
);
