// Desktop settings, third pass: the file manager's remaining safety prompts,
// what the panel and the search box remember, and the peripheral behaviour that
// costs battery for nothing.
import type { SettingPolicy } from "../../type/policy.ts";
import {
  FILE_MANAGER,
  LOCKDOWN,
  NOTIFY,
  POWER,
  SCREENSAVER,
  SESSION,
  THUMB_CACHE,
} from "./schemas.ts";

const NEMO_MENU = ["org.nemo.preferences.menu-config"] as const;
const NEMO_DESKTOP = ["org.nemo.desktop"] as const;
const CINNAMON = ["org.cinnamon"] as const;
const TOUCHPAD = [
  "org.cinnamon.desktop.peripherals.touchpad",
  "org.gnome.desktop.peripherals.touchpad",
] as const;
const CIN_SOUNDS = ["org.cinnamon.sounds"] as const;
const MEDIA_KEYS = [
  "org.cinnamon.settings-daemon.plugins.power",
  "org.gnome.settings-daemon.plugins.power",
] as const;

/** [id, schemas, key, bad, safe, cat, sev, weight, title, detail, because] */
type Row = [
  string,
  readonly string[],
  string,
  SettingPolicy["bad"],
  string,
  SettingPolicy["category"],
  SettingPolicy["severity"],
  number,
  string,
  string,
  string,
];

const ROWS: Row[] = [
  // -------------------------------------------------------- file manager
  [
    "fm-menu-delete",
    NEMO_MENU,
    "selection-menu-move-to-trash",
    "false",
    "true",
    "settings",
    "minor",
    30,
    "The file manager's menu has no move-to-trash entry",
    "the only delete offered is the permanent one",
    "Restores the trash entry to the context menu.",
  ],
  [
    "fm-desktop-trash",
    NEMO_DESKTOP,
    "trash-icon-visible",
    "false",
    "true",
    "settings",
    "minor",
    8,
    "The trash is not visible on the desktop",
    "the one place deleted files can still be recovered from is out of sight",
    "The icon returns. Nothing in the trash changes.",
  ],
  [
    "fm-parent-dblclick",
    FILE_MANAGER,
    "click-double-parent-folder",
    "true",
    "false",
    "settings",
    "minor",
    7,
    "Double-clicking empty space goes to the parent folder",
    "a mis-aimed double click navigates away from what you were looking at",
    "The double click does nothing instead.",
  ],
  [
    "fm-home-desktop",
    FILE_MANAGER,
    "desktop-is-home-dir",
    "true",
    "false",
    "privacy",
    "minor",
    28,
    "Your home directory is the desktop",
    "every file in your home folder is on screen, including in screen shares",
    "The desktop becomes ~/Desktop. No file moves.",
  ],
  [
    "fm-context-all",
    FILE_MANAGER,
    "context-menus-show-all-actions",
    "true",
    "false",
    "settings",
    "minor",
    6,
    "The file manager shows every action in the context menu",
    "destructive entries sit next to ordinary ones in a long list",
    "The menu returns to its usual length.",
  ],

  // ------------------------------------------------------------- privacy
  [
    "screensaver-away",
    SCREENSAVER,
    "ask-for-away-message",
    "true",
    "false",
    "privacy",
    "minor",
    27,
    "The lock screen asks for an away message",
    "a note about where you are, displayed to anyone at the desk",
    "The prompt stops. Existing messages are not shown.",
  ],
  [
    "screensaver-info",
    SCREENSAVER,
    "show-info-panel",
    "true",
    "false",
    "privacy",
    "minor",
    26,
    "The lock screen shows an information panel",
    "battery, network and notification state readable without unlocking",
    "The clock stays; the panel goes.",
  ],
  [
    "screensaver-widgets",
    SCREENSAVER,
    "floating-widgets",
    "true",
    "false",
    "privacy",
    "minor",
    25,
    "The lock screen shows floating widgets",
    "more session state on display while locked",
    "The lock screen shows the clock and the password box.",
  ],
  [
    "thumbnail-remote",
    THUMB_CACHE,
    "maximum-size",
    "=-1",
    "256",
    "resource",
    "minor",
    24,
    "The thumbnail cache has no size limit",
    "small copies of every image you have ever previewed, kept forever",
    "A 256 MB ceiling applies from now on. Nothing is deleted by this change.",
  ],

  // ------------------------------------------------------------ lockdown
  [
    "lockdown-app-handlers",
    LOCKDOWN,
    "disable-application-handlers",
    "true",
    "false",
    "settings",
    "minor",
    23,
    "Applications cannot be launched from other applications",
    "links and attachments stop opening, usually unintentionally",
    "Restores normal handler behaviour.",
  ],
  [
    "lockdown-user-admin",
    LOCKDOWN,
    "user-administration-disabled",
    "true",
    "false",
    "settings",
    "minor",
    21,
    "User administration is disabled",
    "accounts cannot be added or changed from the settings app",
    "Restores the accounts panel.",
  ],

  // --------------------------------------------------------- power / perf
  [
    "power-notify-mouse",
    POWER,
    "power-notifications-for-mouse",
    "true",
    "false",
    "performance",
    "minor",
    4,
    "Battery notifications for the mouse interrupt you",
    "a low-battery popup for a peripheral, over whatever you are doing",
    "The mouse still reports its battery in settings.",
  ],
  [
    "power-notify-keyboard",
    POWER,
    "power-notifications-for-keyboard",
    "true",
    "false",
    "performance",
    "minor",
    3,
    "Battery notifications for the keyboard interrupt you",
    "the same interruption, for the other peripheral",
    "Battery level is still visible in settings.",
  ],
  [
    "power-notify-other",
    POWER,
    "power-notifications-for-other-devices",
    "true",
    "false",
    "performance",
    "minor",
    2,
    "Battery notifications for every connected device interrupt you",
    "one popup per paired device",
    "Battery levels are still visible in settings.",
  ],
  [
    "idle-brightness",
    POWER,
    "idle-brightness",
    ">50",
    "30",
    "resource",
    "minor",
    9,
    "The screen barely dims when idle",
    "the panel keeps drawing near-full power on an unattended machine",
    "Dimming to 30% is instantly reversed by any input.",
  ],
  [
    "lid-inhibit",
    POWER,
    "inhibit-lid-switch",
    "true",
    "false",
    "security",
    "minor",
    45,
    "Closing the lid does nothing",
    "a closed laptop stays awake and unlocked in your bag",
    "Closing the lid suspends again. Undo if you dock with the lid shut.",
  ],
  [
    "touchpad-typing",
    TOUCHPAD,
    "disable-while-typing",
    "false",
    "true",
    "settings",
    "minor",
    10,
    "The touchpad stays live while you type",
    "the cursor jumps mid-sentence and text lands in the wrong place",
    "The touchpad pauses briefly while you type.",
  ],
  [
    "cinnamon-devtools",
    CINNAMON,
    "development-tools",
    "true",
    "false",
    "security",
    "minor",
    46,
    "The desktop's developer console is enabled",
    "a shortcut opens a console that can run code inside the desktop shell",
    "The console stops opening. Nothing about the desktop changes.",
  ],
  [
    "sounds-notification",
    CIN_SOUNDS,
    "notification-enabled",
    "true",
    "false",
    "performance",
    "minor",
    1,
    "Every notification plays a sound",
    "the audio stack wakes for each one",
    "Notifications still appear silently.",
  ],
  [
    "session-idle-notify",
    NOTIFY,
    "fade-on-mouseover",
    "false",
    "true",
    "settings",
    "minor",
    11,
    "Notifications do not fade when you move over them",
    "a notification sits on top of the control you are reaching for",
    "They fade out of the way and stay in the tray.",
  ],
  [
    // The id predates the row's real subject and is kept because ids key the
    // fix log; what it checks is `backlight-helper-force`.
    "numlock-remember",
    MEDIA_KEYS,
    "backlight-helper-force",
    "true",
    "false",
    "resource",
    "minor",
    13,
    "Screen brightness is forced through the backlight helper",
    "every brightness change goes through a helper program instead of the kernel's own backlight interface",
    "The kernel interface is used directly where it works.",
  ],
  [
    "session-idle-zero",
    SESSION,
    "idle-delay",
    ">3600",
    "900",
    "security",
    "minor",
    47,
    "The session is considered active for over an hour of idle",
    "everything keyed to idle — locking, dimming, suspend — waits that long",
    "Fifteen minutes. Any input resets it.",
  ],
];

/** Rows that report rather than write, and the reason.
 *
 *  Every one of these is a timing or power preference the user is expected to
 *  choose. A row that overwrites a deliberate choice is not a fix — it is the
 *  app deciding it knows better than the person using the machine. */
const ADVISORY: Record<string, string> = {
  "lid-inhibit":
    "No automatic fix. Ignoring the lid switch is exactly what you want on a docked laptop with the lid shut, and turning it off would make the machine suspend the moment you close it. Change it in Power settings if it was not deliberate.",
  "numlock-remember":
    "No automatic fix. Forcing the backlight helper is the workaround for panels whose kernel backlight interface does nothing or picks the wrong device, and on those machines turning it off leaves the brightness keys dead. If brightness works either way, you can turn it off in dconf-editor under org.cinnamon.settings-daemon.plugins.power.",
  "idle-dim-ac":
    "No automatic fix. Whether the screen dims when you step away is a preference, not a fault. Change it in Power settings.",
};

export const DESKTOP3_POLICIES: SettingPolicy[] = ROWS.map(
  (
    [
      id,
      schemas,
      key,
      bad,
      safe,
      category,
      severity,
      weight,
      title,
      detail,
      because,
    ],
  ) => ({
    id: `d3-${id}`,
    title,
    category,
    severity,
    weight,
    schemas,
    key,
    bad,
    safe,
    detail,
    because,
    advisory: ADVISORY[id],
  }),
);
