// System services and login policy under /etc. Every row is reported only:
// these need root, and several of them restart a service that something is
// using right now.
import type { EtcPolicy } from "../../type/policy.ts";
import type { ConfFormat } from "../../type/policy.ts";

/** [id, file, format, section, key, safe, missingIsBad, cat, band, weight,
 *   title, detail, how] */
type Row = [
  string,
  string,
  ConfFormat,
  string | undefined,
  string,
  string,
  boolean,
  EtcPolicy["category"],
  EtcPolicy["severity"],
  number,
  string,
  string,
  string,
];

const reload = (unit: string) => `sudo systemctl restart ${unit}`;

const ROWS: Row[] = [
  // ---------------------------------------------------------- login policy
  [
    "logindefs-encrypt",
    "/etc/login.defs",
    "space",
    undefined,
    "ENCRYPT_METHOD",
    "YESCRYPT",
    true,
    "security",
    "major",
    74,
    "Passwords are hashed with an older algorithm",
    "the stored hash of every password on this machine is cheaper to crack than it needs to be",
    "Set `ENCRYPT_METHOD YESCRYPT` in /etc/login.defs. Existing hashes are upgraded the next time each password changes.",
  ],
  [
    "logindefs-umask",
    "/etc/login.defs",
    "space",
    undefined,
    "UMASK",
    "077",
    true,
    "security",
    "major",
    73,
    "New files are readable by other accounts by default",
    "every file any user creates starts out world-readable",
    "Set `UMASK 077` in /etc/login.defs. It applies to files created after the next login.",
  ],
  [
    "logindefs-maxdays",
    "/etc/login.defs",
    "space",
    undefined,
    "PASS_MAX_DAYS",
    "365",
    true,
    "settings",
    "minor",
    40,
    "Passwords never expire",
    "a password leaked years ago still works",
    "Set `PASS_MAX_DAYS 365` in /etc/login.defs, and apply it to existing accounts with `sudo chage -M 365 <user>`.",
  ],
  [
    "logindefs-warnage",
    "/etc/login.defs",
    "space",
    undefined,
    "PASS_WARN_AGE",
    "14",
    true,
    "settings",
    "minor",
    21,
    "No warning before a password expires",
    "the first sign is being locked out",
    "Set `PASS_WARN_AGE 14` in /etc/login.defs.",
  ],
  [
    "logindefs-failog",
    "/etc/login.defs",
    "space",
    undefined,
    "FAILLOG_ENAB",
    "yes",
    true,
    "security",
    "minor",
    39,
    "Failed logins are not recorded",
    "a brute-force attempt leaves no trace to notice",
    "Set `FAILLOG_ENAB yes` in /etc/login.defs.",
  ],
  [
    "logindefs-sulog",
    "/etc/login.defs",
    "space",
    undefined,
    "SULOG_FILE",
    "/var/log/sulog",
    true,
    "security",
    "minor",
    22,
    "Uses of `su` are not logged separately",
    "privilege changes are harder to reconstruct after an incident",
    "Set `SULOG_FILE /var/log/sulog` in /etc/login.defs.",
  ],

  // ------------------------------------------------------------- journald
  [
    "journald-storage",
    "/etc/systemd/journald.conf",
    "ini",
    "Journal",
    "Storage",
    "persistent",
    true,
    "settings",
    "major",
    63,
    "System logs do not survive a reboot",
    "the logs you need to explain a crash are erased by the crash",
    `Set \`Storage=persistent\` under [Journal] in /etc/systemd/journald.conf, then ${
      reload("systemd-journald")
    }.`,
  ],
  [
    "journald-maxuse",
    "/etc/systemd/journald.conf",
    "ini",
    "Journal",
    "SystemMaxUse",
    "1G",
    true,
    "resource",
    "minor",
    31,
    "The journal has no size cap",
    "logs grow until the disk decides the limit for them",
    `Set \`SystemMaxUse=1G\` under [Journal] in /etc/systemd/journald.conf, then ${
      reload("systemd-journald")
    }.`,
  ],
  [
    "journald-compress",
    "/etc/systemd/journald.conf",
    "ini",
    "Journal",
    "Compress",
    "yes",
    true,
    "resource",
    "minor",
    15,
    "Journal entries are stored uncompressed",
    "several times the disk for the same history",
    `Set \`Compress=yes\` under [Journal] in /etc/systemd/journald.conf.`,
  ],
  [
    "journald-forward",
    "/etc/systemd/journald.conf",
    "ini",
    "Journal",
    "ForwardToSyslog",
    "no",
    true,
    "performance",
    "minor",
    14,
    "Every log line is written twice",
    "journald and rsyslog both keep a copy of the same output",
    `Set \`ForwardToSyslog=no\` under [Journal] in /etc/systemd/journald.conf.`,
  ],

  // -------------------------------------------------------------- coredump
  [
    "coredump-storage",
    "/etc/systemd/coredump.conf",
    "ini",
    "Coredump",
    "Storage",
    "none",
    true,
    "privacy",
    "major",
    61,
    "Crashed programs write their memory to disk",
    "a core dump holds whatever the program had in memory, which routinely includes keys and passwords",
    "Set `Storage=none` under [Coredump] in /etc/systemd/coredump.conf.",
  ],
  [
    "coredump-maxuse",
    "/etc/systemd/coredump.conf",
    "ini",
    "Coredump",
    "ProcessSizeMax",
    "0",
    true,
    "privacy",
    "minor",
    32,
    "Core dumps are not size-limited",
    "a large crash can write gigabytes of process memory to disk",
    "Set `ProcessSizeMax=0` under [Coredump] in /etc/systemd/coredump.conf.",
  ],

  // -------------------------------------------------------------- resolved
  [
    "resolved-dnssec",
    "/etc/systemd/resolved.conf",
    "ini",
    "Resolve",
    "DNSSEC",
    "allow-downgrade",
    true,
    "security",
    "major",
    62,
    "DNS answers are not validated",
    "a forged DNS answer sends you to the wrong server with no sign that anything happened",
    `Set \`DNSSEC=allow-downgrade\` under [Resolve] in /etc/systemd/resolved.conf, then ${
      reload("systemd-resolved")
    }.`,
  ],
  [
    "resolved-dot",
    "/etc/systemd/resolved.conf",
    "ini",
    "Resolve",
    "DNSOverTLS",
    "opportunistic",
    true,
    "privacy",
    "major",
    60,
    "DNS queries travel in clear text",
    "everyone between you and the resolver sees every name you look up",
    `Set \`DNSOverTLS=opportunistic\` under [Resolve] in /etc/systemd/resolved.conf, then ${
      reload("systemd-resolved")
    }.`,
  ],
  [
    "resolved-llmnr",
    "/etc/systemd/resolved.conf",
    "ini",
    "Resolve",
    "LLMNR",
    "no",
    true,
    "security",
    "minor",
    48,
    "LLMNR name resolution is enabled",
    "anything on the local network can answer a name lookup and be believed — the classic credential-relay setup",
    `Set \`LLMNR=no\` under [Resolve] in /etc/systemd/resolved.conf.`,
  ],
  [
    "resolved-mdns",
    "/etc/systemd/resolved.conf",
    "ini",
    "Resolve",
    "MulticastDNS",
    "no",
    true,
    "privacy",
    "minor",
    34,
    "Multicast DNS is enabled",
    "the machine announces itself, by name, to the whole local network",
    `Set \`MulticastDNS=no\` under [Resolve] in /etc/systemd/resolved.conf. Turn it back on if you print or cast to local devices.`,
  ],

  // ---------------------------------------------------------------- avahi
  [
    "avahi-publish",
    "/etc/avahi/avahi-daemon.conf",
    "ini",
    "publish",
    "disable-publishing",
    "yes",
    true,
    "privacy",
    "minor",
    47,
    "This machine advertises its services on the local network",
    "its hostname, addresses and shared services are broadcast to everyone on the segment",
    "Set `disable-publishing=yes` under [publish] in /etc/avahi/avahi-daemon.conf, then `sudo systemctl restart avahi-daemon`.",
  ],
  [
    "avahi-workstation",
    "/etc/avahi/avahi-daemon.conf",
    "ini",
    "publish",
    "publish-workstation",
    "no",
    true,
    "privacy",
    "minor",
    33,
    "This machine advertises itself as a workstation",
    "your username and hostname are visible to the local network",
    "Set `publish-workstation=no` under [publish] in /etc/avahi/avahi-daemon.conf.",
  ],

  // ----------------------------------------------------------------- cups
  [
    "cups-listen",
    "/etc/cups/cupsd.conf",
    "space",
    undefined,
    "Listen",
    "localhost:631",
    true,
    "security",
    "major",
    59,
    "The print server listens beyond this machine",
    "a print daemon reachable from the network is a service you did not mean to run",
    "Change the `Listen` line in /etc/cups/cupsd.conf to `localhost:631`, then `sudo systemctl restart cups`.",
  ],
  [
    "cups-browsing",
    "/etc/cups/cupsd.conf",
    "space",
    undefined,
    "Browsing",
    "Off",
    true,
    "privacy",
    "minor",
    35,
    "The print server browses and advertises printers",
    "printer discovery traffic announces this machine continuously",
    "Set `Browsing Off` in /etc/cups/cupsd.conf.",
  ],

  // ------------------------------------------------------- NetworkManager
  [
    "nm-mac-scan",
    "/etc/NetworkManager/NetworkManager.conf",
    "ini",
    "device",
    "wifi.scan-rand-mac-address",
    "yes",
    true,
    "privacy",
    "major",
    58,
    "Wi-Fi scans use your real hardware address",
    "every access point you walk past records the same identifier for this laptop",
    "Set `wifi.scan-rand-mac-address=yes` under [device] in /etc/NetworkManager/NetworkManager.conf.",
  ],
  [
    "nm-mac-connect",
    "/etc/NetworkManager/NetworkManager.conf",
    "ini",
    "connection",
    "wifi.cloned-mac-address",
    "stable",
    true,
    "privacy",
    "minor",
    46,
    "Connected Wi-Fi uses your real hardware address",
    "the network you join can recognise this exact laptop on every future visit",
    "Set `wifi.cloned-mac-address=stable` under [connection] in /etc/NetworkManager/NetworkManager.conf. `stable` keeps a per-network identity, which does not break captive portals.",
  ],
  [
    "nm-connectivity",
    "/etc/NetworkManager/NetworkManager.conf",
    "ini",
    "connectivity",
    "enabled",
    "false",
    true,
    "privacy",
    "minor",
    23,
    "The machine pings a connectivity-check server",
    "a periodic request announcing that this machine is online, to a third party",
    "Set `enabled=false` under [connectivity] in /etc/NetworkManager/NetworkManager.conf. Captive-portal detection stops with it.",
  ],

  // ----------------------------------------------------------------- sudo
  [
    "sudo-use-pty",
    "/etc/sudoers",
    "space",
    undefined,
    "Defaults",
    "use_pty",
    true,
    "security",
    "minor",
    45,
    "sudo does not run commands in a pseudo-terminal",
    "a program run under sudo can inject keystrokes back into your terminal",
    "Add `Defaults use_pty` with `sudo visudo`.",
  ],
  [
    "sudo-logfile",
    "/etc/sudoers",
    "space",
    undefined,
    "Defaults",
    "logfile=/var/log/sudo.log",
    true,
    "security",
    "minor",
    44,
    "sudo has no dedicated log",
    "reconstructing what was run as root means grepping the whole journal",
    "Add `Defaults logfile=/var/log/sudo.log` with `sudo visudo`.",
  ],

  // ------------------------------------------------------------------ apt
  [
    "apt-install-recommends",
    "/etc/apt/apt.conf.d/99local",
    "space",
    undefined,
    "APT::Install-Recommends",
    '"false";',
    true,
    "resource",
    "minor",
    13,
    "apt installs recommended packages automatically",
    "every install pulls in software you did not ask for, and each piece is more attack surface",
    'Add `APT::Install-Recommends "false";` to /etc/apt/apt.conf.d/99local. Existing packages are untouched.',
  ],
  [
    "apt-allow-unauth",
    "/etc/apt/apt.conf.d/99local",
    "space",
    undefined,
    "APT::Get::AllowUnauthenticated",
    '"false";',
    true,
    "security",
    "major",
    72,
    "apt may install unsigned packages",
    "a package with no valid signature is a package from anyone",
    'Add `APT::Get::AllowUnauthenticated "false";` to /etc/apt/apt.conf.d/99local.',
  ],
  [
    "logind-idle",
    "/etc/systemd/logind.conf",
    "ini",
    "Login",
    "IdleAction",
    "lock",
    true,
    "security",
    "minor",
    43,
    "An idle session is never acted on by the system",
    "if the desktop's own idle handling fails, nothing else locks the screen",
    "Set `IdleAction=lock` and `IdleActionSec=900` under [Login] in /etc/systemd/logind.conf, then `sudo systemctl restart systemd-logind`.",
  ],
  [
    "logind-killuser",
    "/etc/systemd/logind.conf",
    "ini",
    "Login",
    "KillUserProcesses",
    "yes",
    true,
    "security",
    "minor",
    30,
    "Processes survive after you log out",
    "a program started in one session keeps running with your credentials after you leave",
    "Set `KillUserProcesses=yes` under [Login] in /etc/systemd/logind.conf. Use `systemd-run --user --scope` for anything you deliberately want to outlive the session.",
  ],
  [
    "logind-handle-lid",
    "/etc/systemd/logind.conf",
    "ini",
    "Login",
    "HandleLidSwitch",
    "suspend",
    true,
    "security",
    "minor",
    29,
    "Closing the lid is not handled by the system",
    "a laptop that stays awake in a bag is a laptop that stays unlocked",
    "Set `HandleLidSwitch=suspend` under [Login] in /etc/systemd/logind.conf.",
  ],
  [
    "timesyncd-ntp",
    "/etc/systemd/timesyncd.conf",
    "ini",
    "Time",
    "NTP",
    "time.cloudflare.com",
    true,
    "settings",
    "minor",
    28,
    "No time server is configured",
    "a clock that drifts breaks TLS certificate validation, two-factor codes and log correlation, all at once",
    "Set `NTP=` under [Time] in /etc/systemd/timesyncd.conf, then `sudo systemctl restart systemd-timesyncd`.",
  ],
  [
    "unattended-enable",
    "/etc/apt/apt.conf.d/20auto-upgrades",
    "space",
    undefined,
    "APT::Periodic::Unattended-Upgrade",
    '"1";',
    true,
    "settings",
    "major",
    64,
    "Security updates are not installed unattended",
    "a published vulnerability stays open until you happen to run the updater",
    'Set `APT::Periodic::Unattended-Upgrade "1";` in /etc/apt/apt.conf.d/20auto-upgrades. Only the security pocket is applied by default.',
  ],
  [
    "unattended-update-list",
    "/etc/apt/apt.conf.d/20auto-upgrades",
    "space",
    undefined,
    "APT::Periodic::Update-Package-Lists",
    '"1";',
    true,
    "settings",
    "minor",
    27,
    "The package index is not refreshed on a schedule",
    "the machine cannot know an update exists",
    'Set `APT::Periodic::Update-Package-Lists "1";` in /etc/apt/apt.conf.d/20auto-upgrades.',
  ],
  [
    "needrestart-mode",
    "/etc/needrestart/needrestart.conf",
    "space",
    undefined,
    "$nrconf{restart}",
    "'a'",
    true,
    "settings",
    "minor",
    26,
    "Services are not restarted after a library update",
    "a patched library is on disk while every running program still holds the old one in memory",
    "Set `$nrconf{restart} = 'a';` in /etc/needrestart/needrestart.conf, or run `sudo needrestart` after updates.",
  ],
  [
    "sysstat-enabled",
    "/etc/default/sysstat",
    "equals",
    undefined,
    "ENABLED",
    '"true"',
    true,
    "settings",
    "minor",
    25,
    "System activity is not being recorded",
    "when the machine was slow yesterday there is nothing to look at",
    'Set `ENABLED="true"` in /etc/default/sysstat, then `sudo systemctl enable --now sysstat`.',
  ],
  [
    "grub-timeout",
    "/etc/default/grub",
    "equals",
    undefined,
    "GRUB_TIMEOUT",
    "3",
    true,
    "performance",
    "minor",
    9,
    "The boot menu waits a long time",
    "seconds added to every boot for a menu nobody uses",
    "Set `GRUB_TIMEOUT=3` in /etc/default/grub and run `sudo update-grub`.",
  ],
  [
    "grub-audit",
    "/etc/default/grub",
    "equals",
    undefined,
    "GRUB_CMDLINE_LINUX_DEFAULT",
    "quiet splash",
    false,
    "settings",
    "minor",
    8,
    "Kernel command line differs from the distribution default",
    "reported so an unexpected boot parameter — a disabled mitigation, for instance — is visible",
    "Check the value in /etc/default/grub. `mitigations=off` and `apparmor=0` are the two worth noticing.",
  ],
  [
    "rsyslog-fileperms",
    "/etc/rsyslog.conf",
    "space",
    undefined,
    "$FileCreateMode",
    "0640",
    true,
    "security",
    "minor",
    24,
    "New log files are created world-readable",
    "logs routinely contain usernames, addresses and occasionally secrets",
    "Set `$FileCreateMode 0640` in /etc/rsyslog.conf, then `sudo systemctl restart rsyslog`.",
  ],
  [
    "chrony-sources",
    "/etc/chrony/chrony.conf",
    "space",
    undefined,
    "makestep",
    "1.0 3",
    true,
    "settings",
    "minor",
    7,
    "A large clock offset is corrected only by slewing",
    "a machine that boots with a badly wrong clock takes hours to converge, and TLS fails throughout",
    "Add `makestep 1.0 3` to /etc/chrony/chrony.conf.",
  ],
];

export const ETC_SYSTEM_POLICIES: EtcPolicy[] = ROWS.map(
  (
    [
      id,
      file,
      format,
      section,
      key,
      safe,
      missingIsBad,
      category,
      severity,
      weight,
      title,
      detail,
      how,
    ],
  ): EtcPolicy => ({
    id: `etc-${id}`,
    title,
    category,
    severity,
    weight,
    file,
    format,
    section,
    key,
    safe,
    missingIsBad,
    detail,
    how,
  }),
);
