// The SSH server, if one is installed. Every row here is something an attacker
// on the network gets to try; the file only exists when openssh-server is
// present, so on a machine that does not accept SSH the whole family is silent.
import type { EtcPolicy } from "../../type/policy.ts";

const FILE = "/etc/ssh/sshd_config";

/** [key, safe, missingIsBad, band, weight, title, detail] */
type Row = [
  string,
  string,
  boolean,
  EtcPolicy["severity"],
  number,
  string,
  string,
];

const ROWS: Row[] = [
  [
    "PermitRootLogin",
    "no",
    true,
    "critical",
    96,
    "The SSH server allows root to log in",
    "an attacker guessing one password gets the whole machine, and every attempt is against a username they already know",
  ],
  [
    "PermitEmptyPasswords",
    "no",
    false,
    "critical",
    95,
    "The SSH server accepts empty passwords",
    "an account with no password is an open door",
  ],
  [
    "PasswordAuthentication",
    "no",
    false,
    "major",
    84,
    "The SSH server accepts password logins",
    "every password on the machine is exposed to unlimited guessing from the network",
  ],
  [
    "ChallengeResponseAuthentication",
    "no",
    false,
    "major",
    70,
    "Challenge-response authentication is enabled",
    "a second password path that is easy to forget when hardening the first",
  ],
  [
    "KbdInteractiveAuthentication",
    "no",
    false,
    "major",
    69,
    "Keyboard-interactive authentication is enabled",
    "the modern spelling of the password path above",
  ],
  [
    "HostbasedAuthentication",
    "no",
    true,
    "major",
    82,
    "Host-based authentication is enabled",
    "trust is granted by source host, which is trivially forged on a network you do not control",
  ],
  [
    "IgnoreRhosts",
    "yes",
    true,
    "major",
    81,
    "The SSH server honours .rhosts files",
    "a file in any home directory can grant access",
  ],
  [
    "PermitUserEnvironment",
    "no",
    true,
    "major",
    80,
    "Users may set environment variables at login",
    "an entry in ~/.ssh/environment can change what runs on connect",
  ],
  [
    "X11Forwarding",
    "no",
    false,
    "major",
    79,
    "The SSH server offers X11 forwarding",
    "a connecting client gets a channel into the display server",
  ],
  [
    "AllowAgentForwarding",
    "no",
    false,
    "major",
    78,
    "The SSH server allows agent forwarding",
    "a session on this machine can reach back through a visitor's keys",
  ],
  [
    "AllowTcpForwarding",
    "no",
    false,
    "minor",
    54,
    "The SSH server allows TCP forwarding",
    "an authenticated user can tunnel to anything this machine can reach",
  ],
  [
    "GatewayPorts",
    "no",
    false,
    "major",
    77,
    "Forwarded ports are exposed to the network",
    "a tunnel one user opens becomes reachable by everyone",
  ],
  [
    "PermitTunnel",
    "no",
    false,
    "major",
    76,
    "The SSH server permits tunnel devices",
    "a client can build a network interface into this machine",
  ],
  [
    "MaxAuthTries",
    "3",
    true,
    "minor",
    53,
    "The SSH server allows many authentication attempts per connection",
    "each connection gets several guesses, which multiplies a brute-force",
  ],
  [
    "MaxSessions",
    "4",
    true,
    "minor",
    30,
    "The SSH server allows many sessions per connection",
    "one connection can multiplex more work than a person needs",
  ],
  [
    "LoginGraceTime",
    "60",
    true,
    "minor",
    52,
    "Half-open logins are held for a long time",
    "unauthenticated connections can be held open to exhaust the server",
  ],
  [
    "ClientAliveInterval",
    "300",
    true,
    "minor",
    51,
    "Idle SSH sessions are never timed out",
    "a forgotten session stays authenticated indefinitely",
  ],
  [
    "ClientAliveCountMax",
    "2",
    true,
    "minor",
    29,
    "Idle sessions survive many missed keepalives",
    "the timeout above takes far longer than it looks",
  ],
  [
    "StrictModes",
    "yes",
    true,
    "major",
    75,
    "The SSH server does not check file ownership",
    "a world-writable ~/.ssh is accepted rather than refused",
  ],
  [
    "UsePAM",
    "yes",
    true,
    "minor",
    50,
    "PAM is not used for SSH sessions",
    "account expiry, limits and lockout policies are bypassed",
  ],
  [
    "LogLevel",
    "VERBOSE",
    true,
    "minor",
    49,
    "SSH logging does not record key fingerprints",
    "you cannot tell which key was used for a login after the fact",
  ],
  [
    "Banner",
    "/etc/issue.net",
    true,
    "minor",
    20,
    "No banner is shown before login",
    "in some jurisdictions a banner is what makes unauthorised access prosecutable",
  ],
  [
    "KerberosAuthentication",
    "no",
    true,
    "minor",
    28,
    "Kerberos authentication is enabled on the server",
    "an authentication path almost no workstation uses",
  ],
  [
    "GSSAPIAuthentication",
    "no",
    true,
    "minor",
    27,
    "GSSAPI authentication is enabled on the server",
    "another rarely used authentication path left switched on",
  ],
  [
    "Compression",
    "no",
    true,
    "minor",
    26,
    "Compression is offered before authentication",
    "compression code is reachable by an unauthenticated client",
  ],
  [
    "TCPKeepAlive",
    "no",
    true,
    "minor",
    19,
    "TCP keepalives are used instead of protocol-level ones",
    "spoofed TCP resets can drop sessions that ClientAlive would have kept",
  ],
  [
    "PrintLastLog",
    "yes",
    true,
    "minor",
    18,
    "The last-login line is not shown",
    "the cheapest way for a user to notice a login they did not make",
  ],
  [
    "MaxStartups",
    "10:30:60",
    true,
    "minor",
    25,
    "Concurrent unauthenticated connections are unlimited",
    "a trivial way to exhaust the server's connection slots",
  ],
  [
    "Protocol",
    "2",
    false,
    "critical",
    94,
    "The SSH server may speak protocol version 1",
    "SSH-1 is broken and has been for twenty years",
  ],
  [
    "PubkeyAuthentication",
    "yes",
    true,
    "major",
    68,
    "Public-key authentication is disabled",
    "the only login method that cannot be guessed is switched off",
  ],
];

export const ETC_SSH_POLICIES: EtcPolicy[] = ROWS.map(
  ([key, safe, missingIsBad, severity, weight, title, detail]): EtcPolicy => ({
    id: `sshd-${key.toLowerCase()}`,
    title,
    category: "security",
    severity,
    weight,
    file: FILE,
    format: "space",
    key,
    safe,
    missingIsBad,
    detail,
    how:
      `Set \`${key} ${safe}\` in ${FILE} (or a file in /etc/ssh/sshd_config.d/) ` +
      `and reload with \`sudo systemctl reload ssh\`. Check you still have a ` +
      `working way in before you disconnect.`,
  }),
);
