// A third pass over /etc: the files that decide how the machine boots, what it
// logs, how it schedules work, and what it trusts.
import type { ConfFormat, EtcPolicy } from "../../type/policy.ts";

type Row = [
  string,
  string,
  ConfFormat,
  string | undefined,
  string,
  string,
  boolean,
  EtcPolicy["category"],
  EtcPolicy["severity"],
  number,
  string,
  string,
  string,
];

const ROWS: Row[] = [
  [
    "grub-password",
    "/etc/grub.d/40_custom",
    "line",
    undefined,
    "set superusers",
    "",
    true,
    "security",
    "minor",
    40,
    "The bootloader has no password",
    "anyone at the keyboard can edit the kernel command line and boot to a root shell",
    "Set a GRUB password with `grub-mkpasswd-pbkdf2` and a `set superusers` line in /etc/grub.d/40_custom, then `sudo update-grub`. Keep a recovery plan — a forgotten GRUB password is a live-USB job.",
  ],
  [
    "grub-lockdown",
    "/etc/default/grub",
    "equals",
    undefined,
    "GRUB_CMDLINE_LINUX_DEFAULT",
    "quiet splash lockdown=confidentiality",
    true,
    "security",
    "minor",
    38,
    "Kernel lockdown is not enabled",
    "root can load unsigned modules and read kernel memory, so Secure Boot's guarantee stops at the bootloader",
    "Add `lockdown=confidentiality` to GRUB_CMDLINE_LINUX_DEFAULT. It breaks unsigned DKMS modules — check your graphics driver first.",
  ],
  [
    "fstab-nofail",
    "/etc/fstab",
    "line",
    undefined,
    "nofail",
    "",
    true,
    "stability",
    "minor",
    46,
    "A removable mount can block boot",
    "an external disk listed in /etc/fstab that is not attached stops the machine at boot until you intervene",
    "Add `nofail` (and `x-systemd.device-timeout=5`) to the options of any mount that is not always present.",
  ],
  [
    "crypttab-tries",
    "/etc/crypttab",
    "line",
    undefined,
    "tries=",
    "",
    true,
    "stability",
    "minor",
    20,
    "The disk unlock prompt has no retry limit",
    "reported for awareness; the default is usually sensible",
    "Add `tries=3` in /etc/crypttab if you want a fixed limit.",
  ],
  [
    "logrotate-compress",
    "/etc/logrotate.conf",
    "line",
    undefined,
    "compress",
    "",
    true,
    "resource",
    "minor",
    26,
    "Rotated logs are not compressed",
    "several times the disk for the same history",
    "Uncomment `compress` in /etc/logrotate.conf.",
  ],
  [
    "rsyslog-remote",
    "/etc/rsyslog.conf",
    "line",
    undefined,
    'module(load="imudp")',
    "",
    false,
    "security",
    "major",
    66,
    "The log daemon accepts records from the network",
    "anyone on the network can write into this machine's logs",
    "Comment out the `imudp`/`imtcp` module lines in /etc/rsyslog.conf unless this machine is a log server.",
  ],
  [
    "issue-banner",
    "/etc/issue.net",
    "line",
    undefined,
    "Authorized uses only",
    "",
    true,
    "settings",
    "minor",
    12,
    "There is no pre-login banner",
    "in some jurisdictions a banner is what makes unauthorised access prosecutable",
    "Write one to /etc/issue.net and reference it with `Banner /etc/issue.net` in sshd_config.",
  ],
  [
    "motd-dynamic",
    "/etc/default/motd-news",
    "equals",
    undefined,
    "ENABLED",
    "0",
    true,
    "privacy",
    "minor",
    44,
    "The login message is fetched from the vendor",
    "every terminal you open makes a request carrying your release and architecture",
    "Set `ENABLED=0` in /etc/default/motd-news.",
  ],
  [
    "profile-umask",
    "/etc/profile",
    "line",
    undefined,
    "umask 077",
    "",
    true,
    "security",
    "minor",
    48,
    "The system-wide umask is permissive",
    "files created by login shells are readable by other accounts by default",
    "Prefer `UMASK 077` in /etc/login.defs plus `pam_umask` — a line in /etc/profile misses non-shell logins.",
  ],
  [
    "securetty-empty",
    "/etc/securetty",
    "line",
    undefined,
    "console",
    "",
    false,
    "security",
    "minor",
    30,
    "Root may log in on physical consoles",
    "a console login bypasses sudo's logging entirely",
    "An empty /etc/securetty prevents root console logins. Keep a recovery route first.",
  ],
  [
    "nsswitch-hosts",
    "/etc/nsswitch.conf",
    "space",
    undefined,
    "hosts:",
    "files dns",
    false,
    "security",
    "minor",
    50,
    "Name resolution consults multicast protocols",
    "`mdns` and `llmnr` in the hosts line let anything on the local network answer a name lookup and be believed",
    "Reduce the `hosts:` line in /etc/nsswitch.conf to `files dns` unless you rely on local device discovery.",
  ],
  [
    "sudo-timeout",
    "/etc/sudoers",
    "space",
    undefined,
    "Defaults",
    "timestamp_timeout=5",
    true,
    "security",
    "minor",
    52,
    "A sudo authorisation lasts a long time",
    "after one password, any program you start inherits a window in which sudo does not ask again",
    "Add `Defaults timestamp_timeout=5` with `sudo visudo`.",
  ],
  [
    "sudo-tty-tickets",
    "/etc/sudoers",
    "space",
    undefined,
    "Defaults",
    "timestamp_type=tty",
    true,
    "security",
    "minor",
    54,
    "A sudo authorisation is shared across terminals",
    "authenticating in one terminal silently authorises every other terminal you have open",
    "Add `Defaults timestamp_type=tty` with `sudo visudo`.",
  ],
  [
    "sudo-env-reset",
    "/etc/sudoers",
    "space",
    undefined,
    "Defaults",
    "env_reset",
    true,
    "security",
    "critical",
    82,
    "sudo passes your environment through to root",
    "variables like LD_PRELOAD reach the privileged process, which is a direct escalation path",
    "Add `Defaults env_reset` with `sudo visudo`. It is the default on most systems; its absence is a red flag.",
  ],
  [
    "pam-nullok",
    "/etc/pam.d/common-auth",
    "line",
    undefined,
    "nullok",
    "",
    false,
    "security",
    "critical",
    90,
    "PAM accepts empty passwords",
    "`nullok` on the unix module means an account with no password can log in",
    "Remove `nullok` from the pam_unix line in /etc/pam.d/common-auth.",
  ],
  [
    "apt-sandbox",
    "/etc/apt/apt.conf.d/99local",
    "space",
    undefined,
    "APT::Sandbox::Seccomp",
    '"true";',
    true,
    "security",
    "minor",
    36,
    "apt does not sandbox its download helpers",
    "the code that parses what comes off the network runs unconfined",
    'Add `APT::Sandbox::Seccomp "true";` to /etc/apt/apt.conf.d/99local.',
  ],
  [
    "dpkg-verify",
    "/etc/dpkg/dpkg.cfg",
    "line",
    undefined,
    "no-debsig",
    "",
    false,
    "security",
    "minor",
    34,
    "Package signature checking is relaxed",
    "`no-debsig` disables per-package signature verification",
    "Remove the `no-debsig` line from /etc/dpkg/dpkg.cfg.",
  ],
  [
    "chrony-nts",
    "/etc/chrony/chrony.conf",
    "space",
    undefined,
    "nts",
    "",
    true,
    "security",
    "minor",
    32,
    "Time synchronisation is unauthenticated",
    "a forged NTP response can move the clock, and a wrong clock breaks certificate validation",
    "Use an NTS-capable server: `server time.cloudflare.com iburst nts` in /etc/chrony/chrony.conf.",
  ],
  [
    "timesyncd-fallback",
    "/etc/systemd/timesyncd.conf",
    "ini",
    "Time",
    "FallbackNTP",
    "time.cloudflare.com",
    true,
    "stability",
    "minor",
    24,
    "There is no fallback time server",
    "if the primary is unreachable the clock simply drifts",
    "Set `FallbackNTP=` under [Time] in /etc/systemd/timesyncd.conf.",
  ],
  [
    "sysctl-conf-local",
    "/etc/sysctl.d/99-local.conf",
    "space",
    undefined,
    "kernel.dmesg_restrict",
    "1",
    true,
    "settings",
    "minor",
    16,
    "There is no local kernel-parameter file",
    "every kernel setting this catalogue reports has to be applied by hand each time",
    "Create /etc/sysctl.d/99-local.conf and put the settings you accept in it, then `sudo sysctl --system`.",
  ],
  [
    "fail2ban-absent",
    "/etc/fail2ban/jail.local",
    "line",
    undefined,
    "[sshd]",
    "",
    true,
    "security",
    "minor",
    56,
    "Nothing bans repeated authentication failures",
    "a brute-force attempt against SSH or a web service runs indefinitely",
    "`sudo apt install fail2ban`, then create /etc/fail2ban/jail.local with the jails you want. Only useful if something is reachable from the network.",
  ],
  [
    "apparmor-enabled",
    "/etc/default/grub",
    "equals",
    undefined,
    "GRUB_CMDLINE_LINUX_DEFAULT",
    "quiet splash apparmor=1 security=apparmor",
    true,
    "security",
    "minor",
    58,
    "Mandatory access control is not forced on at boot",
    "AppArmor confines browsers and other exposed programs; without it a compromise reaches everything you can",
    "Add `apparmor=1 security=apparmor` to GRUB_CMDLINE_LINUX_DEFAULT and `sudo update-grub`.",
  ],
  [
    "auditd-rules",
    "/etc/audit/rules.d/audit.rules",
    "line",
    undefined,
    "-w /etc/passwd -p wa",
    "",
    true,
    "security",
    "minor",
    28,
    "Changes to the account database are not audited",
    "an account added or a sudoers file edited leaves no dedicated record",
    "Install `auditd` and add watch rules for /etc/passwd, /etc/shadow, /etc/sudoers.",
  ],
  [
    "modprobe-blacklist",
    "/etc/modprobe.d/99-local.conf",
    "line",
    undefined,
    "install dccp /bin/false",
    "",
    true,
    "security",
    "minor",
    22,
    "There is no local module blacklist",
    "the unused protocol and filesystem modules this catalogue reports load on demand",
    "Create /etc/modprobe.d/99-local.conf with an `install <module> /bin/false` line for each module you do not need.",
  ],
];

export const ETC_HARDENING_POLICIES: EtcPolicy[] = ROWS.map(
  (
    [
      id,
      file,
      format,
      section,
      key,
      safe,
      missingIsBad,
      category,
      severity,
      weight,
      title,
      detail,
      how,
    ],
  ): EtcPolicy => ({
    id: `etch-${id}`,
    title,
    category,
    severity,
    weight,
    file,
    format,
    section,
    key,
    safe,
    missingIsBad,
    detail,
    how,
  }),
);
