// File-manager behaviour. The theme is the same one throughout: make the
// destructive path ask, and stop previewing things you have not opened.
import type { SettingPolicy } from "../../type/policy.ts";
import { FILE_MANAGER } from "./schemas.ts";

export const FILEMGR_POLICIES: SettingPolicy[] = [
  {
    id: "fm-confirm-trash",
    title: "Moving files to the trash happens without confirmation",
    category: "settings",
    severity: "major",
    weight: 68,
    schemas: FILE_MANAGER,
    key: "confirm-move-to-trash",
    bad: "false",
    safe: "true",
    detail: "a mis-aimed drag or a stray Delete removes files silently",
    because:
      "One dialog before a delete. Nothing already trashed is affected, and " +
      "Undo puts the setting back.",
  },
  {
    id: "fm-confirm-empty-trash",
    title: "Emptying the trash happens without confirmation",
    category: "settings",
    severity: "major",
    weight: 67,
    schemas: FILE_MANAGER,
    key: "confirm-trash",
    bad: "false",
    safe: "true",
    detail: "the one irreversible action in the file manager does not ask",
    because: "Emptying the trash cannot be undone; being asked first can.",
  },
  {
    id: "fm-permanent-delete",
    title: "Permanent delete is offered next to normal delete",
    category: "settings",
    severity: "major",
    weight: 64,
    schemas: FILE_MANAGER,
    key: "enable-delete",
    bad: "true",
    safe: "false",
    detail: "a menu entry deletes files outright, skipping the trash entirely",
    because:
      "Shift+Delete still works when you mean it; the menu stops offering " +
      "it by accident.",
  },
  {
    id: "fm-mime-executable",
    title: "The file manager may mark downloaded files executable",
    category: "security",
    severity: "major",
    weight: 76,
    schemas: FILE_MANAGER,
    key: "enable-mime-actions-make-executable",
    bad: "true",
    safe: "false",
    detail: "opening a file can turn it into something that runs",
    because: "You can still mark a file executable yourself in its properties.",
  },
  {
    id: "fm-thumbnail-inherit",
    title: "Thumbnails are generated on remote and removable filesystems",
    category: "security",
    severity: "minor",
    weight: 47,
    schemas: FILE_MANAGER,
    key: "inherit-show-thumbnails",
    bad: "true",
    safe: "false",
    detail: "untrusted files are parsed by preview helpers to draw an icon",
    because: "Files still open normally; only automatic previews stop.",
  },
  {
    id: "fm-detect-content",
    title: "The file manager inspects file contents to pick an action",
    category: "security",
    severity: "minor",
    weight: 20,
    schemas: FILE_MANAGER,
    key: "detect-content",
    bad: "true",
    safe: "false",
    detail: "inserted media is sniffed to decide what to launch",
    because: "The drive still opens; the guess about what to run stops.",
  },
  {
    id: "fm-preload-limit",
    title: "The file manager preloads attributes for large folders",
    category: "performance",
    severity: "minor",
    weight: 1,
    schemas: FILE_MANAGER,
    key: "deferred-attribute-preload-limit",
    bad: ">200",
    safe: "150",
    detail: "big directories stat hundreds of files before drawing",
    because: "Lower limit, same listing — attributes load as you scroll.",
  },
  {
    id: "fm-menu-warning",
    title: "The file manager's menu warning has been suppressed",
    category: "settings",
    severity: "minor",
    weight: 1,
    schemas: FILE_MANAGER,
    key: "disable-menu-warning",
    bad: "true",
    safe: "false",
    detail: "a safety prompt was dismissed permanently",
    because: "Restores the prompt. Undo removes it again.",
  },
];
