// Firefox, second pass: the capabilities a page gets for free, the things the
// browser writes to disk about where you have been, and the network calls it
// makes on its own behalf.
import type { MozPolicy } from "../../type/policy.ts";

/** [id, pref, fallback, bad, safe, cat, weight, title, detail, because] */
type Row = [
  string,
  string,
  string,
  MozPolicy["bad"],
  string,
  MozPolicy["category"],
  number,
  string,
  string,
  string,
];

const ROWS: Row[] = [
  // ------------------------------------------------- capabilities to pages
  [
    "beacon",
    "beacon.enabled",
    "true",
    "true",
    "false",
    "privacy",
    68,
    "Pages can send data as they close",
    "sendBeacon is the tracking call designed to survive you navigating away",
    "Ordinary requests still work. Only the fire-and-forget channel closes.",
  ],
  [
    "dom-push",
    "dom.push.enabled",
    "true",
    "true",
    "false",
    "privacy",
    67,
    "Web push is enabled",
    "a site you allowed once keeps a channel open to your desktop indefinitely",
    "Sites can no longer register for push. Existing subscriptions stop.",
  ],
  [
    "battery-api",
    "dom.battery.enabled",
    "true",
    "true",
    "false",
    "privacy",
    66,
    "Pages can read your battery level",
    "battery level and charge rate identify a device across sites for minutes at a time",
    "No page needs it; nothing legitimate breaks.",
  ],
  [
    "window-move",
    "dom.disable_window_move_resize",
    "false",
    "false",
    "true",
    "security",
    65,
    "Pages can move and resize your window",
    "the classic way to hide the address bar or fake a system dialog",
    "The page still renders; it stops moving your window.",
  ],

  // ------------------------------------------------------ what hits disk
  [
    "page-thumbnails",
    "browser.pagethumbnails.capturing_disabled",
    "false",
    "false",
    "true",
    "privacy",
    64,
    "Firefox saves screenshots of pages you visit",
    "images of pages you have been on sit in your profile directory",
    "The new-tab tiles lose their previews. Nothing else changes.",
  ],
  [
    "session-privacy",
    "browser.sessionstore.privacy_level",
    "0",
    "<2",
    "2",
    "privacy",
    63,
    "Form contents are written to disk for session restore",
    "what you typed into a form — including a partially filled one — is saved to your profile",
    "Tabs still restore; their form contents do not.",
  ],
  [
    "temp-file-cleanup",
    "browser.helperApps.deleteTempFileOnExit",
    "false",
    "false",
    "true",
    "privacy",
    62,
    "Files opened from the browser are left in /tmp",
    "every attachment you previewed stays on disk after you close it",
    "The file is removed when Firefox exits. Files you saved deliberately are untouched.",
  ],
  [
    "downloads-tmp",
    "browser.download.start_downloads_in_tmp_dir",
    "false",
    "false",
    "true",
    "security",
    61,
    "Downloads land directly in your Downloads folder",
    "a file arrives at its final location before you have decided to keep it",
    "Downloads land in a temporary directory and move when you keep them.",
  ],
  [
    "breach-alerts",
    "signon.management.page.breach-alerts.enabled",
    "true",
    "false",
    "true",
    "security",
    30,
    "Firefox does not warn when a site you log in to is breached",
    "a site you keep a saved login for can publish a breach and nothing tells you to change that password",
    "Firefox downloads the public breach list and compares it on this machine; nothing about your logins is sent anywhere.",
  ],

  // ---------------------------------------------- calls Firefox makes itself
  [
    "captive-portal",
    "network.captive-portal-service.enabled",
    "true",
    "true",
    "false",
    "privacy",
    60,
    "Firefox probes a Mozilla server to detect captive portals",
    "a periodic request that announces the browser is online",
    "Captive-portal detection stops. Portals still work; you just navigate to them.",
  ],
  [
    "connectivity-service",
    "network.connectivity-service.enabled",
    "true",
    "true",
    "false",
    "privacy",
    59,
    "Firefox probes for connectivity on its own",
    "another periodic beacon, to the same effect",
    "Firefox uses the system's connectivity state instead.",
  ],
  [
    "region-update",
    "browser.region.update.enabled",
    "true",
    "true",
    "false",
    "privacy",
    58,
    "Firefox looks up which country you are in",
    "your approximate location is fetched and stored on a schedule",
    "Search defaults stay as they are.",
  ],
  [
    "uitour",
    "browser.uitour.enabled",
    "true",
    "true",
    "false",
    "security",
    57,
    "Mozilla pages may drive the browser interface",
    "a privileged API that lets a web page highlight and open parts of your browser",
    "Onboarding tours stop working; nothing else uses it.",
  ],
  [
    "cfr-addons",
    "browser.newtabpage.activity-stream.asrouter.userprefs.cfr.addons",
    "true",
    "true",
    "false",
    "privacy",
    28,
    "Firefox recommends add-ons based on your browsing",
    "what you visit decides which extensions you are shown",
    "You can still browse add-ons yourself.",
  ],
  [
    "cfr-features",
    "browser.newtabpage.activity-stream.asrouter.userprefs.cfr.features",
    "true",
    "true",
    "false",
    "privacy",
    27,
    "Firefox recommends features based on your browsing",
    "the same mechanism, for browser features",
    "Nothing about the browser changes.",
  ],
  [
    "snippets",
    "browser.newtabpage.activity-stream.feeds.snippets",
    "true",
    "true",
    "false",
    "privacy",
    26,
    "Mozilla messages appear on the new-tab page",
    "content fetched from Mozilla on every new tab",
    "The page loads slightly faster.",
  ],
  [
    "highlights-downloads",
    "browser.newtabpage.activity-stream.section.highlights.includeDownloads",
    "true",
    "true",
    "false",
    "privacy",
    25,
    "Recent downloads are shown on the new-tab page",
    "the names of files you downloaded are on screen to anyone nearby",
    "Downloads are still in the downloads panel.",
  ],
  [
    "default-browser-check",
    "browser.shell.checkDefaultBrowser",
    "true",
    "true",
    "false",
    "performance",
    10,
    "Firefox checks whether it is the default browser at every start",
    "a startup dialog between you and the page you wanted",
    "Firefox still works as the default browser if it is one.",
  ],
  [
    "safebrowsing-downloads",
    "browser.safebrowsing.downloads.remote.enabled",
    "true",
    "true",
    "false",
    "privacy",
    24,
    "Download metadata is sent for reputation checking",
    "the name, size and source of everything you download goes to a remote service",
    "The local blocklist still blocks known-bad downloads.",
  ],

  // ---------------------------------------------------------------- TLS
  [
    "tls-min",
    "security.tls.version.min",
    "3",
    "<3",
    "3",
    "security",
    76,
    "Firefox will negotiate TLS 1.0 or 1.1",
    "protocol versions withdrawn from the web years ago are still offered",
    "TLS 1.2 becomes the floor. Sites older than that were already showing warnings.",
  ],
  [
    "insecure-text",
    "security.insecure_connection_text.enabled",
    "false",
    "false",
    "true",
    "security",
    56,
    "Plain HTTP pages are not labelled",
    "an unencrypted page looks the same as an encrypted one at a glance",
    "'Not secure' appears in the address bar for HTTP pages.",
  ],
  [
    "insecure-text-pbm",
    "security.insecure_connection_text.pbmode.enabled",
    "false",
    "false",
    "true",
    "security",
    55,
    "Plain HTTP is not labelled in private windows",
    "the same missing label, in the window you opened for privacy",
    "'Not secure' appears there too.",
  ],
  [
    "expert-bad-cert",
    "browser.xul.error_pages.expert_bad_cert",
    "false",
    "false",
    "true",
    "security",
    23,
    "Certificate errors do not show the details",
    "you cannot see what is actually wrong before deciding whether to proceed",
    "The certificate error page shows the technical detail.",
  ],
  [
    "referer-trim",
    "network.http.referer.XOriginTrimmingPolicy",
    "0",
    "<2",
    "2",
    "privacy",
    54,
    "The full URL is sent as referrer to other sites",
    "the page you came from — path, query and all — is handed to every third party",
    "Only the origin is sent across sites. Same-site referrers are unchanged.",
  ],

  // ----------------------------------------------------------- partitioning
  [
    "partition-network",
    "privacy.partition.network_state",
    "true",
    "false",
    "true",
    "privacy",
    53,
    "Network state is shared across sites",
    "connection pools and caches become a cross-site identifier",
    "Each site gets its own. This is Firefox's own default.",
  ],
  [
    "partition-workers",
    "privacy.partition.serviceWorkers",
    "true",
    "false",
    "true",
    "privacy",
    52,
    "Service workers are shared across sites",
    "a third-party worker can persist across the sites that embed it",
    "Each site gets its own.",
  ],
  [
    "cookie-behavior",
    "network.cookie.cookieBehavior",
    "5",
    "<5",
    "5",
    "privacy",
    69,
    "Third-party cookies are not fully partitioned",
    "a tracker embedded on two sites can join up what you did on both",
    "Total Cookie Protection: each site gets its own cookie jar. Logins keep working.",
  ],
];

export const FIREFOX2_POLICIES: MozPolicy[] = ROWS.map(
  (
    [id, pref, fallback, bad, safe, category, weight, title, detail, because],
  ) => ({
    id: `ff2-${id}`,
    title,
    category,
    severity: weight >= 55 ? "major" as const : "minor" as const,
    weight,
    product: "firefox" as const,
    pref,
    fallback,
    bad,
    safe,
    detail,
    because,
  }),
);
