// Firefox, third pass: what a page may reach on your machine, and what the
// browser keeps about where you have been.
import type { MozPolicy } from "../../type/policy.ts";

/** [id, pref, fallback, bad, safe, cat, weight, title, detail, because] */
type Row = [
  string,
  string,
  string,
  MozPolicy["bad"],
  string,
  MozPolicy["category"],
  number,
  string,
  string,
  string,
];

const ROWS: Row[] = [
  [
    "webgl-debug",
    "webgl.enable-debug-renderer-info",
    "true",
    "true",
    "false",
    "privacy",
    56,
    "Pages can read your exact graphics hardware",
    "the GPU model and driver string are one of the strongest fingerprinting signals a page can get for free",
    "Rendering is unaffected; only the identifying string is withheld.",
  ],
  [
    "media-devices",
    "media.navigator.enumerate.legacy.enabled",
    "true",
    "true",
    "false",
    "privacy",
    55,
    "Pages can enumerate your cameras and microphones without permission",
    "the number and names of your devices identify the machine",
    "A page that asks for the camera still works; it just cannot list them first.",
  ],
  [
    "gamepad",
    "dom.gamepad.enabled",
    "true",
    "true",
    "false",
    "privacy",
    24,
    "Pages can enumerate connected gamepads",
    "another device list available without a prompt",
    "Games that use a gamepad through the browser will need it back.",
  ],
  [
    "vr",
    "dom.vr.enabled",
    "true",
    "true",
    "false",
    "privacy",
    23,
    "Pages can query VR hardware",
    "another hardware signal exposed without a prompt",
    "Nothing else uses it.",
  ],
  [
    "midi",
    "dom.webmidi.enabled",
    "true",
    "true",
    "false",
    "security",
    57,
    "Pages may request MIDI access",
    "system-exclusive MIDI can reprogram attached hardware",
    "A page that needs MIDI will prompt; this only stops the capability being present.",
  ],
  [
    "speech",
    "media.webspeech.recognition.enable",
    "true",
    "true",
    "false",
    "privacy",
    45,
    "Speech recognition is enabled",
    "audio can be sent to a remote recogniser",
    "Nothing on a normal page uses it.",
  ],
  [
    "idle-api",
    "dom.idle-observers-api.enabled",
    "true",
    "true",
    "false",
    "privacy",
    44,
    "Pages can tell when you step away",
    "a site learns your working pattern minute by minute",
    "No ordinary page needs it.",
  ],
  [
    "network-info",
    "dom.netinfo.enabled",
    "true",
    "true",
    "false",
    "privacy",
    43,
    "Pages can read your connection type",
    "another fingerprinting signal, and it reveals when you move between networks",
    "Adaptive video still works from measured throughput.",
  ],
  [
    "dom-storage-quota",
    "dom.storage.next_gen",
    "true",
    "false",
    "true",
    "privacy",
    20,
    "Storage is not partitioned per site",
    "records the current default explicitly",
    "No behaviour change.",
  ],
  [
    "form-autofill-heuristics",
    "extensions.formautofill.heuristics.enabled",
    "true",
    "true",
    "false",
    "privacy",
    42,
    "Firefox guesses which fields hold personal data",
    "the guess is what lets a hidden field be filled",
    "Explicitly marked fields still work.",
  ],
  [
    "search-update",
    "browser.search.update",
    "true",
    "true",
    "false",
    "privacy",
    30,
    "Search engine definitions update themselves",
    "the browser fetches engine metadata on a schedule",
    "Your chosen engine keeps working.",
  ],
  [
    "contentblocking-report",
    "browser.contentblocking.report.lockwise.enabled",
    "true",
    "true",
    "false",
    "privacy",
    19,
    "The protections report includes your saved logins",
    "a count of your accounts on a page the browser renders",
    "The report still shows blocking counts.",
  ],
  [
    "telemetry-server",
    "toolkit.telemetry.server",
    '"https://incoming.telemetry.mozilla.org"',
    "~mozilla",
    '"data:,"',
    "privacy",
    54,
    "A telemetry endpoint is still configured",
    "the destination remains set even when individual pings are off",
    "Points the endpoint at nothing. Nothing about browsing changes.",
  ],
  [
    "experiments",
    "app.normandy.first_run",
    "true",
    "true",
    "false",
    "privacy",
    29,
    "The remote experiment framework runs on first start",
    "the browser contacts Mozilla before you have used it",
    "Nothing about the profile changes.",
  ],
  [
    "healthreport-url",
    "datareporting.healthreport.about.reportUrl",
    '"https://fhr.cdn.mozilla.net/"',
    "~mozilla",
    '"data:text/plain,"',
    "privacy",
    28,
    "The health report page fetches remote content",
    "opening a settings page makes a network request",
    "The page renders empty instead.",
  ],
  [
    "geo-provider",
    "geo.provider.network.url",
    '"https://location.services.mozilla.com/v1/geolocate"',
    "~http",
    '""',
    "privacy",
    53,
    "Location lookups go to a fixed remote service",
    "when a site asks for your location, the request is answered by a third party who then knows it too",
    "Location requests fail instead of being answered remotely. Sites that need location will say so.",
  ],
  [
    "safebrowsing-provider",
    "browser.safebrowsing.provider.google4.updateURL",
    '""',
    "~google",
    '""',
    "privacy",
    41,
    "Safe Browsing list updates go to Google",
    "the update request carries identifying details on a schedule",
    "Removing the URL disables list updates — the protection stops with it, so this is a trade.",
  ],
  [
    "ocsp-stapling",
    "security.ssl.enable_ocsp_stapling",
    "true",
    "false",
    "true",
    "security",
    58,
    "Certificate revocation is not checked via stapling",
    "a revoked certificate is accepted as valid",
    "The server supplies the proof; there is no extra request.",
  ],
  [
    "tls-13-downgrade",
    "security.tls.version.enable-deprecated",
    "false",
    "true",
    "false",
    "security",
    68,
    "Deprecated TLS versions are re-enabled",
    "someone turned old protocol versions back on, which is a downgrade path",
    "Modern sites are unaffected.",
  ],
  [
    "sha1-certs",
    "security.pki.sha1_enforcement_level",
    "1",
    "=0",
    "1",
    "security",
    67,
    "SHA-1 certificates are accepted",
    "SHA-1 collisions are practical, so such a certificate proves nothing",
    "Sites using SHA-1 have been broken for years anyway.",
  ],
  [
    "crlite",
    "security.remote_settings.crlite_filters.enabled",
    "false",
    "false",
    "true",
    "security",
    52,
    "Fast revocation checking is off",
    "revoked certificates are only caught by the slower path, or not at all",
    "It is a downloaded filter; there is no per-visit request.",
  ],
  [
    "cert-error-override",
    "security.certerrors.permanentOverride",
    "true",
    "true",
    "false",
    "security",
    66,
    "Certificate exceptions are remembered forever",
    "a warning you clicked through once never appears again, on any future connection to that site",
    "Exceptions last for the session instead.",
  ],
  [
    "proxy-dns",
    "network.proxy.socks_remote_dns",
    "false",
    "false",
    "true",
    "privacy",
    51,
    "DNS is resolved locally when using a SOCKS proxy",
    "the proxy carries your traffic while your own resolver still sees every name — the classic proxy leak",
    "Names are resolved through the proxy. No effect when no proxy is set.",
  ],
  [
    "disk-cache-ssl",
    "browser.cache.disk_cache_ssl",
    "true",
    "true",
    "false",
    "privacy",
    40,
    "Content from encrypted sites is cached to disk",
    "pages from your bank and your mail sit in the cache in clear text",
    "They are cached in memory instead, which costs a little re-fetching.",
  ],
  [
    "sanitize-onshutdown-cache",
    "privacy.clearOnShutdown.cache",
    "false",
    "false",
    "true",
    "privacy",
    27,
    "The cache is kept between sessions",
    "the record of what you loaded survives closing the browser",
    "Only the cache is cleared; history, logins and cookies are untouched.",
  ],
  [
    "offline-apps",
    "offline-apps.allow_by_default",
    "true",
    "true",
    "false",
    "privacy",
    26,
    "Sites may store offline data without asking",
    "a page can write to your disk with no prompt",
    "Sites that need it will ask.",
  ],
  [
    "indexeddb-shutdown",
    "dom.indexedDB.logging.enabled",
    "false",
    "true",
    "false",
    "performance",
    8,
    "Database logging is enabled",
    "extra work and log volume for something only a developer reads",
    "No behaviour change.",
  ],
  [
    "gfx-webrender-software",
    "gfx.webrender.software",
    "false",
    "true",
    "false",
    "performance",
    47,
    "Rendering is falling back to software",
    "every page is composited on the CPU, which shows as scrolling that stutters and a hot fan",
    "Investigate why hardware acceleration is unavailable rather than leaving the fallback in place.",
  ],
  [
    "process-count",
    "dom.ipc.processCount",
    "8",
    "<4",
    "8",
    "performance",
    25,
    "Firefox is limited to very few content processes",
    "one slow tab blocks the others, and a crash takes more with it",
    "Eight is the shipped default and is right for most machines.",
  ],
  [
    "accessibility-force",
    "accessibility.force_disabled",
    "0",
    ">0",
    "0",
    "settings",
    18,
    "Accessibility support is force-disabled",
    "assistive technology cannot read any page",
    "Restores the default. Set this only as a deliberate performance measure.",
  ],
];

export const FIREFOX3_POLICIES: MozPolicy[] = ROWS.map(
  (
    [id, pref, fallback, bad, safe, category, weight, title, detail, because],
  ) => ({
    id: `ff3-${id}`,
    title,
    category,
    severity: weight >= 50 ? "major" as const : "minor" as const,
    weight,
    product: "firefox" as const,
    pref,
    fallback,
    bad,
    safe,
    detail,
    because,
  }),
);
