// Firefox preferences. The browser is the largest privacy and security surface
// on a workstation, and almost all of it is one boolean away from being better.
//
// What is deliberately NOT here: `privacy.resistFingerprinting`, `webgl.disabled`
// and `media.peerconnection.enabled`. Each is a real hardening win and each
// visibly breaks ordinary browsing — video calls, maps, timezone-correct pages.
// A fix that makes the machine worse to use is not a fix.
import type { MozPolicy } from "../../type/policy.ts";

/** [id, pref, fallback, bad, safe, weight, title, detail, because] */
type Row = [
  string,
  string,
  string,
  MozPolicy["bad"],
  string,
  number,
  string,
  string,
  string,
];

const off = (
  id: string,
  pref: string,
  weight: number,
  title: string,
  detail: string,
  because: string,
  fallback = "true",
): Row => [id, pref, fallback, "true", "false", weight, title, detail, because];

const on = (
  id: string,
  pref: string,
  weight: number,
  title: string,
  detail: string,
  because: string,
  fallback = "false",
): Row => [id, pref, fallback, "false", "true", weight, title, detail, because];

const TELEMETRY: Row[] = [
  off(
    "health-report",
    "datareporting.healthreport.uploadEnabled",
    62,
    "Firefox uploads a health report",
    "usage and performance data about this machine is sent to Mozilla on a schedule",
    "Browsing is unaffected. Only the upload stops.",
  ),
  off(
    "data-submission",
    "datareporting.policy.dataSubmissionEnabled",
    61,
    "Firefox data submission is enabled",
    "the master switch that permits every other data upload is on",
    "This is the single switch that turns the rest off with it.",
  ),
  off(
    "telemetry",
    "toolkit.telemetry.enabled",
    60,
    "Firefox telemetry is enabled",
    "measurements of what you do in the browser are collected",
    "Nothing about page loading or rendering changes.",
    "false",
  ),
  off(
    "telemetry-unified",
    "toolkit.telemetry.unified",
    59,
    "Unified telemetry collection is on",
    "the collection pipeline runs even when individual pings are off",
    "Turning it off stops the pipeline rather than its outputs.",
  ),
  off(
    "telemetry-archive",
    "toolkit.telemetry.archive.enabled",
    58,
    "Telemetry pings are archived on disk",
    "a growing store of what you did, kept locally as well as sent",
    "Existing archives are left alone; new ones stop.",
  ),
  off(
    "telemetry-newprofile",
    "toolkit.telemetry.newProfilePing.enabled",
    57,
    "Firefox pings on a new profile",
    "creating a profile is itself reported",
    "No effect on the profile.",
  ),
  off(
    "telemetry-shutdown",
    "toolkit.telemetry.shutdownPingSender.enabled",
    56,
    "Firefox sends a ping when it closes",
    "a report is sent every time you quit the browser",
    "Quitting still works exactly the same.",
  ),
  off(
    "telemetry-update",
    "toolkit.telemetry.updatePing.enabled",
    55,
    "Firefox pings after an update",
    "each update is reported back with your profile identifier",
    "Updates still install.",
  ),
  off(
    "telemetry-bhr",
    "toolkit.telemetry.bhrPing.enabled",
    54,
    "Background hang reports are sent",
    "stack traces from your browser are uploaded when it stutters",
    "Hangs still resolve the same way.",
  ),
  off(
    "telemetry-firstshutdown",
    "toolkit.telemetry.firstShutdownPing.enabled",
    53,
    "A ping is sent on first shutdown",
    "the first time you close a new profile is reported",
    "No effect on the profile.",
  ),
  on(
    "telemetry-coverage-out",
    "toolkit.telemetry.coverage.opt-out",
    52,
    "Firefox is not opted out of coverage telemetry",
    "a separate coverage collection is active",
    "This is the documented opt-out flag.",
  ),
  on(
    "coverage-out",
    "toolkit.coverage.opt-out",
    51,
    "Firefox is not opted out of coverage collection",
    "the second half of the coverage opt-out is unset",
    "This is the documented opt-out flag.",
  ),
  off(
    "ping-centre",
    "browser.ping-centre.telemetry",
    50,
    "The new-tab page reports what you click",
    "activity on the home page is sent to Mozilla",
    "The page still works.",
  ),
  off(
    "shield-studies",
    "app.shield.optoutstudies.enabled",
    49,
    "Firefox may enrol you in studies",
    "Mozilla can enable experimental changes in your browser without asking",
    "Your browser stops changing behind your back.",
  ),
  off(
    "normandy",
    "app.normandy.enabled",
    48,
    "Firefox accepts remote configuration",
    "Normandy can push preference changes and add-ons into this profile",
    "Your settings stop being remotely adjustable.",
  ),
  off(
    "crash-report-tabs",
    "browser.tabs.crashReporting.sendReport",
    47,
    "Tab crash reports are sent",
    "crash data — which can contain page contents — is uploaded",
    "Crashed tabs still recover the same way.",
  ),
  off(
    "crash-autosubmit",
    "browser.crashReports.unsubmittedCheck.autoSubmit2",
    46,
    "Pending crash reports are submitted automatically",
    "reports you never saw are sent without asking",
    "You can still submit one deliberately.",
    "false",
  ),
  off(
    "default-agent",
    "default-browser-agent.enabled",
    45,
    "The default-browser agent runs",
    "a background task reports your default-browser choice",
    "Setting a default browser still works.",
    "false",
  ),
  off(
    "discovery",
    "browser.discovery.enabled",
    44,
    "Firefox sends data for add-on recommendations",
    "your browsing informs which add-ons you are shown",
    "You can still search for add-ons yourself.",
  ),
  off(
    "newtab-telemetry",
    "browser.newtabpage.activity-stream.telemetry",
    43,
    "The new-tab page sends telemetry",
    "what you open from the home page is reported",
    "The page still works.",
  ),
  off(
    "newtab-feed-telemetry",
    "browser.newtabpage.activity-stream.feeds.telemetry",
    42,
    "The new-tab feed sends telemetry",
    "the second half of the home-page reporting",
    "The page still works.",
  ),
];

const CONTENT: Row[] = [
  off(
    "sponsored",
    "browser.newtabpage.activity-stream.showSponsored",
    41,
    "Sponsored stories appear on the new-tab page",
    "paid content is mixed into your home page, and it is measured",
    "The home page keeps your own top sites.",
  ),
  off(
    "sponsored-tiles",
    "browser.newtabpage.activity-stream.showSponsoredTopSites",
    40,
    "Sponsored tiles appear among your top sites",
    "paid tiles sit among the sites you actually visit",
    "Your own top sites remain.",
  ),
  off(
    "pocket-feed",
    "browser.newtabpage.activity-stream.feeds.section.topstories",
    39,
    "Pocket recommendations appear on the new-tab page",
    "an external feed loads on every new tab",
    "The home page loads faster without it.",
  ),
  off(
    "pocket",
    "extensions.pocket.enabled",
    38,
    "Pocket integration is enabled",
    "a third-party service is wired into the browser toolbar and menus",
    "Nothing you have saved is deleted; the integration is switched off.",
  ),
  off(
    "formfill",
    "browser.formfill.enable",
    37,
    "Firefox remembers what you type into forms",
    "search boxes and form fields replay your earlier entries to anyone at the machine",
    "Existing history is kept; new entries stop being recorded.",
  ),
  off(
    "autofill-addresses",
    "extensions.formautofill.addresses.enabled",
    36,
    "Address autofill is enabled",
    "your postal address can be filled into a hidden field by a hostile page",
    "You can still paste an address yourself.",
  ),
  off(
    "autofill-cards",
    "extensions.formautofill.creditCards.enabled",
    35,
    "Payment-card autofill is enabled",
    "card details can be filled into fields you cannot see",
    "Cards can still be entered by hand.",
  ),
  off(
    "signon-autofill",
    "signon.autofillForms",
    34,
    "Saved passwords are filled in automatically",
    "a login form on a page you did not expect gets your password without a click",
    "Saved passwords still fill when you choose them from the field.",
  ),
  off(
    "recent-docs",
    "browser.download.manager.addToRecentDocs",
    33,
    "Downloads are added to your recent documents",
    "every download appears in a system-wide list other applications read",
    "The file is still downloaded to the same place.",
  ),
];

const NETWORK: Row[] = [
  on(
    "punycode",
    "network.IDN_show_punycode",
    78,
    "Lookalike domains are displayed as real text",
    "a domain using Cyrillic characters renders identically to the real one in the address bar",
    "Internationalised domains show as punycode, which is the only way to see the difference.",
  ),
  on(
    "dns-prefetch",
    "network.dns.disablePrefetch",
    32,
    "Firefox resolves links you have not clicked",
    "your DNS server learns about pages you only looked at",
    "Clicking a link is imperceptibly slower.",
    "false",
  ),
  off(
    "prefetch-next",
    "network.prefetch-next",
    31,
    "Firefox pre-loads pages you have not visited",
    "sites can make your browser fetch other pages in the background",
    "Fewer requests, less bandwidth.",
  ),
  off(
    "predictor",
    "network.predictor.enabled",
    30,
    "The network predictor is on",
    "Firefox keeps a model of your browsing to guess ahead",
    "The model stops being built and used.",
  ),
  off(
    "send-pings",
    "browser.send_pings",
    29,
    "Firefox honours link ping tracking",
    "clicking a link can silently notify a third party",
    "The link still works; the notification stops.",
    "false",
  ),
  off(
    "speculative-urlbar",
    "browser.urlbar.speculativeConnect.enabled",
    28,
    "Firefox connects to sites as you type",
    "a server hears from you for a URL you never finished typing",
    "Loading is imperceptibly slower.",
  ),
  off(
    "search-suggest",
    "browser.search.suggest.enabled",
    27,
    "Every keystroke in the address bar goes to your search engine",
    "a search engine receives what you type before you press Enter, including things you decide not to search for",
    "Suggestions stop; searching itself is unchanged.",
  ),
  off(
    "urlbar-trim",
    "browser.urlbar.trimURLs",
    26,
    "The address bar hides part of the URL",
    "a hidden scheme makes a phishing URL harder to read",
    "The full address is shown.",
  ),
  off(
    "fixup-alternate",
    "browser.fixup.alternate.enabled",
    25,
    "A mistyped host is retried as a www domain",
    "a typo becomes a request to a domain you did not intend to visit",
    "A typo becomes an error instead of a lookup.",
    "false",
  ),
];

const SECURITY: Row[] = [
  on(
    "https-only",
    "dom.security.https_only_mode",
    88,
    "HTTPS-only mode is off",
    "a page can be loaded over plain HTTP without you noticing, and anything on the path can read or change it",
    "Firefox tries HTTPS first and asks before falling back. A site with no HTTPS shows a prompt rather than failing.",
  ),
  on(
    "https-only-pbm",
    "dom.security.https_only_mode_pbm",
    87,
    "HTTPS-only mode is off in private windows",
    "the same downgrade, in the window you opened for privacy",
    "Same prompt-before-fallback behaviour.",
  ),
  on(
    "mixed-display",
    "security.mixed_content.block_display_content",
    86,
    "Insecure images and media load on secure pages",
    "an attacker on the path can replace them, and they leak the page you are on",
    "Secure pages load only secure content.",
  ),
  off(
    "tls-0rtt",
    "security.tls.enable_0rtt_data",
    85,
    "TLS early data is enabled",
    "0-RTT data can be replayed by anyone who captures it",
    "Connections take one extra round-trip on resumption.",
  ),
  off(
    "pdf-scripting",
    "pdfjs.enableScripting",
    84,
    "JavaScript inside PDFs is allowed to run",
    "opening a PDF runs code the document brought with it",
    "PDFs still render; embedded scripts stop.",
    "true",
  ),
  on(
    "blocklist",
    "extensions.blocklist.enabled",
    83,
    "The add-on blocklist is disabled",
    "extensions known to be malicious are no longer blocked",
    "Restores Mozilla's blocklist. Your own add-ons are unaffected.",
    "true",
  ),
  on(
    "app-update",
    "app.update.auto",
    82,
    "Firefox does not update itself",
    "the browser stays on a version with known, published vulnerabilities",
    "Updates install in the background and apply at the next restart.",
    "true",
  ),
  on(
    "tracking-protection",
    "privacy.trackingprotection.enabled",
    81,
    "Tracking protection is off",
    "known trackers load on every page you visit",
    "Firefox's own blocklist is applied. Sites that break can be excepted individually.",
  ),
  on(
    "tp-fingerprinting",
    "privacy.trackingprotection.fingerprinting.enabled",
    80,
    "Fingerprinting scripts are not blocked",
    "scripts that identify this exact machine load freely",
    "Known fingerprinting scripts are blocked.",
    "true",
  ),
  on(
    "tp-cryptomining",
    "privacy.trackingprotection.cryptomining.enabled",
    79,
    "Cryptomining scripts are not blocked",
    "pages can spend your CPU and battery mining",
    "Known miners are blocked.",
    "true",
  ),
  on(
    "tp-social",
    "privacy.trackingprotection.socialtracking.enabled",
    77,
    "Social trackers are not blocked",
    "embedded buttons report your visit whether or not you click",
    "Known social trackers are blocked.",
    "true",
  ),
  on(
    "gpc",
    "privacy.globalprivacycontrol.enabled",
    76,
    "Global Privacy Control is not sent",
    "sites are not told you object to your data being sold",
    "A header is added. It is legally binding in several jurisdictions.",
  ),
  [
    "cert-pinning",
    "security.cert_pinning.enforcement_level",
    "1",
    "<2",
    "2",
    75,
    "Certificate pinning is not fully enforced",
    "a certificate authority installed on this machine can impersonate pinned sites",
    "Level 2 enforces pinning even against a root you installed yourself — which is what corporate TLS inspection, antivirus web shields and debugging proxies such as mitmproxy rely on, so pinned sites stop loading behind any of them.",
  ],
];

const ROWS: Row[] = [...TELEMETRY, ...CONTENT, ...NETWORK, ...SECURITY];

const category = (id: string): MozPolicy["category"] =>
  SECURITY.some((r) => r[0] === id)
    ? "security"
    : NETWORK.some((r) => r[0] === id)
    ? "privacy"
    : "privacy";

export const FIREFOX_POLICIES: MozPolicy[] = ROWS.map(
  ([id, pref, fallback, bad, safe, weight, title, detail, because]) => ({
    id: `ff-${id}`,
    title,
    category: category(id),
    severity: weight >= 75 ? "major" as const : "minor" as const,
    weight,
    product: "firefox" as const,
    pref,
    fallback,
    bad,
    safe,
    detail,
    because,
  }),
);
