// `git config --global` policy. Auto-fixable and tool-mediated: the fix runs
// `git config`, so nothing here ever edits ~/.gitconfig by hand — no parser to
// get wrong, no file to corrupt, and `--unset` is an exact undo.
import type { GitPolicy } from "../../type/policy.ts";

const CORE: GitPolicy[] = [
  {
    id: "git-ssl-verify",
    title: "Git has TLS certificate verification switched off",
    category: "security",
    severity: "critical",
    weight: 96,
    key: "http.sslVerify",
    safe: "true",
    missingIsBad: false,
    detail: "every clone and fetch over HTTPS accepts any certificate",
    because: "Restores certificate checking. If one specific host needs an " +
      "exception, set it per-URL instead of globally.",
  },
  {
    id: "git-fsck-transfer",
    title: "Git does not validate objects it transfers",
    category: "security",
    severity: "major",
    weight: 71,
    key: "transfer.fsckObjects",
    safe: "true",
    missingIsBad: true,
    detail: "malformed or malicious objects are accepted without checking",
    because:
      "Adds integrity checking to fetch and push. A repository that fails " +
      "the check was already broken.",
  },
  {
    id: "git-fsck-fetch",
    title: "Git does not validate objects it fetches",
    category: "security",
    severity: "major",
    weight: 70,
    key: "fetch.fsckObjects",
    safe: "true",
    missingIsBad: true,
    detail: "objects arriving from a remote are trusted as-is",
    because: "Adds integrity checking on fetch only. Undo removes the key.",
  },
  {
    id: "git-fsck-receive",
    title: "Git does not validate objects it receives",
    category: "security",
    severity: "minor",
    weight: 54,
    key: "receive.fsckObjects",
    safe: "true",
    missingIsBad: true,
    detail: "objects pushed into a local repository are trusted as-is",
    because: "Adds integrity checking on receive. Undo removes the key.",
  },
  {
    id: "git-protocol-file",
    title: "Git allows file:// submodules from any repository",
    category: "security",
    severity: "major",
    weight: 74,
    key: "protocol.file.allow",
    safe: "user",
    missingIsBad: true,
    detail:
      "a cloned repository can pull submodules from local paths (CVE-2022-39253)",
    because:
      "'user' allows file:// when you ask for it directly and blocks it " +
      "during clone. This is git's own recommended value.",
  },
  {
    id: "git-symlinks-core",
    title: "Git creates symlinks from repository contents unchecked",
    category: "security",
    severity: "minor",
    weight: 52,
    key: "core.symlinks",
    safe: "true",
    missingIsBad: false,
    detail: "core.symlinks is switched off, which changes checkout behaviour",
    because: "Restores git's default. Undo puts your value back.",
  },
  {
    id: "git-default-branch",
    title: "Git has no default branch name configured",
    category: "settings",
    severity: "minor",
    weight: 12,
    key: "init.defaultBranch",
    safe: "main",
    missingIsBad: true,
    detail: "`git init` prints a hint about the default branch every time",
    because:
      "Sets the name for repositories you create from now on. Existing " +
      "repositories are untouched.",
  },
  {
    id: "git-rerere",
    title: "Git does not remember how you resolved a conflict",
    category: "settings",
    severity: "minor",
    weight: 3,
    key: "rerere.enabled",
    safe: "true",
    missingIsBad: true,
    detail: "the same merge conflict has to be resolved by hand every time",
    because:
      "Git records your resolutions and replays them. It never resolves " +
      "anything it has not seen you resolve first.",
  },
  {
    id: "git-fetch-prune",
    title: "Deleted remote branches accumulate locally forever",
    category: "settings",
    severity: "minor",
    weight: 2,
    key: "fetch.prune",
    safe: "true",
    missingIsBad: true,
    detail: "remote-tracking refs are kept after the branch is gone upstream",
    because:
      "Removes remote-tracking refs whose branch no longer exists. Your own " +
      "local branches and commits are never touched.",
  },
];

/** Reliability, performance and the two dangerous settings people copy off the
 *  internet without reading. */
type Row = [
  id: string,
  key: string,
  safe: string,
  missingIsBad: boolean,
  cat: GitPolicy["category"],
  sev: GitPolicy["severity"],
  weight: number,
  title: string,
  detail: string,
  because: string,
];

const MORE: Row[] = [
  [
    "fsync",
    "core.fsync",
    "committed",
    true,
    "settings",
    "major",
    65,
    "Git does not flush objects to disk when it commits",
    "a power loss or kernel panic can leave a repository with a commit whose objects were never written",
    "Git fsyncs what it commits, which is what every other database does. The cost is milliseconds per commit.",
  ],
  [
    "credentials-in-url",
    "transfer.credentialsInUrl",
    "die",
    true,
    "security",
    "major",
    80,
    "Git accepts passwords embedded in remote URLs",
    "a URL with credentials ends up in .git/config, in your shell history, and in every log that records the command",
    "Git refuses such a URL and tells you to use a credential helper. Existing remotes are not rewritten.",
  ],
  [
    "untracked-cache",
    "core.untrackedCache",
    "true",
    true,
    "performance",
    "minor",
    22,
    "Git rescans for untracked files on every status",
    "`git status` walks the whole tree each time, which is seconds in a large repository",
    "Git caches directory state and validates it against mtime. It is a cache; the answer is the same.",
  ],
  [
    "index-threads",
    "index.threads",
    "true",
    true,
    "performance",
    "minor",
    21,
    "Git loads the index single-threaded",
    "index reads are serialised on repositories with many files",
    "Git uses one thread per core to read the index.",
  ],
  [
    "checkout-workers",
    "checkout.workers",
    "0",
    true,
    "performance",
    "minor",
    20,
    "Git checks out files single-threaded",
    "clone and checkout are slower than the disk on any multi-core machine",
    "0 means one worker per core. The files written are identical.",
  ],
  [
    "commit-graph",
    "fetch.writeCommitGraph",
    "true",
    true,
    "performance",
    "minor",
    19,
    "Git does not maintain a commit graph on fetch",
    "history traversal — log, blame, merge-base — re-walks commits it could have indexed",
    "The graph is written after fetch and is a derived index; deleting it costs nothing.",
  ],
  [
    "diff-algorithm",
    "diff.algorithm",
    "histogram",
    true,
    "settings",
    "minor",
    18,
    "Git uses its oldest diff algorithm",
    "the default Myers diff produces noisier hunks on real code than the alternatives",
    "Histogram diffs are the same content, grouped better. Nothing about your commits changes.",
  ],
  [
    "conflict-style",
    "merge.conflictStyle",
    "zdiff3",
    true,
    "settings",
    "minor",
    24,
    "Merge conflicts do not show the common ancestor",
    "you resolve conflicts seeing only two sides, which is how wrong resolutions happen",
    "Conflict markers gain the original text. It affects only how conflicts are displayed.",
  ],
  [
    "rebase-autostash",
    "rebase.autoStash",
    "true",
    true,
    "settings",
    "minor",
    23,
    "Rebasing refuses to start with uncommitted work",
    "you stash by hand, rebase, then forget to pop",
    "Git stashes and restores around the rebase. Failures leave the stash intact.",
  ],
  [
    "rerere-autoupdate",
    "rerere.autoUpdate",
    "true",
    true,
    "settings",
    "minor",
    4,
    "Replayed conflict resolutions are not staged",
    "rerere resolves the conflict and then leaves you to stage it anyway",
    "The replayed resolution is staged. It only ever replays a resolution you made yourself.",
  ],
  [
    "push-autosetup",
    "push.autoSetupRemote",
    "true",
    true,
    "settings",
    "minor",
    17,
    "Pushing a new branch fails until you name the upstream",
    "the first push of every branch is an error and a copy-pasted command",
    "Git sets the upstream to the same branch name on the default remote.",
  ],
  [
    "am-threeway",
    "am.threeWay",
    "true",
    true,
    "settings",
    "minor",
    5,
    "Applying a patch gives up instead of merging",
    "`git am` fails on patches it has enough information to apply",
    "Git falls back to a three-way merge, which is what `git apply -3` does.",
  ],
  [
    "gpg-min-trust",
    "gpg.minTrustLevel",
    "fully",
    true,
    "security",
    "minor",
    16,
    "Signature verification accepts any trust level",
    "a signature from a key you never verified reports as good",
    "Only fully trusted keys verify as good. Verification of anything else says so instead of staying quiet.",
  ],
  [
    "tag-forcesign",
    "tag.gpgSign",
    "false",
    true,
    "settings",
    "minor",
    1,
    "Tag signing has no explicit setting",
    "whether a release tag is signed depends on which flag you remembered",
    "Records the current default explicitly, so the behaviour stops depending on habit.",
  ],
  [
    "clean-require-force",
    "clean.requireForce",
    "true",
    true,
    "settings",
    "major",
    67,
    "`git clean` deletes without requiring -f",
    "one keystroke removes every untracked file in the tree, permanently",
    "`git clean` refuses without an explicit -f. Nothing about tracked files changes.",
  ],
  [
    "merge-verify",
    "merge.verifySignatures",
    "false",
    true,
    "security",
    "minor",
    15,
    "Merges do not check commit signatures",
    "records the current default explicitly rather than leaving it implicit",
    "No change in behaviour; the setting stops being ambiguous.",
  ],
  [
    "receive-deny-current",
    "receive.denyCurrentBranch",
    "refuse",
    true,
    "settings",
    "minor",
    14,
    "Pushing to a checked-out branch is not refused",
    "a push into a working repository can leave the index and the tree disagreeing",
    "The push is refused with an explanation instead.",
  ],
  [
    "gc-prune-expire",
    "gc.pruneExpire",
    "2.weeks.ago",
    true,
    "settings",
    "minor",
    13,
    "Unreachable objects are pruned immediately",
    "a mistaken reset has no grace period in which the objects still exist",
    "Unreachable objects survive two weeks, which is long enough to recover from a bad command.",
  ],
  [
    "core-fsmonitor",
    "core.fsmonitor",
    "true",
    true,
    "performance",
    "minor",
    12,
    "Git rescans the working tree on every command",
    "`git status` walks every file in a large repository, every time",
    "Git watches the filesystem instead. It is a cache; results are identical.",
  ],
  [
    "pack-window-memory",
    "pack.windowMemory",
    "256m",
    true,
    "resource",
    "minor",
    11,
    "Packing has no memory ceiling",
    "a `git gc` on a large repository can take the machine into swap",
    "Packing stays within 256 MB per thread. The pack it produces is equivalent.",
  ],
  [
    "log-showsig",
    "log.showSignature",
    "false",
    true,
    "settings",
    "minor",
    1,
    "Signature status is not shown in log output",
    "records the current default explicitly",
    "No change in behaviour.",
  ],
  [
    "http-version",
    "http.version",
    "HTTP/2",
    true,
    "performance",
    "minor",
    9,
    "Git negotiates its HTTP version each time",
    "fetches fall back to HTTP/1.1 against servers that support better",
    "HTTP/2 is requested. Servers that do not speak it negotiate down as before.",
  ],
];

const DANGEROUS: [
  id: string,
  key: string,
  sev: GitPolicy["severity"],
  weight: number,
  title: string,
  detail: string,
  why: string,
  /** Only report when the value contains this; omitted = any value. */
  onlyWhen?: string,
][] = [
  [
    "credential-store",
    "credential.helper",
    "major",
    85,
    "Git stores your credentials in clear text",
    "the `store` helper writes tokens to ~/.git-credentials unencrypted",
    "No automatic fix: changing your credential helper logs you out of every host you have authenticated to, and this app will not do that mid-session. Switch to `libsecret` (`git config --global credential.helper libsecret`) and re-authenticate when it suits you.",
    "store",
  ],
  [
    "hooks-path",
    "core.hooksPath",
    "major",
    82,
    "Git hooks are loaded from one configured directory",
    "every repository you touch runs hooks from that directory, whoever wrote them, instead of its own",
    "No automatic fix: this is usually deliberate (a shared hook manager). Check what is in that directory, and unset it with `git config --global --unset core.hooksPath` if you do not recognise it.",
  ],
  [
    "safe-directory-all",
    "safe.directory",
    "major",
    83,
    "Git trusts repositories owned by any user",
    "`safe.directory = *` disables the ownership check that stops a repository planted by another account from running its config",
    "No automatic fix: removing it can break the setup it was added for — usually a container or a shared mount. List the specific directories instead of `*`.",
    "*",
  ],
];

export const GIT_POLICIES: GitPolicy[] = [
  ...CORE,
  ...MORE.map((
    [
      id,
      key,
      safe,
      missingIsBad,
      category,
      severity,
      weight,
      title,
      detail,
      because,
    ],
  ): GitPolicy => ({
    id: `git-${id}`,
    title,
    category,
    severity,
    weight,
    key,
    safe,
    missingIsBad,
    detail,
    because,
  })),
  ...DANGEROUS.map((
    [id, key, severity, weight, title, detail, why, onlyWhen],
  ): GitPolicy => ({
    id: `git-${id}`,
    title,
    category: "security",
    severity,
    weight,
    key,
    safe: "",
    missingIsBad: false,
    detail,
    because: "",
    advisory: why,
    onlyWhen,
  })),
];
