// GnuPG defaults. GnuPG's own defaults are conservative for compatibility with
// keys from twenty years ago; these rows move a modern desktop to modern
// algorithms and stop it announcing itself in every armoured block.
import type { ConfPolicy } from "../../type/policy.ts";

type Row = [
  id: string,
  key: string,
  safe: string,
  severity: ConfPolicy["severity"],
  weight: number,
  title: string,
  detail: string,
  because: string,
];

const ROWS: Row[] = [
  [
    "keyid-format",
    "keyid-format",
    "0xlong",
    "major",
    77,
    "GnuPG prints short key ids",
    "short key ids are cheap to collide, so a forged key can display the id you were told to expect",
    "Full-length ids are printed instead. Nothing about your keys changes.",
  ],
  [
    "with-fingerprint",
    "with-fingerprint",
    "",
    "major",
    76,
    "Key listings omit fingerprints",
    "the only identifier worth verifying is not shown when you look a key up",
    "Listings gain a fingerprint line. It is display only.",
  ],
  [
    "cert-digest",
    "cert-digest-algo",
    "SHA512",
    "major",
    75,
    "Signatures on keys are certified with a weaker digest",
    "SHA-1 certifications are the weak point in a web of trust",
    "New certifications use SHA-512. Existing signatures are untouched.",
  ],
  [
    "personal-digest",
    "personal-digest-preferences",
    "SHA512 SHA384 SHA256",
    "major",
    74,
    "GnuPG may pick a weak digest for your signatures",
    "without a preference, recipients' capabilities decide, and old capabilities include SHA-1",
    "Your signatures use SHA-2 family digests. Verification of old signatures still works.",
  ],
  [
    "personal-cipher",
    "personal-cipher-preferences",
    "AES256 AES192 AES",
    "major",
    73,
    "GnuPG may pick a weak cipher for your encryption",
    "the negotiated default can fall back to CAST5 or 3DES",
    "Your encryption uses AES. Decryption of anything older is unaffected.",
  ],
  [
    "personal-compress",
    "personal-compress-preferences",
    "ZLIB BZIP2 ZIP Uncompressed",
    "minor",
    36,
    "Compression preference is unset",
    "GnuPG's fallback ordering is older than it needs to be",
    "Sets a modern ordering. Decompression of anything is unaffected.",
  ],
  [
    "default-prefs",
    "default-preference-list",
    "SHA512 SHA384 SHA256 AES256 AES192 AES ZLIB BZIP2 ZIP Uncompressed",
    "minor",
    50,
    "Keys you generate advertise weak algorithm support",
    "the preferences baked into a new key tell everyone what to use with it, for its whole life",
    "Only keys created from now on carry the new list. Existing keys are untouched.",
  ],
  [
    "s2k-digest",
    "s2k-digest-algo",
    "SHA512",
    "major",
    71,
    "Your passphrase is hashed with a weaker digest",
    "the key that protects your private key is derived with GnuPG's older default",
    "Applies the next time a passphrase is set. Your existing key still opens with its current passphrase.",
  ],
  [
    "s2k-cipher",
    "s2k-cipher-algo",
    "AES256",
    "major",
    70,
    "Your private key is protected with a weaker cipher",
    "the on-disk protection of your secret key is not AES",
    "Applies the next time a passphrase is set. Nothing existing is re-encrypted.",
  ],
  [
    "s2k-count",
    "s2k-count",
    "65011712",
    "minor",
    49,
    "Passphrase hashing is cheap to brute-force",
    "a low iteration count makes an offline attack on your exported key far faster",
    "Raises the work factor for passphrases set from now on. Unlocking is imperceptibly slower.",
  ],
  [
    "no-emit-version",
    "no-emit-version",
    "",
    "minor",
    44,
    "GnuPG stamps its version into everything you sign",
    "every armoured block tells the world which GnuPG build you run",
    "The Version: header is omitted. Signatures verify exactly the same.",
  ],
  [
    "no-comments",
    "no-comments",
    "",
    "minor",
    43,
    "GnuPG writes comment headers into armoured output",
    "another line of metadata attached to everything you send",
    "The Comment: header is omitted.",
  ],
  [
    "require-cross-cert",
    "require-cross-certification",
    "",
    "major",
    69,
    "Signing subkeys are accepted without a back signature",
    "a subkey can be attached to someone else's key without their consent",
    "GnuPG's own recommendation, and the default in recent versions.",
  ],
  [
    "no-symkey-cache",
    "no-symkey-cache",
    "",
    "minor",
    47,
    "Symmetric passphrases are cached by the agent",
    "a passphrase for a symmetrically encrypted file stays in the agent afterwards",
    "You are asked each time instead.",
  ],
  [
    "keyserver-no-url",
    "keyserver-options",
    "no-honor-keyserver-url",
    "major",
    68,
    "GnuPG follows the keyserver URL embedded in a key",
    "a key can point your refresh at a server of its author's choosing, which tells them when you use it",
    "Refreshes go to your configured keyserver only.",
  ],
  [
    "list-uid-validity",
    "list-options",
    "show-uid-validity",
    "minor",
    42,
    "Key listings do not show identity validity",
    "you cannot see at a glance whether a user id is actually trusted",
    "Adds a validity column. Display only.",
  ],
  [
    "verify-uid-validity",
    "verify-options",
    "show-uid-validity",
    "minor",
    41,
    "Verification output does not show identity validity",
    "a good signature from an untrusted identity reads the same as one you trust",
    "Adds validity to verification output. Display only.",
  ],
];

export const GNUPG_POLICIES: ConfPolicy[] = ROWS.map(
  ([id, key, safe, severity, weight, title, detail, because]): ConfPolicy => ({
    id: `gpg-${id}`,
    title,
    category: "security",
    severity,
    weight,
    file: ".gnupg/gpg.conf",
    format: "space",
    key,
    safe,
    missingIsBad: true,
    needs: "gpg",
    detail,
    because,
  }),
);
