// Screen lock and idle policy. Every row here is one gsettings write away from
// being right, and every one of them is undoable.
import type { SettingPolicy } from "../../type/policy.ts";
import { POWER, SCREENSAVER, SESSION } from "./schemas.ts";

export const LOCK_POLICIES: SettingPolicy[] = [
  {
    id: "screen-lock",
    title: "The screen does not lock when it blanks",
    category: "security",
    severity: "major",
    weight: 85,
    schemas: SCREENSAVER,
    key: "lock-enabled",
    bad: "false",
    safe: "true",
    detail: "anyone who walks up to the machine resumes your session",
    because: "The screen already blanks; locking it costs you one password.",
  },
  {
    id: "screen-idle",
    title: "The screen never blanks on idle",
    category: "security",
    severity: "minor",
    weight: 55,
    schemas: SESSION,
    key: "idle-delay",
    bad: "=0",
    safe: "300",
    detail: "idle-delay is 0 — the session stays awake and on display",
    because: "Five minutes of idle is long enough not to interrupt you.",
    advisory:
      "No automatic fix. `0` means the session is never considered idle, which is deliberate on a machine that must not blank or lock. It does mean nothing keyed to idle will ever fire \u2014 including the screen lock. Change it in Screensaver settings if that is not what you intended.",
  },
  {
    id: "screen-idle-long",
    title: "The screen stays on for a very long time before blanking",
    category: "security",
    severity: "minor",
    weight: 34,
    schemas: SESSION,
    key: "idle-delay",
    bad: ">1800",
    safe: "900",
    detail: "the desk can be left unattended for half an hour, unlocked",
    because: "Fifteen minutes is a common ceiling and still generous.",
    advisory:
      "No automatic fix. This is a timeout you chose. Change it in Screensaver settings if it is longer than you meant.",
  },
  {
    id: "lock-activation",
    title: "Idle no longer starts the screensaver",
    category: "security",
    severity: "major",
    weight: 80,
    schemas: SCREENSAVER,
    key: "idle-activation-enabled",
    bad: "false",
    safe: "true",
    detail: "the lock screen is configured but nothing ever triggers it",
    because: "Without this, every other lock setting is inert.",
  },
  {
    id: "lock-delay",
    title: "There is a grace period before the screen actually locks",
    category: "security",
    severity: "minor",
    weight: 44,
    schemas: SCREENSAVER,
    key: "lock-delay",
    bad: ">30",
    safe: "0",
    detail: "the screen blanks but stays unlocked for the grace period",
    because: "Locking with the blank is the behaviour people assume they have.",
    advisory:
      "No automatic fix. This grace period is a deliberate setting \u2014 it is what lets you nudge the mouse and get back in without typing a password. Change it in Screensaver settings if it is longer than you meant.",
  },
  {
    id: "lock-on-suspend",
    title: "The machine does not lock when it suspends",
    category: "security",
    severity: "major",
    weight: 83,
    schemas: POWER,
    key: "lock-on-suspend",
    bad: "false",
    safe: "true",
    detail: "closing the lid leaves the session open to whoever opens it",
    because: "A suspended laptop is the one most likely to change hands.",
  },
  {
    id: "lock-ubuntu-suspend",
    title: "The machine does not lock when it suspends",
    category: "security",
    severity: "major",
    weight: 82,
    schemas: SCREENSAVER,
    key: "ubuntu-lock-on-suspend",
    bad: "false",
    safe: "true",
    detail: "the Ubuntu-specific suspend lock is switched off",
    because: "It is the switch this desktop actually reads on suspend.",
  },
  {
    id: "lock-user-switch",
    title: "The lock screen offers to switch user",
    category: "security",
    severity: "minor",
    weight: 28,
    schemas: SCREENSAVER,
    key: "user-switch-enabled",
    bad: "true",
    safe: "false",
    detail: "the greeter exposes other accounts from your locked session",
    because: "Switching user is still available after unlocking normally.",
  },
  {
    id: "lock-keyboard-shortcuts",
    title: "Keyboard shortcuts still work on the lock screen",
    category: "security",
    severity: "minor",
    weight: 42,
    schemas: SCREENSAVER,
    key: "allow-keyboard-shortcuts",
    bad: "true",
    safe: "false",
    detail: "shortcuts reach the session through the lock screen",
    because: "A lock screen that forwards keystrokes is not a lock screen.",
  },
  {
    id: "lock-media-control",
    title: "Media playback can be controlled from the lock screen",
    category: "privacy",
    severity: "minor",
    weight: 24,
    schemas: SCREENSAVER,
    key: "allow-media-control",
    bad: "true",
    safe: "false",
    detail: "a passer-by can drive whatever is playing",
    because: "Music resumes normally once you unlock.",
  },
  {
    id: "lock-album-art",
    title: "The lock screen shows what you are playing",
    category: "privacy",
    severity: "minor",
    weight: 18,
    schemas: SCREENSAVER,
    key: "show-album-art",
    bad: "true",
    safe: "false",
    detail: "cover art and track names are visible while locked",
    because: "The player itself still shows them once unlocked.",
  },
  {
    id: "lock-notifications",
    title: "Notifications are shown on the lock screen",
    category: "privacy",
    severity: "major",
    weight: 66,
    schemas: SCREENSAVER,
    key: "show-notifications",
    bad: "true",
    safe: "false",
    detail: "message previews are readable without unlocking",
    because: "The notifications are still waiting for you after you unlock.",
  },
  {
    id: "lock-notifications-gnome",
    title: "Notifications are shown on the lock screen",
    category: "privacy",
    severity: "major",
    weight: 65,
    schemas: ["org.gnome.desktop.notifications"],
    key: "show-in-lock-screen",
    bad: "true",
    safe: "false",
    detail: "message previews are readable without unlocking",
    because: "The notifications are still waiting for you after you unlock.",
  },
  {
    id: "lock-full-name",
    title: "Your full name is displayed on the lock screen",
    category: "privacy",
    severity: "minor",
    weight: 22,
    schemas: SCREENSAVER,
    key: "show-full-name-in-top-bar",
    bad: "true",
    safe: "false",
    detail: "the greeter names you to anyone looking at the screen",
    because: "You do not need your own name to unlock your own machine.",
  },
  {
    id: "lock-embedded-keyboard",
    title: "An on-screen keyboard runs inside the lock screen",
    category: "security",
    severity: "minor",
    weight: 38,
    schemas: SCREENSAVER,
    key: "embedded-keyboard-enabled",
    bad: "true",
    safe: "false",
    detail: "an extra program runs with the screen locked",
    because: "Turn it back on with Undo if you unlock by touch.",
  },
  {
    id: "lock-status-message",
    title: "A custom message is shown on the lock screen",
    category: "privacy",
    severity: "minor",
    weight: 16,
    schemas: SCREENSAVER,
    key: "status-message-enabled",
    bad: "true",
    safe: "false",
    detail: "an away message is displayed to anyone at the desk",
    because: "The message is kept; only its display stops.",
  },
  {
    id: "lockdown-disabled-lock",
    title: "Locking the screen has been disabled outright",
    category: "security",
    severity: "critical",
    weight: 93,
    schemas: ["org.cinnamon.desktop.lockdown", "org.gnome.desktop.lockdown"],
    key: "disable-lock-screen",
    bad: "true",
    safe: "false",
    detail: "the lock command is switched off system-wide for this session",
    because: "Nothing else can protect an unattended screen if this is on.",
  },
];
