// Removable media, and what the desktop does the moment something is plugged
// in. This is the classic drive-by attack surface on a desktop: a USB stick
// that mounts itself and runs something.
import type { SettingPolicy } from "../../type/policy.ts";
import { LOCKDOWN, MEDIA, PRIVACY } from "./schemas.ts";

export const MEDIA_POLICIES: SettingPolicy[] = [
  {
    id: "autorun-never",
    title: "Inserted media may run programs automatically",
    category: "security",
    severity: "critical",
    weight: 94,
    schemas: MEDIA,
    key: "autorun-never",
    bad: "false",
    safe: "true",
    detail: "a USB stick can start software the moment it is plugged in",
    because:
      "Media still mounts and opens; only automatic execution stops. This is " +
      "the single most valuable removable-media setting on a desktop.",
  },
  {
    id: "automount-open",
    title: "Inserted media opens a file manager window by itself",
    category: "security",
    severity: "minor",
    weight: 48,
    schemas: MEDIA,
    key: "automount-open",
    bad: "true",
    safe: "false",
    detail: "plugging anything in spawns a window, thumbnailing its contents",
    because: "The drive still mounts; you open it when you want to.",
  },
  {
    id: "automount",
    title: "Removable media mounts without being asked",
    category: "security",
    severity: "minor",
    weight: 41,
    schemas: MEDIA,
    key: "automount",
    bad: "true",
    safe: "false",
    detail: "any filesystem on any device is mounted as soon as it appears",
    because:
      "Mounting becomes a click in the file manager. Undo restores it if " +
      "you plug drives in constantly.",
  },
  {
    id: "usb-protection",
    title: "USB devices are accepted while the screen is locked",
    category: "security",
    severity: "major",
    weight: 79,
    schemas: PRIVACY,
    key: "usb-protection",
    bad: "false",
    safe: "true",
    detail: "a device plugged in at a locked screen is enumerated anyway",
    because:
      "Devices already attached keep working; only new ones wait for you to " +
      "unlock.",
  },
  {
    id: "lockdown-save-to-disk",
    title: "Saving to disk has been disabled",
    category: "settings",
    severity: "major",
    weight: 58,
    schemas: LOCKDOWN,
    key: "disable-save-to-disk",
    bad: "true",
    safe: "false",
    detail:
      "applications cannot write files — a lockdown an administrator or a kiosk profile sets on purpose, and occasionally one left behind by mistake",
    because: "Restores the ability to save. Nothing existing is touched.",
  },
  {
    id: "lockdown-printing",
    title: "Printing has been disabled",
    category: "settings",
    severity: "minor",
    weight: 26,
    schemas: LOCKDOWN,
    key: "disable-printing",
    bad: "true",
    safe: "false",
    detail: "print dialogs are suppressed across the desktop",
    because: "Restores the print dialog. Undo puts the restriction back.",
  },
  {
    id: "lockdown-print-setup",
    title: "Printer configuration has been disabled",
    category: "settings",
    severity: "minor",
    weight: 11,
    schemas: LOCKDOWN,
    key: "disable-print-setup",
    bad: "true",
    safe: "false",
    detail: "printers cannot be added or changed",
    because: "Restores printer setup. Undo puts the restriction back.",
  },
  {
    id: "lockdown-command-line",
    title: "Command-line access has been disabled",
    category: "settings",
    severity: "minor",
    weight: 27,
    schemas: LOCKDOWN,
    key: "disable-command-line",
    bad: "true",
    safe: "false",
    detail: "the terminal and run-command dialogs are blocked",
    because:
      "Restores them. If this was set deliberately as a kiosk policy, Undo " +
      "puts it straight back.",
  },
  {
    id: "lockdown-user-switching",
    title: "User switching has been disabled",
    category: "settings",
    severity: "minor",
    weight: 10,
    schemas: LOCKDOWN,
    key: "disable-user-switching",
    bad: "true",
    safe: "false",
    detail: "other accounts on this machine cannot be reached",
    because: "Restores switching. Undo puts the restriction back.",
  },
  {
    id: "lockdown-log-out",
    title: "Logging out has been disabled",
    category: "settings",
    severity: "minor",
    weight: 25,
    schemas: LOCKDOWN,
    key: "disable-log-out",
    bad: "true",
    safe: "false",
    detail: "the session cannot be ended from the menu",
    because: "Restores log out — which also restores a way to lock and leave.",
  },
  {
    id: "lockdown-show-password",
    title: "Password fields offer to reveal what you type",
    category: "privacy",
    severity: "minor",
    weight: 23,
    schemas: LOCKDOWN,
    key: "disable-show-password",
    bad: "false",
    safe: "true",
    detail: "the 'show password' eye is available in shared or filmed rooms",
    because: "Typing is unaffected; only the reveal button goes.",
  },
];
