// Directories that must be private outright, and paths whose *write* bit is a
// code-execution path into your session.
//
// The second group is the one people underestimate: a file another account can
// write is a program that runs as you at your next login.

/** [id, $HOME-relative path, what it is, band] */
export type DirRow = [
  id: string,
  path: string,
  what: string,
  sev: "critical" | "major",
];

/** Directories where any group/other access at all is wrong. */
export const PRIVATE_DIRS: DirRow[] = [
  ["ssh-dir", ".ssh", "~/.ssh", "major"],
  ["gnupg-dir", ".gnupg", "~/.gnupg", "critical"],
  [
    "gnupg-private",
    ".gnupg/private-keys-v1.d",
    "your GnuPG private keys",
    "critical",
  ],
  [
    "gnupg-openpgp",
    ".gnupg/openpgp-revocs.d",
    "your GnuPG revocation certificates",
    "critical",
  ],
  ["aws-dir", ".aws", "~/.aws", "major"],
  ["kube-dir", ".kube", "~/.kube", "major"],
  ["docker-dir", ".docker", "~/.docker", "major"],
  ["gcloud-dir", ".config/gcloud", "~/.config/gcloud", "major"],
  [
    "gcloud-legacy",
    ".config/gcloud/legacy_credentials",
    "your gcloud legacy credentials",
    "critical",
  ],
  ["azure-dir", ".azure", "~/.azure", "major"],
  ["keyrings-dir", ".local/share/keyrings", "your login keyring", "critical"],
  ["password-store", ".password-store", "your password store", "critical"],
  ["pki-dir", ".pki", "~/.pki (client certificates)", "critical"],
  ["cert-dir", ".cert", "~/.cert (client certificates)", "critical"],
  [
    "subversion-auth",
    ".subversion/auth",
    "your Subversion saved passwords",
    "critical",
  ],
  ["openvpn-dir", ".config/openvpn", "your VPN profiles and keys", "critical"],
  [
    "wireguard-dir",
    ".config/wireguard",
    "your WireGuard private keys",
    "critical",
  ],
  ["electrum-dir", ".electrum", "your Electrum wallets", "critical"],
  ["bitcoin-dir", ".bitcoin", "your Bitcoin wallet", "critical"],
  ["ethereum-dir", ".ethereum", "your Ethereum keystore", "critical"],
  ["monero-dir", ".bitmonero", "your Monero wallet", "critical"],
  ["signal-dir", ".config/Signal", "your Signal message database", "critical"],
  ["element-dir", ".config/Element", "your Element session keys", "critical"],
  [
    "telegram-dir",
    ".local/share/TelegramDesktop",
    "your Telegram session",
    "critical",
  ],
  ["whatsapp-dir", ".config/WhatsApp", "your WhatsApp session", "critical"],
  ["op-dir", ".config/op", "your 1Password CLI session", "critical"],
  ["keybase-dir", ".config/keybase", "your Keybase session", "critical"],
  [
    "bitwarden-dir",
    ".config/Bitwarden CLI",
    "your Bitwarden session",
    "critical",
  ],
  ["mozilla-dir", ".mozilla", "your Firefox profiles", "major"],
  ["thunderbird-dir", ".thunderbird", "your mail profiles", "major"],
  ["chromium-dir", ".config/chromium", "your Chromium profile", "major"],
  ["chrome-dir", ".config/google-chrome", "your Chrome profile", "major"],
  [
    "podman-dir",
    ".config/containers",
    "your container registry logins",
    "major",
  ],
  ["ipython-dir", ".ipython", "your IPython profile", "major"],
  ["jupyter-dir", ".jupyter", "your Jupyter configuration and tokens", "major"],
  ["claude-dir", ".claude", "~/.claude", "major"],
  ["cache-dir", ".cache", "~/.cache", "major"],
  [
    "gnome-secrets",
    ".local/share/nautilus/scripts",
    "your file-manager scripts",
    "major",
  ],
  ["restic-dir", ".config/restic", "your backup configuration", "major"],
  ["borg-dir", ".config/borg", "your Borg configuration", "major"],
  ["ansible-dir", ".ansible", "~/.ansible", "major"],
  ["terraform-dir", ".terraform.d", "~/.terraform.d", "major"],
  ["pulumi-dir", ".pulumi", "~/.pulumi", "major"],
  ["vault-dir", ".vault", "~/.vault", "critical"],
  [
    "ssh-control",
    ".ssh/controlmasters",
    "your multiplexed SSH sockets",
    "critical",
  ],
  [
    "gpg-agent-sock",
    ".gnupg/S.gpg-agent",
    "your GnuPG agent socket",
    "critical",
  ],
  ["mc-dir", ".mc", "your MinIO client configuration", "critical"],
  ["syncthing-dir", ".config/syncthing", "your Syncthing keys", "critical"],
  ["nextcloud-dir", ".config/Nextcloud", "your Nextcloud account", "major"],
  [
    "remmina-dir",
    ".local/share/remmina",
    "your remote-desktop credentials",
    "critical",
  ],
  [
    "filezilla-dir",
    ".config/filezilla",
    "your FileZilla site passwords",
    "critical",
  ],
  ["slack-dir", ".config/Slack", "your Slack session", "critical"],
  ["discord-dir", ".config/discord", "your Discord session", "critical"],
  ["steam-dir", ".steam", "your Steam session", "major"],
  ["obs-dir", ".config/obs-studio", "your stream keys", "critical"],
  [
    "yubico-dir",
    ".config/Yubico",
    "your hardware-token registrations",
    "critical",
  ],
  ["gopass-dir", ".config/gopass", "your gopass configuration", "major"],
  ["k9s-dir", ".config/k9s", "your cluster configuration", "major"],
  ["argocd-dir", ".config/argocd", "your Argo CD token", "critical"],
  ["talos-dir", ".talos", "your Talos credentials", "critical"],
  ["circleci-dir", ".circleci", "your CircleCI token", "critical"],
  [
    "gitlab-runner-dir",
    ".gitlab-runner",
    "your GitLab runner token",
    "critical",
  ],
  ["m2-dir", ".m2", "your Maven repository passwords", "major"],
  ["gradle-dir", ".gradle", "your Gradle signing keys", "major"],
  ["sbt-dir", ".sbt", "your sbt credentials", "major"],
  ["ivy-dir", ".ivy2", "your Ivy credentials", "major"],
  ["nuget-dir", ".nuget", "your NuGet credentials", "major"],
  ["cargo-dir", ".cargo", "~/.cargo", "major"],
  ["rustup-dir", ".rustup", "~/.rustup", "major"],
  ["npm-dir", ".npm", "~/.npm", "major"],
  ["yarn-dir", ".yarn", "~/.yarn", "major"],
  ["pnpm-dir", ".local/share/pnpm", "~/.local/share/pnpm", "major"],
  ["deno-dir", ".cache/deno", "~/.cache/deno", "major"],
  ["bun-dir", ".bun", "~/.bun", "major"],
  ["conda-dir", ".conda", "~/.conda", "major"],
  ["poetry-dir", ".config/pypoetry", "your Poetry tokens", "critical"],
  ["httpie-dir", ".config/httpie", "your saved API sessions", "critical"],
  ["insomnia-dir", ".config/Insomnia", "your saved API tokens", "critical"],
  ["postman-dir", ".config/Postman", "your saved API tokens", "critical"],
  ["atuin-dir", ".local/share/atuin", "your shell history database", "major"],
  ["gvfs-dir", ".gvfs", "your mounted network shares", "major"],
  ["nix-dir", ".nix-defexpr", "your Nix channel definitions", "major"],
  ["guix-dir", ".config/guix", "your Guix configuration", "major"],
  ["asdf-dir", ".asdf", "your toolchain installs", "major"],
  ["mise-dir", ".local/share/mise", "your toolchain installs", "major"],
  ["sdkman-dir", ".sdkman", "your toolchain installs", "major"],
  ["nvm-dir", ".nvm", "your Node installs", "major"],
  ["pyenv-dir", ".pyenv", "your Python installs", "major"],
  ["rbenv-dir", ".rbenv", "your Ruby installs", "major"],
  ["gvm-dir", ".gvm", "your Go installs", "major"],
  ["virtualenvs-dir", ".virtualenvs", "your Python environments", "major"],
  [
    "poetry-venvs",
    ".cache/pypoetry/virtualenvs",
    "your Python environments",
    "major",
  ],
  [
    "jupyter-runtime-dir",
    ".local/share/jupyter",
    "your notebook tokens",
    "critical",
  ],
  [
    "vscode-dir",
    ".config/Code",
    "your editor configuration and tokens",
    "major",
  ],
  [
    "vscodium-dir",
    ".config/VSCodium",
    "your editor configuration and tokens",
    "major",
  ],
  [
    "cursor-dir",
    ".config/Cursor",
    "your editor configuration and tokens",
    "major",
  ],
  ["zed-dir", ".config/zed", "your editor configuration and tokens", "major"],
  [
    "jetbrains-dir",
    ".config/JetBrains",
    "your IDE configuration and tokens",
    "major",
  ],
  ["sublime-dir", ".config/sublime-text", "your editor configuration", "major"],
  ["emacs-dir", ".emacs.d", "your editor configuration and packages", "major"],
  [
    "nvim-dir",
    ".config/nvim",
    "your editor configuration and plugins",
    "major",
  ],
  ["vim-dir", ".vim", "your editor configuration and plugins", "major"],
  ["helix-dir", ".config/helix", "your editor configuration", "major"],
  ["tmux-plugins", ".tmux", "your terminal multiplexer plugins", "major"],
  ["zsh-dir", ".oh-my-zsh", "your shell framework and plugins", "critical"],
  ["bash-it", ".bash_it", "your shell framework and plugins", "critical"],
  [
    "fish-dir",
    ".config/fish",
    "your shell configuration and functions",
    "critical",
  ],
  [
    "starship-dir",
    ".config/starship.toml",
    "your prompt configuration",
    "major",
  ],
  [
    "direnv-dir",
    ".config/direnv",
    "which project scripts you have authorised",
    "critical",
  ],
  [
    "ansible-collections",
    ".ansible/collections",
    "the automation code you run",
    "critical",
  ],
  [
    "terraform-plugins",
    ".terraform.d/plugins",
    "the providers your infrastructure code runs",
    "critical",
  ],
  [
    "helm-plugins",
    ".local/share/helm/plugins",
    "the plugins your cluster tooling runs",
    "critical",
  ],
  ["krew-dir", ".krew", "your kubectl plugins", "critical"],
  ["cargo-bin", ".cargo/bin", "programs on your PATH", "critical"],
  ["go-bin", "go/bin", "programs on your PATH", "critical"],
  ["npm-global", ".npm-global", "programs on your PATH", "critical"],
  ["pipx-dir", ".local/pipx", "programs on your PATH", "critical"],
  ["gem-bin", ".local/share/gem", "programs on your PATH", "critical"],
  [
    "composer-vendor",
    ".config/composer/vendor",
    "programs on your PATH",
    "critical",
  ],
  ["dotnet-tools", ".dotnet/tools", "programs on your PATH", "critical"],
  ["bin-dir", "bin", "programs on your PATH", "critical"],
  ["appimage-dir", "Applications", "the AppImages you run", "critical"],
  ["scripts-dir", "scripts", "scripts you run", "critical"],
  ["gnupg-crls", ".gnupg/crls.d", "your GnuPG revocation cache", "major"],
  ["libvirt-dir", ".config/libvirt", "your hypervisor configuration", "major"],
  ["boxes-dir", ".config/gnome-boxes", "your virtual machines", "major"],
  ["vbox-dir", ".config/VirtualBox", "your virtual machine inventory", "major"],
  ["wine-prefix", ".wine", "your Windows application data", "major"],
  [
    "proton-dir",
    ".steam/steam/steamapps/compatdata",
    "your game save data",
    "major",
  ],
  ["davfs-dir", ".davfs2", "your WebDAV credentials", "critical"],
  ["autofs-dir", ".config/autofs", "your automount configuration", "major"],
];

/** [id, paths, what, title, band, weight] — a file or directory whose *write*
 *  permission for other accounts is the finding. */
export type ExecRow = [
  id: string,
  paths: string[],
  what: string,
  title: string,
  sev: "critical" | "major",
  weight: number,
];

export const WRITABLE_PATHS: ExecRow[] = [
  [
    "login-scripts",
    [
      ".xinitrc",
      ".xprofile",
      ".xsession",
      ".xsessionrc",
      ".bash_login",
      ".bash_logout",
      ".zlogin",
      ".zprofile",
      ".zlogout",
      ".pam_environment",
    ],
    "your session startup scripts",
    "A session startup script is writable by other accounts",
    "critical",
    94,
  ],
  [
    "shell-rc",
    [
      ".bashrc",
      ".bash_profile",
      ".profile",
      ".zshrc",
      ".zshenv",
      ".zshrc.local",
    ],
    "your shell startup files",
    "A shell startup file is writable by other accounts",
    "critical",
    93,
  ],
  [
    "user-units",
    [".config/systemd/user"],
    "~/.config/systemd/user",
    "Your systemd user units are writable by other accounts",
    "critical",
    92,
  ],
  [
    "autostart-dir",
    [".config/autostart"],
    "~/.config/autostart",
    "Your autostart directory is writable by other accounts",
    "critical",
    91,
  ],
  [
    "desktop-entries",
    [".local/share/applications"],
    "~/.local/share/applications",
    "Your desktop entries are writable by other accounts",
    "critical",
    90,
  ],
  [
    "environment-d",
    [".config/environment.d"],
    "~/.config/environment.d",
    "Your session environment directory is writable by other accounts",
    "critical",
    89,
  ],
  [
    "path-dirs",
    [".local/bin", "bin", ".cargo/bin", "go/bin", ".npm-global/bin"],
    "the directories on your PATH inside $HOME",
    "A directory on your PATH is writable by other accounts",
    "critical",
    88,
  ],
  [
    "fm-scripts",
    [".local/share/nemo/scripts", ".local/share/nautilus/scripts"],
    "your file-manager script directories",
    "Your file-manager scripts are writable by other accounts",
    "major",
    77,
  ],
  [
    "git-config",
    [".gitconfig", ".config/git/config"],
    "your git configuration",
    "Your git configuration is writable by other accounts",
    "critical",
    86,
  ],
  [
    "ssh-config-write",
    [".ssh/config"],
    "~/.ssh/config",
    "Your SSH client configuration is writable by other accounts",
    "critical",
    96,
  ],
  [
    "pkg-config-write",
    [".npmrc", ".yarnrc.yml", ".cargo/config.toml", ".config/pip/pip.conf"],
    "your package-manager configuration",
    "Your package-manager configuration is writable by other accounts",
    "major",
    75,
  ],
  [
    "editor-config",
    [".vimrc", ".config/nvim/init.lua", ".config/nvim/init.vim", ".emacs"],
    "your editor configuration",
    "Your editor configuration is writable by other accounts",
    "critical",
    85,
  ],
  [
    "config-dir",
    [".config"],
    "~/.config",
    "~/.config is writable by other accounts",
    "major",
    73,
  ],
  [
    "local-dir",
    [".local", ".local/share"],
    "~/.local",
    "~/.local is writable by other accounts",
    "major",
    72,
  ],
  [
    "downloads",
    ["Downloads"],
    "~/Downloads",
    "Your Downloads folder is writable by other accounts",
    "major",
    71,
  ],
  [
    "forward",
    [".forward"],
    "~/.forward",
    "Your mail forwarding file is writable by other accounts",
    "major",
    74,
  ],
];
