// History and state files. Not credentials — a transcript of your work, and
// often enough a password someone typed on a command line once.

/** [id, $HOME-relative path, what it records] */
export type HistoryRow = [id: string, path: string, name: string];

export const HISTORY_FILES: HistoryRow[] = [
  ["bash-history", ".bash_history", "your shell history"],
  ["zsh-history", ".zsh_history", "your shell history"],
  ["fish-history", ".local/share/fish/fish_history", "your fish history"],
  ["python-history", ".python_history", "your Python REPL history"],
  [
    "ipython-history",
    ".ipython/profile_default/history.sqlite",
    "your IPython history",
  ],
  ["node-history", ".node_repl_history", "your Node REPL history"],
  [
    "deno-history",
    ".local/share/deno/deno_history.txt",
    "your Deno REPL history",
  ],
  ["psql-history", ".psql_history", "your psql history"],
  ["mysql-history", ".mysql_history", "your MySQL client history"],
  ["sqlite-history", ".sqlite_history", "your sqlite history"],
  ["redis-history", ".rediscli_history", "your redis-cli history"],
  ["mongo-history", ".dbshell", "your MongoDB shell history"],
  ["sftp-history", ".sftp_history", "your sftp history"],
  ["gdb-history", ".gdb_history", "your debugger history"],
  ["lldb-history", ".lldb/lldb-history", "your debugger history"],
  ["r-history", ".Rhistory", "your R history"],
  ["octave-history", ".octave_hist", "your Octave history"],
  ["julia-history", ".julia/logs/repl_history.jl", "your Julia REPL history"],
  ["irb-history", ".irb_history", "your Ruby REPL history"],
  ["php-history", ".php_history", "your PHP REPL history"],
  ["scala-history", ".scala_history", "your Scala REPL history"],
  ["erlang-history", ".erlang-history", "your Erlang shell history"],
  ["less-history", ".lesshst", "what you have paged through"],
  ["viminfo", ".viminfo", "the files and searches Vim remembers"],
  [
    "nvim-shada",
    ".local/state/nvim/shada/main.shada",
    "the files and searches Neovim remembers",
  ],
  [
    "recently-used",
    ".local/share/recently-used.xbel",
    "the list of files you have opened",
  ],
  ["wget-hsts", ".wget-hsts", "the HTTPS sites wget has visited"],
  ["aws-cli-history", ".aws/cli/history", "your AWS CLI history"],
  ["kube-cache", ".kube/cache", "the clusters you have talked to"],
  ["docker-run-history", ".docker/run", "your container runtime state"],
  ["zsh-histfile-alt", ".histfile", "your shell history"],
  ["ksh-history", ".sh_history", "your shell history"],
  ["tcsh-history", ".history", "your shell history"],
  ["nu-history", ".config/nushell/history.txt", "your Nushell history"],
  ["elvish-history", ".local/state/elvish/db", "your Elvish history"],
  [
    "xonsh-history",
    ".local/share/xonsh/xonsh-history.sqlite",
    "your xonsh history",
  ],
  [
    "clickhouse-history",
    ".clickhouse-client-history",
    "your ClickHouse history",
  ],
  ["influx-history", ".influx_history", "your InfluxDB history"],
  ["cqlsh-history", ".cassandra/cqlsh_history", "your Cassandra history"],
  ["sqlplus-history", ".sqlplus_history", "your Oracle client history"],
  [
    "httpie-sessions",
    ".config/httpie/sessions",
    "the requests HTTPie has replayed",
  ],
  ["fzf-history", ".fzf_history", "what you have searched for in the shell"],
  [
    "atuin-db",
    ".local/share/atuin/history.db",
    "your full shell history database",
  ],
  [
    "zoxide-db",
    ".local/share/zoxide/db.zo",
    "every directory you have visited",
  ],
  ["mc-history", ".local/share/mc/history", "your file-manager history"],
  [
    "ranger-history",
    ".local/share/ranger/history",
    "your file-manager history",
  ],
  ["tig-history", ".tig_history", "your git browsing history"],
  [
    "nano-history",
    ".local/share/nano/search_history",
    "your editor search history",
  ],
  [
    "thumbnails-normal",
    ".cache/thumbnails",
    "small copies of images you have viewed",
  ],
  ["tracker-index", ".cache/tracker3", "an index of your documents"],
  ["baloo-index", ".local/share/baloo", "an index of your documents"],
  [
    "gtk-recent",
    ".local/share/gvfs-metadata",
    "which files you opened over the network",
  ],
  ["firefox-places", ".mozilla/firefox", "every page you have visited"],
  [
    "chrome-history",
    ".config/google-chrome/Default/History",
    "every page you have visited",
  ],
  [
    "chromium-history",
    ".config/chromium/Default/History",
    "every page you have visited",
  ],
  [
    "chrome-topsites",
    ".config/google-chrome/Default/Top Sites",
    "the sites you visit most",
  ],
  [
    "vlc-recent",
    ".config/vlc/vlc-qt-interface.conf",
    "the media you have played",
  ],
  [
    "mpv-watch",
    ".local/state/mpv/watch_later",
    "what you were watching and where you stopped",
  ],
  ["gimp-recent", ".config/GIMP", "the images you have edited"],
  [
    "libreoffice-recent",
    ".config/libreoffice/4/user/registrymodifications.xcu",
    "the documents you have opened",
  ],
  ["evince-recent", ".config/evince", "the documents you have read"],
  [
    "okular-docdata",
    ".local/share/okular/docdata",
    "the documents you have read and your notes on them",
  ],
  [
    "zathura-history",
    ".local/share/zathura/history",
    "the documents you have read",
  ],
  ["calibre-db", ".config/calibre", "your library and reading position"],
  ["telegram-cache", ".cache/TelegramDesktop", "cached message media"],
  ["discord-cache", ".config/discord/Cache", "cached message media"],
  ["slack-cache", ".config/Slack/Cache", "cached message media"],
  [
    "signal-attachments",
    ".config/Signal/attachments.noindex",
    "message attachments",
  ],
  ["thunderbird-cache", ".cache/thunderbird", "cached mail content"],
  [
    "systemd-user-journal",
    ".local/share/systemd",
    "what your user services have logged",
  ],
  [
    "xsession-errors",
    ".xsession-errors",
    "everything your session has printed, including error output from your programs",
  ],
  [
    "xorg-log",
    ".local/share/xorg/Xorg.0.log",
    "your display and input device layout",
  ],
  [
    "wireshark-recent",
    ".config/wireshark/recent",
    "the captures you have opened",
  ],
  ["nmap-history", ".nmap", "the hosts you have scanned"],
  [
    "gnome-shell-search",
    ".cache/gnome-shell",
    "what you have searched for in the shell",
  ],
  ["dconf-user", ".config/dconf/user", "every desktop setting on this account"],
  [
    "fontconfig-cache",
    ".cache/fontconfig",
    "the fonts installed for this account",
  ],
  ["bash-sessions", ".bash_sessions", "your saved shell sessions"],
  [
    "gtk-bookmarks",
    ".config/gtk-3.0/bookmarks",
    "the folders you have bookmarked",
  ],
  [
    "user-dirs",
    ".config/user-dirs.dirs",
    "where your documents and downloads live",
  ],
  [
    "trash-info",
    ".local/share/Trash/info",
    "the original path of everything you have deleted",
  ],
  ["recently-used-old", ".recently-used", "the list of files you have opened"],
  ["gnupg-random-seed", ".gnupg/random_seed", "the GnuPG random seed"],
  ["mailcap", ".mailcap", "which program opens which attachment type"],
  ["wall-clock", ".config/autostart-scripts", "scripts that run at login"],
  [
    "pulse-cookie",
    ".config/pulse/cookie",
    "your audio server authentication cookie",
  ],
  [
    "xauthority",
    ".Xauthority",
    "the cookie that grants access to your display",
  ],
  [
    "ica-cookie",
    ".ICEauthority",
    "the cookie that grants access to your session bus",
  ],
  ["krb-ccache", ".krb5cc", "your Kerberos ticket cache"],
  ["gnome-keyring-control", ".cache/keyring", "your keyring control socket"],
  ["zsh-zcompdump", ".zcompdump", "the commands your shell can complete"],
  ["bash-aliases", ".bash_aliases", "your shell aliases"],
  ["ssh-agent-sock-dir", ".ssh/sockets", "your multiplexed SSH sessions"],
  ["gnupg-trustdb", ".gnupg/trustdb.gpg", "which keys you trust"],
  ["gnupg-pubring", ".gnupg/pubring.kbx", "whose keys you hold"],
  [
    "gtk-recent-2",
    ".local/share/recently-used.xbel.bak",
    "the list of files you have opened",
  ],
  [
    "nautilus-metadata",
    ".local/share/nautilus",
    "how you have arranged your folders",
  ],
  ["nemo-metadata", ".local/share/nemo", "how you have arranged your folders"],
  ["gnome-boxes", ".local/share/gnome-boxes", "your virtual machines"],
  ["virtualbox-vms", "VirtualBox VMs", "your virtual machines"],
  [
    "libvirt-images",
    ".local/share/libvirt/images",
    "your virtual machine disks",
  ],
  [
    "podman-storage",
    ".local/share/containers/storage",
    "your container images and volumes",
  ],
  ["docker-desktop", ".docker/desktop", "your Docker Desktop state"],
  ["steam-userdata", ".steam/steam/userdata", "your game saves and account id"],
  ["lutris-games", ".local/share/lutris", "your game library"],
  ["heroic-config", ".config/heroic", "your game store accounts"],
  ["retroarch-saves", ".config/retroarch/saves", "your game saves"],
  ["kdenlive-recent", ".local/share/kdenlive", "the projects you have edited"],
  ["blender-recent", ".config/blender", "the projects you have opened"],
  ["inkscape-recent", ".config/inkscape", "the documents you have edited"],
  [
    "darktable-library",
    ".config/darktable/library.db",
    "every photo you have imported",
  ],
  ["shotwell-db", ".local/share/shotwell/data", "your photo library"],
  ["rhythmbox-db", ".local/share/rhythmbox", "your music library"],
  ["audacity-cfg", ".config/audacity", "the recordings you have opened"],
  ["obs-scenes", ".config/obs-studio/basic/scenes", "your stream layout"],
  ["zoom-data", ".zoom", "your meeting history"],
  ["teams-cache", ".config/Microsoft/Microsoft Teams", "your chat cache"],
  ["skype-data", ".config/skypeforlinux", "your chat history"],
  [
    "element-store",
    ".config/Element/IndexedDB",
    "your decrypted message index",
  ],
  [
    "thunderbird-index",
    ".thunderbird/global-messages-db.sqlite",
    "the full text of your mail",
  ],
  ["evolution-cache", ".cache/evolution", "cached mail and calendar entries"],
  [
    "gnome-online-accounts",
    ".config/goa-1.0",
    "which online accounts you have linked",
  ],
  ["keepassxc-recent", ".cache/keepassxc", "the databases you have opened"],
  ["gpg-agent-cache", ".cache/gnupg", "GnuPG agent state"],
  ["pip-cache", ".cache/pip", "the packages you have installed"],
  ["npm-cache", ".npm/_cacache", "the packages you have installed"],
  ["cargo-registry", ".cargo/registry", "the crates you have built against"],
  ["go-modcache", "go/pkg/mod", "the modules you have built against"],
  ["maven-repo", ".m2/repository", "the artifacts you have built against"],
  ["gradle-caches", ".gradle/caches", "the artifacts you have built against"],
  ["composer-cache", ".cache/composer", "the packages you have installed"],
  ["yarn-cache", ".cache/yarn", "the packages you have installed"],
  ["nix-profile", ".nix-profile", "the packages installed for this account"],
  [
    "vscode-storage",
    ".config/Code/User/globalStorage",
    "your editor extension data",
  ],
  [
    "sublime-session",
    ".config/sublime-text/Local/Session.sublime_session",
    "your open files and unsaved buffers",
  ],
  ["emacs-recentf", ".emacs.d/recentf", "the files you have opened"],
  ["helix-state", ".local/state/helix", "the files you have opened"],
  ["kate-session", ".local/share/kate", "your open documents"],
];
