// Files that hold a credential. Each one is exactly one leak away from being
// somebody else's access, so each gets its own row rather than a wildcard —
// the report names the thing that is exposed, not "a file".
//
// A path that does not exist on this machine is simply not applicable.

/** [id, $HOME-relative path, what it is, band] */
export type SecretRow = [
  id: string,
  path: string,
  what: string,
  sev: "critical" | "major",
];

export const SECRET_FILES: SecretRow[] = [
  // --- shell and network login ---
  ["netrc", ".netrc", "~/.netrc (login passwords in clear text)", "critical"],
  ["netrc-gpg", ".netrc.gpg", "your encrypted netrc", "major"],
  ["authinfo", ".authinfo", "~/.authinfo (Emacs stored logins)", "critical"],
  ["rhosts-file", ".rhosts", "~/.rhosts (host-based trust)", "critical"],

  // --- cloud providers ---
  ["aws-credentials", ".aws/credentials", "your AWS credentials", "critical"],
  ["aws-config", ".aws/config", "your AWS profile configuration", "major"],
  [
    "gcloud-creds",
    ".config/gcloud/credentials.db",
    "your gcloud credentials",
    "critical",
  ],
  [
    "gcloud-access",
    ".config/gcloud/access_tokens.db",
    "your gcloud access tokens",
    "critical",
  ],
  [
    "gcloud-adc",
    ".config/gcloud/application_default_credentials.json",
    "your gcloud default credentials",
    "critical",
  ],
  ["azure-profile", ".azure/azureProfile.json", "your Azure profile", "major"],
  [
    "azure-tokens",
    ".azure/accessTokens.json",
    "your Azure access tokens",
    "critical",
  ],
  ["oci-config", ".oci/config", "your Oracle Cloud credentials", "critical"],
  ["doctl", ".config/doctl/config.yaml", "your DigitalOcean token", "critical"],
  ["hcloud", ".config/hcloud/cli.toml", "your Hetzner token", "critical"],
  ["linode", ".config/linode-cli", "your Linode token", "critical"],
  ["scaleway", ".config/scw/config.yaml", "your Scaleway token", "critical"],
  ["fly", ".fly/config.yml", "your Fly.io token", "critical"],
  ["heroku-netrc", ".netrc.heroku", "your Heroku credentials", "critical"],
  [
    "cloudflared",
    ".cloudflared/cert.pem",
    "your Cloudflare tunnel certificate",
    "critical",
  ],

  // --- clusters and containers ---
  [
    "kube-config",
    ".kube/config",
    "your Kubernetes cluster credentials",
    "critical",
  ],
  [
    "docker-config",
    ".docker/config.json",
    "your container registry logins",
    "critical",
  ],
  [
    "containers-auth",
    ".config/containers/auth.json",
    "your Podman registry logins",
    "critical",
  ],
  [
    "helm-repo",
    ".config/helm/repositories.yaml",
    "your Helm repository credentials",
    "major",
  ],

  // --- source hosting ---
  ["git-credentials", ".git-credentials", "~/.git-credentials", "critical"],
  ["gh-hosts", ".config/gh/hosts.yml", "your GitHub CLI token", "critical"],
  ["glab", ".config/glab-cli/config.yml", "your GitLab CLI token", "critical"],
  ["hub", ".config/hub", "your GitHub token (hub)", "critical"],
  ["tea", ".config/tea/config.yml", "your Gitea token", "critical"],

  // --- package registries ---
  ["npmrc", ".npmrc", "~/.npmrc (registry tokens)", "critical"],
  ["yarnrc", ".yarnrc.yml", "~/.yarnrc.yml (registry tokens)", "critical"],
  ["pypirc", ".pypirc", "~/.pypirc (package index tokens)", "critical"],
  [
    "cargo-credentials",
    ".cargo/credentials.toml",
    "your crates.io token",
    "critical",
  ],
  ["gem-credentials", ".gem/credentials", "your RubyGems token", "critical"],
  ["composer-auth", ".composer/auth.json", "your Composer tokens", "critical"],
  [
    "nuget-config",
    ".nuget/NuGet/NuGet.Config",
    "your NuGet feed credentials",
    "critical",
  ],
  [
    "m2-settings",
    ".m2/settings.xml",
    "your Maven repository passwords",
    "critical",
  ],
  [
    "gradle-props",
    ".gradle/gradle.properties",
    "your Gradle signing keys",
    "critical",
  ],
  [
    "pypoetry-auth",
    ".config/pypoetry/auth.toml",
    "your Poetry repository tokens",
    "critical",
  ],
  ["netrc-hex", ".hex/hex.config", "your Hex token", "critical"],

  // --- secret management ---
  ["vault-token", ".vault-token", "your HashiCorp Vault token", "critical"],
  [
    "ansible-vault",
    ".ansible/vault_pass",
    "your Ansible vault password",
    "critical",
  ],
  ["age-keys", ".config/age/keys.txt", "your age private keys", "critical"],
  ["sops-age", ".config/sops/age/keys.txt", "your SOPS age keys", "critical"],
  [
    "terraformrc",
    ".terraformrc",
    "~/.terraformrc (registry tokens)",
    "critical",
  ],
  [
    "terraform-creds",
    ".terraform.d/credentials.tfrc.json",
    "your Terraform Cloud token",
    "critical",
  ],
  ["pulumi-creds", ".pulumi/credentials.json", "your Pulumi token", "critical"],

  // --- databases ---
  ["pgpass", ".pgpass", "~/.pgpass (database passwords)", "critical"],
  [
    "pgservice",
    ".pg_service.conf",
    "your PostgreSQL service passwords",
    "critical",
  ],
  ["mycnf", ".my.cnf", "~/.my.cnf (MySQL credentials)", "critical"],
  ["odbc-ini", ".odbc.ini", "your ODBC connection passwords", "critical"],
  ["mongo-config", ".mongorc.js", "~/.mongorc.js", "major"],

  // --- object storage ---
  ["s3cfg", ".s3cfg", "~/.s3cfg (S3 keys)", "critical"],
  ["boto", ".boto", "~/.boto (cloud credentials)", "critical"],
  [
    "rclone-conf",
    ".config/rclone/rclone.conf",
    "your rclone remotes",
    "critical",
  ],
  [
    "restic-pass",
    ".config/restic/password",
    "your backup passphrase",
    "critical",
  ],
  [
    "borg-passphrase",
    ".config/borg/passphrase",
    "your Borg passphrase",
    "critical",
  ],

  // --- mail and chat ---
  ["msmtprc", ".msmtprc", "~/.msmtprc (mail account passwords)", "critical"],
  ["mbsyncrc", ".mbsyncrc", "~/.mbsyncrc (mail account passwords)", "critical"],
  [
    "fetchmailrc",
    ".fetchmailrc",
    "~/.fetchmailrc (mail passwords)",
    "critical",
  ],
  [
    "offlineimaprc",
    ".offlineimaprc",
    "~/.offlineimaprc (mail passwords)",
    "critical",
  ],
  ["muttrc", ".muttrc", "~/.muttrc (may hold an IMAP password)", "major"],
  ["irssi-config", ".irssi/config", "your IRC passwords", "major"],
  ["weechat-sec", ".weechat/sec.conf", "your WeeChat secured data", "critical"],

  // --- wallets and messengers ---
  ["solana-id", ".config/solana/id.json", "your Solana keypair", "critical"],
  ["kaggle", ".kaggle/kaggle.json", "your Kaggle API token", "critical"],
  [
    "chrome-login-data",
    ".config/google-chrome/Default/Login Data",
    "your Chrome saved passwords",
    "critical",
  ],
  [
    "chromium-login-data",
    ".config/chromium/Default/Login Data",
    "your Chromium saved passwords",
    "critical",
  ],

  // --- more registries, CI and services ---
  ["circleci", ".circleci/cli.yml", "your CircleCI token", "critical"],
  ["travis", ".travis/config.yml", "your Travis CI token", "critical"],
  [
    "jfrog",
    ".jfrog/jfrog-cli.conf.v6",
    "your Artifactory credentials",
    "critical",
  ],
  [
    "sbt-credentials",
    ".sbt/.credentials",
    "your sbt repository credentials",
    "critical",
  ],
  [
    "ivy-credentials",
    ".ivy2/.credentials",
    "your Ivy repository credentials",
    "critical",
  ],
  [
    "lein-profiles",
    ".lein/profiles.clj",
    "your Leiningen repository credentials",
    "critical",
  ],
  ["mix-hex", ".hex/cache.ets", "your Hex session", "major"],
  [
    "dart-pub",
    ".config/dart/pub-credentials.json",
    "your pub.dev token",
    "critical",
  ],
  [
    "flutter-creds",
    ".config/flutter/tool-state",
    "your Flutter tool state",
    "major",
  ],
  ["conda-token", ".condarc", "~/.condarc (channel tokens)", "critical"],
  ["renv-auth", ".Renviron", "~/.Renviron (R environment secrets)", "critical"],
  [
    "dotnet-nuget",
    ".config/NuGet/NuGet.Config",
    "your NuGet feed credentials",
    "critical",
  ],
  [
    "dbeaver-creds",
    ".local/share/DBeaverData/workspace6/General/.dbeaver/credentials-config.json",
    "your DBeaver saved passwords",
    "critical",
  ],
  [
    "mysql-workbench",
    ".mysql/workbench/connections.xml",
    "your MySQL Workbench connections",
    "critical",
  ],
  [
    "filezilla",
    ".config/filezilla/sitemanager.xml",
    "your FileZilla site passwords",
    "critical",
  ],
  ["anydesk", ".anydesk/user.conf", "your AnyDesk configuration", "major"],
  [
    "teamviewer",
    ".config/teamviewer/client.conf",
    "your TeamViewer configuration",
    "major",
  ],
  [
    "nextcloud",
    ".config/Nextcloud/nextcloud.cfg",
    "your Nextcloud account",
    "major",
  ],
  [
    "syncthing",
    ".config/syncthing/config.xml",
    "your Syncthing device keys",
    "critical",
  ],
  [
    "syncthing-key",
    ".config/syncthing/key.pem",
    "your Syncthing private key",
    "critical",
  ],
  ["dropbox-info", ".dropbox/info.json", "your Dropbox account paths", "major"],
  [
    "megasync",
    ".config/megasync/MEGAsync.cfg",
    "your MEGA account",
    "critical",
  ],
  [
    "rustup-settings",
    ".rustup/settings.toml",
    "~/.rustup/settings.toml",
    "major",
  ],
  [
    "bundle-config",
    ".bundle/config",
    "~/.bundle/config (gem source credentials)",
    "critical",
  ],
  [
    "gitlab-runner",
    ".gitlab-runner/config.toml",
    "your GitLab runner token",
    "critical",
  ],
  ["argocd", ".config/argocd/config", "your Argo CD token", "critical"],
  ["k9s", ".config/k9s/config.yaml", "your k9s cluster configuration", "major"],
  ["talos", ".talos/config", "your Talos cluster credentials", "critical"],
  ["nomad-token", ".nomad-token", "your Nomad token", "critical"],
  ["consul-token", ".consul-token", "your Consul token", "critical"],
  ["minio-config", ".mc/config.json", "your MinIO credentials", "critical"],
  ["b2-account", ".b2_account_info", "your Backblaze credentials", "critical"],
  [
    "duplicity",
    ".config/duplicity/credentials",
    "your backup credentials",
    "critical",
  ],
  [
    "borgmatic",
    ".config/borgmatic/config.yaml",
    "your borgmatic configuration",
    "critical",
  ],
  ["mutt-aliases", ".mutt/passwords", "your Mutt stored passwords", "critical"],
  [
    "neomutt",
    ".neomuttrc",
    "~/.neomuttrc (may hold an IMAP password)",
    "major",
  ],
  [
    "aerc-accounts",
    ".config/aerc/accounts.conf",
    "your aerc mail accounts",
    "critical",
  ],
  ["isync", ".mbsyncpass", "your mail sync password", "critical"],
  [
    "pass-extensions",
    ".password-store/.gpg-id",
    "which key unlocks your password store",
    "major",
  ],
  ["gopass", ".config/gopass/config.yml", "your gopass configuration", "major"],
  [
    "yubico",
    ".config/Yubico/u2f_keys",
    "your U2F key registrations",
    "critical",
  ],
  [
    "pam-u2f",
    ".config/Yubico/challenge",
    "your challenge-response secret",
    "critical",
  ],
  [
    "autokey",
    ".config/autokey/autokey.json",
    "your keyboard automation scripts",
    "major",
  ],
  [
    "espanso",
    ".config/espanso/match/base.yml",
    "your text expansions",
    "major",
  ],
  ["zoom-conf", ".config/zoomus.conf", "your Zoom account settings", "major"],
  [
    "slack-cookies",
    ".config/Slack/Cookies",
    "your Slack session cookies",
    "critical",
  ],
  [
    "discord-leveldb",
    ".config/discord/Local Storage",
    "your Discord session token",
    "critical",
  ],
  [
    "spotify-creds",
    ".config/spotify/prefs",
    "your Spotify credentials",
    "major",
  ],
  [
    "steam-config",
    ".steam/steam/config/config.vdf",
    "your Steam login tokens",
    "critical",
  ],
  ["lutris-auth", ".cache/lutris/auth-token", "your Lutris token", "major"],
  [
    "itch-butler",
    ".config/itch/butler_creds",
    "your itch.io token",
    "critical",
  ],
  [
    "obs-profiles",
    ".config/obs-studio/basic/profiles",
    "your stream keys",
    "critical",
  ],
  [
    "transmission-settings",
    ".config/transmission/settings.json",
    "your Transmission RPC password",
    "major",
  ],
  [
    "qbittorrent",
    ".config/qBittorrent/qBittorrent.conf",
    "your qBittorrent web UI password",
    "major",
  ],
  [
    "deluge-auth",
    ".config/deluge/auth",
    "your Deluge daemon password",
    "critical",
  ],

  [
    "jetbrains-creds",
    ".local/share/JetBrains/consentOptions",
    "your JetBrains account state",
    "major",
  ],
  [
    "idea-creds",
    ".java/.userPrefs/prefs.xml",
    "your Java preference store",
    "major",
  ],
  [
    "android-keystore",
    ".android/debug.keystore",
    "your Android signing key",
    "critical",
  ],
  ["android-adbkey", ".android/adbkey", "your ADB private key", "critical"],
  [
    "unity-license",
    ".local/share/unity3d/Unity/Unity_lic.ulf",
    "your Unity licence",
    "major",
  ],
  [
    "godot-editor",
    ".config/godot/editor_settings-4.tres",
    "your Godot editor settings",
    "major",
  ],
  [
    "openvpn-auth",
    ".config/openvpn/auth.txt",
    "your VPN password file",
    "critical",
  ],
  [
    "nordvpn",
    ".config/nordvpn/nordvpn.conf",
    "your VPN account state",
    "major",
  ],
  [
    "protonvpn",
    ".config/protonvpn/pvpn-cli.cfg",
    "your VPN credentials",
    "critical",
  ],
  [
    "mullvad",
    ".config/Mullvad VPN/settings.json",
    "your VPN account number",
    "critical",
  ],
  [
    "tailscale-state",
    ".local/share/tailscale/tailscaled.state",
    "your Tailscale node key",
    "critical",
  ],
  [
    "zerotier",
    ".config/zerotier-one/identity.secret",
    "your ZeroTier identity",
    "critical",
  ],
  [
    "wireguard-conf",
    ".config/wireguard/wg0.conf",
    "your WireGuard private key",
    "critical",
  ],
  [
    "firefox-logins",
    ".mozilla/firefox/logins.json",
    "your Firefox saved passwords",
    "critical",
  ],
  [
    "firefox-key4",
    ".mozilla/firefox/key4.db",
    "the key that decrypts your saved passwords",
    "critical",
  ],
  [
    "chrome-cookies",
    ".config/google-chrome/Default/Cookies",
    "your Chrome session cookies",
    "critical",
  ],
  [
    "chromium-cookies",
    ".config/chromium/Default/Cookies",
    "your Chromium session cookies",
    "critical",
  ],
  [
    "chrome-webdata",
    ".config/google-chrome/Default/Web Data",
    "your Chrome autofill data",
    "critical",
  ],
  [
    "thunderbird-logins",
    ".thunderbird/logins.json",
    "your mail account passwords",
    "critical",
  ],
  [
    "evolution-sources",
    ".config/evolution/sources",
    "your mail account configuration",
    "major",
  ],
  [
    "geary-config",
    ".config/geary/account_01/geary.ini",
    "your mail account configuration",
    "major",
  ],
  [
    "claws-passwd",
    ".claws-mail/passwordstorerc",
    "your Claws Mail passwords",
    "critical",
  ],
  [
    "pidgin-accounts",
    ".purple/accounts.xml",
    "your chat account passwords",
    "critical",
  ],
  [
    "hexchat-servlist",
    ".config/hexchat/servlist.conf",
    "your IRC server passwords",
    "critical",
  ],
  [
    "quassel-config",
    ".config/quassel-irc.org/quasselclient.conf",
    "your IRC client configuration",
    "major",
  ],
  [
    "gajim-config",
    ".config/gajim/config",
    "your XMPP account configuration",
    "major",
  ],
  [
    "profanity-accounts",
    ".local/share/profanity/accounts",
    "your XMPP accounts",
    "critical",
  ],
  [
    "matrix-commander",
    ".config/matrix-commander/credentials.json",
    "your Matrix access token",
    "critical",
  ],
  [
    "mautrix",
    ".config/mautrix/config.yaml",
    "your bridge credentials",
    "critical",
  ],
  [
    "cliff-notes",
    ".config/keepassxc/keepassxc.ini",
    "your password database path and settings",
    "major",
  ],
  [
    "keepass-kdbx",
    "Documents/passwords.kdbx",
    "your password database",
    "critical",
  ],
  [
    "enpass",
    ".config/Enpass/vault.enpassdb",
    "your password vault",
    "critical",
  ],
  ["lastpass-cli", ".local/share/lpass", "your LastPass session", "critical"],
  [
    "pass-otp",
    ".password-store/otp",
    "your one-time-password secrets",
    "critical",
  ],
  ["authy", ".config/Authy Desktop", "your two-factor secrets", "critical"],
  ["gauth", ".config/gauth/gauth.csv", "your two-factor secrets", "critical"],
  [
    "ledger-live",
    ".config/Ledger Live/app.json",
    "your hardware wallet accounts",
    "major",
  ],
  [
    "exodus-wallet",
    ".config/Exodus/exodus.wallet",
    "your Exodus wallet",
    "critical",
  ],
  [
    "metamask-ext",
    ".config/google-chrome/Default/Local Extension Settings",
    "your browser extension storage, including wallets",
    "critical",
  ],
  [
    "dbeaver-workspace",
    ".local/share/DBeaverData",
    "your database connections",
    "critical",
  ],
  [
    "pgadmin",
    ".pgadmin/pgadmin4.db",
    "your pgAdmin saved passwords",
    "critical",
  ],
  [
    "beekeeper",
    ".config/beekeeper-studio/app.db",
    "your database connections",
    "critical",
  ],
  [
    "tableplus",
    ".config/TablePlus/settings.json",
    "your database connections",
    "critical",
  ],
  [
    "azure-data-studio",
    ".config/azuredatastudio/User/settings.json",
    "your database connections",
    "major",
  ],
  [
    "sqlite-browser",
    ".config/sqlitebrowser/sqlitebrowser.conf",
    "your recent database files",
    "major",
  ],
  [
    "cyberduck",
    ".cyberduck/credentials",
    "your transfer credentials",
    "critical",
  ],
  ["winscp-ini", ".config/winscp.ini", "your transfer credentials", "critical"],
  [
    "lftp-bookmarks",
    ".local/share/lftp/bookmarks",
    "your FTP bookmarks and passwords",
    "critical",
  ],
  [
    "ncftp-bookmarks",
    ".ncftp/bookmarks",
    "your FTP bookmarks and passwords",
    "critical",
  ],
  [
    "thefuck-rules",
    ".config/thefuck/settings.py",
    "~/.config/thefuck/settings.py",
    "major",
  ],
  [
    "direnv-allow",
    ".local/share/direnv/allow",
    "which project scripts you have authorised to run",
    "major",
  ],
  ["asdf-tokens", ".asdfrc", "~/.asdfrc", "major"],
  [
    "mise-config",
    ".config/mise/config.toml",
    "~/.config/mise/config.toml",
    "major",
  ],

  // --- ssh and certificates ---
  ["ssh-config", ".ssh/config", "your SSH client configuration", "major"],
  ["ssh-known-hosts", ".ssh/known_hosts", "the hosts you connect to", "major"],
  [
    "ssh-authorized",
    ".ssh/authorized_keys",
    "~/.ssh/authorized_keys",
    "critical",
  ],
  [
    "ssh-agent-env",
    ".ssh/agent-env",
    "your forwarded agent socket path",
    "major",
  ],

  // --- assistants and local tooling ---
  ["claude-json", ".claude.json", "~/.claude.json", "major"],
  [
    "claude-creds",
    ".claude/.credentials.json",
    "your Claude credentials",
    "critical",
  ],
  [
    "openai-key",
    ".config/openai/auth.json",
    "your OpenAI credentials",
    "critical",
  ],
  [
    "jupyter-runtime",
    ".local/share/jupyter/runtime",
    "your live Jupyter tokens",
    "critical",
  ],
  [
    "opnsense-api",
    ".config/opnsense/api.key",
    "your firewall API key",
    "critical",
  ],
  [
    "proxmox-token",
    ".config/proxmox/token.json",
    "your Proxmox API token",
    "critical",
  ],
  [
    "vagrant-boxes",
    ".vagrant.d/data/machine-index",
    "your virtual machine inventory",
    "major",
  ],
  [
    "virtualbox-conf",
    ".config/VirtualBox/VirtualBox.xml",
    "your virtual machine inventory",
    "major",
  ],
  [
    "libvirt-auth",
    ".config/libvirt/auth.conf",
    "your hypervisor credentials",
    "critical",
  ],
  [
    "qemu-sockets",
    ".config/libvirt/libvirt.conf",
    "your hypervisor configuration",
    "major",
  ],
  [
    "distrobox",
    ".config/distrobox/distrobox.conf",
    "your container configuration",
    "major",
  ],
  [
    "toolbox",
    ".config/containers/storage.conf",
    "your container storage configuration",
    "major",
  ],
  [
    "nix-netrc",
    ".config/nix/netrc",
    "your Nix binary cache credentials",
    "critical",
  ],
  [
    "nix-conf",
    ".config/nix/nix.conf",
    "~/.config/nix/nix.conf (substituter keys)",
    "major",
  ],
  [
    "guix-channels",
    ".config/guix/channels.scm",
    "which code your package manager trusts",
    "major",
  ],
  ["sops-config", ".sops.yaml", "~/.sops.yaml", "major"],
  [
    "smbcredentials",
    ".smbcredentials",
    "~/.smbcredentials (share passwords)",
    "critical",
  ],
  ["davfs-secrets", ".davfs2/secrets", "your WebDAV passwords", "critical"],
  ["rsyncd-secrets", ".rsyncd.secrets", "your rsync passwords", "critical"],
  ["mc-ini", ".config/mc/ini", "your file-manager saved connections", "major"],
  ["ftp-netrc", ".netrc.ftp", "your FTP credentials", "critical"],
  [
    "gh-config",
    ".config/gh/config.yml",
    "your GitHub CLI configuration",
    "major",
  ],
  ["gitlab-token", ".python-gitlab.cfg", "your GitLab token", "critical"],
  ["jira-cli", ".config/.jira/.config.yml", "your Jira token", "critical"],
  ["linear-cli", ".config/linear/config.json", "your Linear token", "critical"],
  ["notion-cli", ".config/notion/config.json", "your Notion token", "critical"],
  ["stripe-cli", ".config/stripe/config.toml", "your Stripe keys", "critical"],
  [
    "twilio-cli",
    ".twilio-cli/config.json",
    "your Twilio credentials",
    "critical",
  ],
  ["sendgrid", ".sendgrid.env", "your SendGrid key", "critical"],
  [
    "cloudflare-cli",
    ".cloudflared/config.yml",
    "your Cloudflare tunnel configuration",
    "critical",
  ],
  ["vercel", ".config/vercel/auth.json", "your Vercel token", "critical"],
  ["netlify", ".config/netlify/config.json", "your Netlify token", "critical"],
  ["railway", ".railway/config.json", "your Railway token", "critical"],
  ["render-cli", ".render/config.yaml", "your Render token", "critical"],
  ["supabase", ".supabase/access-token", "your Supabase token", "critical"],
  [
    "planetscale",
    ".config/planetscale/pscale.yml",
    "your PlanetScale token",
    "critical",
  ],
  ["turso", ".config/turso/settings.json", "your Turso token", "critical"],
  ["fastly", ".fastlyctl", "your Fastly token", "critical"],
  ["akamai", ".edgerc", "~/.edgerc (Akamai credentials)", "critical"],
  ["ovh", ".ovh.conf", "your OVH credentials", "critical"],
  [
    "exoscale",
    ".config/exoscale/exoscale.toml",
    "your Exoscale credentials",
    "critical",
  ],
  ["upcloud", ".config/upctl.yaml", "your UpCloud credentials", "critical"],
  ["vultr", ".vultr-cli.yaml", "your Vultr token", "critical"],
  ["packet", ".config/equinix/metal.yaml", "your Equinix token", "critical"],
  ["ibmcloud", ".bluemix/config.json", "your IBM Cloud token", "critical"],
  [
    "alibaba",
    ".aliyun/config.json",
    "your Alibaba Cloud credentials",
    "critical",
  ],
  [
    "tencent",
    ".tccli/default.credential",
    "your Tencent Cloud credentials",
    "critical",
  ],
  [
    "yandex",
    ".config/yandex-cloud/config.yaml",
    "your Yandex Cloud token",
    "critical",
  ],
  [
    "openstack",
    ".config/openstack/clouds.yaml",
    "your OpenStack credentials",
    "critical",
  ],
  ["hetzner-k8s", ".config/hcloud/token", "your Hetzner token", "critical"],
  [
    "digitalocean-k8s",
    ".config/doctl/kubeconfig",
    "your cluster credentials",
    "critical",
  ],
  ["eksctl", ".eksctl/credentials", "your EKS credentials", "critical"],
  [
    "velero",
    ".config/velero/config.json",
    "your backup service configuration",
    "major",
  ],
  ["stern", ".config/stern/config.yaml", "your cluster configuration", "major"],
  [
    "lens",
    ".config/Lens/lens-user-store.json",
    "your cluster credentials",
    "critical",
  ],
  ["rancher", ".rancher/cli2.json", "your Rancher token", "critical"],
  ["openshift", ".kube/cache/oc", "your OpenShift session", "critical"],
  [
    "mysql-workbench2",
    ".mysql/workbench/server_instances.xml",
    "your database connections",
    "critical",
  ],
  [
    "dbvis",
    ".dbvis/config70/dbvis.xml",
    "your database connections",
    "critical",
  ],
  [
    "sqldeveloper",
    ".sqldeveloper/system/product-preferences.xml",
    "your database connections",
    "major",
  ],
  ["robomongo", ".3T/robo-3t", "your MongoDB connections", "critical"],
  ["redisinsight", ".redisinsight-app", "your Redis connections", "critical"],
  [
    "mongodb-compass",
    ".config/MongoDB Compass",
    "your MongoDB connections",
    "critical",
  ],
  ["thunderclient", ".thunder-client", "your saved API requests", "critical"],
  ["bruno", ".config/bruno", "your saved API requests", "critical"],
  ["hoppscotch", ".config/Hoppscotch", "your saved API requests", "critical"],
  ["paw", ".config/Paw", "your saved API requests", "critical"],
  [
    "charles-proxy",
    ".charles/ca",
    "your interception certificate authority",
    "critical",
  ],
  [
    "mitmproxy",
    ".mitmproxy/mitmproxy-ca.pem",
    "your interception certificate authority",
    "critical",
  ],
  [
    "burp",
    ".BurpSuite/UserConfigCommunity.json",
    "your Burp configuration",
    "critical",
  ],
  ["metasploit", ".msf4/config", "your Metasploit configuration", "critical"],
  ["sqlmap", ".local/share/sqlmap", "your scan history", "major"],
  [
    "gpg-sshcontrol",
    ".gnupg/sshcontrol",
    "which GnuPG keys act as SSH keys",
    "major",
  ],
  ["age-identity", ".age/key.txt", "your age private key", "critical"],
  [
    "minisign",
    ".minisign/minisign.key",
    "your minisign secret key",
    "critical",
  ],
  ["signify", ".signify/key.sec", "your signify secret key", "critical"],
  ["cosign", ".sigstore/cosign.key", "your signing key", "critical"],
  ["notary", ".docker/trust/private", "your content-trust keys", "critical"],
  ["ssh-ca", ".ssh/ca", "your SSH certificate authority key", "critical"],
  [
    "step-cli",
    ".step/secrets",
    "your certificate authority secrets",
    "critical",
  ],
  [
    "easyrsa",
    ".easyrsa/pki/private",
    "your certificate authority keys",
    "critical",
  ],
  [
    "certbot-account",
    ".config/letsencrypt/accounts",
    "your ACME account key",
    "critical",
  ],
  [
    "acme-sh",
    ".acme.sh/account.conf",
    "your ACME account configuration",
    "critical",
  ],
  [
    "wpa-supplicant",
    ".config/wpa_supplicant.conf",
    "your Wi-Fi passphrases",
    "critical",
  ],
  [
    "nm-conn-user",
    ".config/NetworkManager/system-connections",
    "your Wi-Fi passphrases",
    "critical",
  ],
  [
    "chrome-affiliation",
    ".config/google-chrome/Default/Affiliation Database",
    "your saved credential metadata",
    "major",
  ],
  [
    "firefox-cert9",
    ".mozilla/firefox/cert9.db",
    "your certificate store and exceptions",
    "major",
  ],
  [
    "firefox-cookies",
    ".mozilla/firefox/cookies.sqlite",
    "your session cookies",
    "critical",
  ],
  [
    "firefox-formhistory",
    ".mozilla/firefox/formhistory.sqlite",
    "everything you have typed into a form",
    "critical",
  ],
  [
    "thunderbird-key4",
    ".thunderbird/key4.db",
    "the key that decrypts your mail passwords",
    "critical",
  ],
  [
    "thunderbird-cert9",
    ".thunderbird/cert9.db",
    "your certificate store",
    "major",
  ],
  [
    "evolution-passwords",
    ".config/evolution/passwords",
    "your mail passwords",
    "critical",
  ],
  ["kwallet", ".local/share/kwalletd", "your KDE wallet", "critical"],
  ["seahorse", ".local/share/seahorse", "your key manager state", "major"],
  [
    "gnome-keyring-user",
    ".local/share/keyrings/login.keyring",
    "your login keyring",
    "critical",
  ],
  [
    "gnome-keyring-default",
    ".local/share/keyrings/default",
    "which keyring is unlocked at login",
    "major",
  ],
  ["pam-gnupg", ".pam-gnupg", "which GnuPG keys unlock at login", "major"],
  [
    "systemd-creds",
    ".config/systemd/user-credentials",
    "credentials for your user services",
    "critical",
  ],
  [
    "age-plugin",
    ".config/age-plugin-yubikey",
    "your hardware key identity",
    "critical",
  ],
  ["passage-store", ".passage/store", "your password store", "critical"],
  ["himitsu", ".local/share/himitsu", "your secret store", "critical"],
  ["secret-tool-cache", ".cache/libsecret", "cached secrets", "critical"],
  [
    "aws-sso-cache",
    ".aws/sso/cache",
    "your AWS SSO session tokens",
    "critical",
  ],
  ["aws-cli-cache", ".aws/cli/cache", "your AWS session tokens", "critical"],
  [
    "gcloud-configs",
    ".config/gcloud/configurations",
    "your gcloud project configuration",
    "major",
  ],
  [
    "azure-msal",
    ".azure/msal_token_cache.json",
    "your Azure tokens",
    "critical",
  ],
  ["kube-sa-token", ".kube/http-cache", "cached cluster responses", "major"],
  ["docker-buildx", ".docker/buildx", "your builder configuration", "major"],
  [
    "podman-auth",
    ".config/containers/registries.conf",
    "your registry configuration",
    "major",
  ],
  ["crc-config", ".crc/machines", "your local cluster state", "major"],
  [
    "minikube-profiles",
    ".minikube/profiles",
    "your cluster certificates and keys",
    "critical",
  ],
  ["kind-config", ".kube/kind-config", "your cluster credentials", "critical"],
  ["k3d-config", ".config/k3d", "your cluster configuration", "major"],
  ["colima-config", ".colima", "your VM configuration", "major"],
  ["multipass-data", ".local/share/multipass", "your VM instances", "major"],
  ["incus-config", ".config/incus", "your container credentials", "critical"],
  ["lxc-config", ".config/lxc", "your container credentials", "critical"],
  ["borg-keys", ".config/borg/keys", "your backup encryption keys", "critical"],
  [
    "borg-security",
    ".config/borg/security",
    "your backup repository state",
    "major",
  ],
  [
    "restic-repo",
    ".config/restic/repo",
    "your backup repository location",
    "major",
  ],
  [
    "kopia-config",
    ".config/kopia/repository.config",
    "your backup repository credentials",
    "critical",
  ],
  [
    "duplicacy-prefs",
    ".duplicacy/preferences",
    "your backup credentials",
    "critical",
  ],
  ["rclone-cache", ".cache/rclone", "cached remote metadata", "major"],
  [
    "syncthing-cert",
    ".config/syncthing/cert.pem",
    "your Syncthing device certificate",
    "critical",
  ],
  ["resilio-sync", ".config/Resilio Sync", "your sync identity", "critical"],
  ["seafile-data", ".ccnet", "your Seafile account", "critical"],
  [
    "owncloud-cfg",
    ".config/ownCloud/owncloud.cfg",
    "your ownCloud account",
    "major",
  ],
  [
    "mega-cache",
    ".local/share/data/Mega Limited",
    "your MEGA session",
    "critical",
  ],
  ["pcloud-data", ".pcloud", "your pCloud session", "critical"],
  [
    "protonmail-bridge",
    ".config/protonmail/bridge",
    "your mail bridge credentials",
    "critical",
  ],
  [
    "tutanota-data",
    ".config/tutanota-desktop",
    "your mail session",
    "critical",
  ],
  ["bitwarden-data", ".config/Bitwarden", "your vault session", "critical"],
  ["keeper-config", ".config/Keeper", "your vault session", "critical"],
  ["dashlane-data", ".config/Dashlane", "your vault session", "critical"],
  ["psono-data", ".config/psono", "your vault session", "critical"],
  ["padloc-data", ".config/padloc", "your vault session", "critical"],
  [
    "aegis-export",
    "Documents/aegis-export.json",
    "an exported two-factor database",
    "critical",
  ],
  [
    "andotp-backup",
    "Documents/andotp_backup.json",
    "an exported two-factor database",
    "critical",
  ],
  [
    "freeotp-backup",
    "Documents/freeotp-backup.json",
    "an exported two-factor database",
    "critical",
  ],
  [
    "recovery-codes",
    "Documents/recovery-codes.txt",
    "your account recovery codes",
    "critical",
  ],
  ["seed-phrase", "Documents/seed.txt", "a wallet recovery phrase", "critical"],
  ["wallet-dat", "Documents/wallet.dat", "a cryptocurrency wallet", "critical"],
  [
    "id-scan",
    "Documents/passport.pdf",
    "a scan of an identity document",
    "critical",
  ],
  ["tax-return", "Documents/tax", "your tax documents", "major"],
  ["payslips", "Documents/payslips", "your payslips", "major"],
  [
    "ssh-config-d",
    ".ssh/config.d",
    "your SSH client configuration fragments",
    "major",
  ],
  [
    "ssh-authorized2",
    ".ssh/authorized_keys2",
    "a second authorised-keys file",
    "critical",
  ],
  [
    "ssh-environment",
    ".ssh/environment",
    "variables applied to every SSH login",
    "critical",
  ],
  ["ssh-rc", ".ssh/rc", "a script run on every SSH login", "critical"],
  [
    "gpg-agent-extra",
    ".gnupg/S.gpg-agent.extra",
    "your forwarded GnuPG agent socket",
    "critical",
  ],
  [
    "gpg-scdaemon",
    ".gnupg/scdaemon.conf",
    "your smartcard configuration",
    "major",
  ],
  [
    "gpg-dirmngr",
    ".gnupg/dirmngr.conf",
    "your keyserver configuration",
    "major",
  ],
  [
    "pass-extensions-dir",
    ".password-store-extensions",
    "code your password manager runs",
    "critical",
  ],
  [
    "bash-logout-file",
    ".bash_logout",
    "a script run when your shell exits",
    "critical",
  ],
  [
    "xinitrc-d",
    ".xinitrc.d",
    "scripts run when your session starts",
    "critical",
  ],
  ["profile-d-user", ".profile.d", "scripts run when you log in", "critical"],
  [
    "systemd-user-env",
    ".config/environment.d",
    "variables applied to your whole session",
    "critical",
  ],
  ["dbus-session", ".dbus/session-bus", "your session bus addresses", "major"],
  [
    "gtk-modules",
    ".config/gtk-3.0/settings.ini",
    "modules loaded into every GTK program",
    "critical",
  ],
  [
    "qt-conf",
    ".config/qt5ct/qt5ct.conf",
    "modules loaded into every Qt program",
    "major",
  ],
  [
    "kdewallet",
    ".local/share/kwalletd/kdewallet.kwl",
    "your KDE wallet",
    "critical",
  ],
  [
    "pass-otp-dir",
    ".password-store/.gpg-id-otp",
    "your one-time-password store metadata",
    "major",
  ],
  [
    "gpg-secring",
    ".gnupg/secring.gpg",
    "your legacy GnuPG secret keyring",
    "critical",
  ],
  ["ssh-id-ecdsa", ".ssh/id_ecdsa", "your SSH private key", "critical"],
  ["ssh-id-ed25519", ".ssh/id_ed25519", "your SSH private key", "critical"],
  ["ssh-id-rsa", ".ssh/id_rsa", "your SSH private key", "critical"],
  ["ssh-id-dsa", ".ssh/id_dsa", "your SSH private key", "critical"],
  [
    "ssh-sk",
    ".ssh/id_ed25519_sk",
    "your hardware-backed SSH key handle",
    "critical",
  ],
  ["mosh-key", ".mosh", "your mosh session keys", "critical"],
  ["autossh-conf", ".autossh", "your persistent tunnel configuration", "major"],
  ["sshuttle-conf", ".sshuttle", "your tunnel configuration", "major"],
  [
    "stunnel-conf",
    ".config/stunnel/stunnel.conf",
    "your TLS tunnel keys",
    "critical",
  ],
  ["socat-scripts", ".config/socat", "your relay configuration", "major"],
  [
    "wireguard-key",
    ".config/wireguard/privatekey",
    "your WireGuard private key",
    "critical",
  ],
  ["tinc-keys", ".tinc", "your mesh VPN keys", "critical"],
  ["i2p-keys", ".i2p", "your I2P identity", "critical"],
  ["tor-data", ".tor", "your Tor state", "critical"],
  ["monero-keys", ".bitmonero/wallets", "your Monero wallet keys", "critical"],
  ["zcash-wallet", ".zcash/wallet.dat", "your Zcash wallet", "critical"],
  [
    "litecoin-wallet",
    ".litecoin/wallet.dat",
    "your Litecoin wallet",
    "critical",
  ],
  [
    "dogecoin-wallet",
    ".dogecoin/wallet.dat",
    "your Dogecoin wallet",
    "critical",
  ],
  ["cardano-keys", ".cardano", "your Cardano keys", "critical"],
  ["polkadot-keys", ".local/share/polkadot", "your Polkadot keys", "critical"],
  ["near-creds", ".near-credentials", "your NEAR keys", "critical"],
  ["aptos-config", ".aptos/config.yaml", "your Aptos keys", "critical"],
  ["sui-config", ".sui/sui_config", "your Sui keys", "critical"],
  [
    "foundry-keystore",
    ".foundry/keystores",
    "your Ethereum keystores",
    "critical",
  ],
  [
    "hardhat-vars",
    ".config/hardhat-nodejs",
    "your deployment keys",
    "critical",
  ],
  [
    "truffle-config",
    ".config/truffle",
    "your deployment configuration",
    "major",
  ],
  [
    "brownie-accounts",
    ".brownie/accounts",
    "your Ethereum accounts",
    "critical",
  ],
  ["web3-keystore", ".ethereum/keystore", "your Ethereum keystore", "critical"],
  [
    "gnucash-data",
    "Documents/accounts.gnucash",
    "your financial records",
    "critical",
  ],
  [
    "kmymoney-data",
    "Documents/finance.kmy",
    "your financial records",
    "critical",
  ],
  [
    "homebank-data",
    "Documents/finance.xhb",
    "your financial records",
    "critical",
  ],
  ["medical-docs", "Documents/medical", "your medical documents", "critical"],
  ["contracts-docs", "Documents/contracts", "your contracts", "major"],
  ["bank-statements", "Documents/bank", "your bank statements", "critical"],
  [
    "insurance-docs",
    "Documents/insurance",
    "your insurance documents",
    "major",
  ],
  [
    "private-notes",
    "Documents/private",
    "documents you have marked private",
    "major",
  ],
  ["obsidian-vault", "Documents/Obsidian", "your notes", "major"],
  [
    "joplin-data",
    ".config/joplin-desktop",
    "your notes and their sync credentials",
    "critical",
  ],
  ["standardnotes", ".config/Standard Notes", "your notes session", "critical"],
  ["logseq-graph", ".logseq", "your notes", "major"],
  ["zotero-data", "Zotero", "your research library", "major"],
  [
    "signal-key",
    ".config/Signal/config.json",
    "the key that decrypts your Signal database",
    "critical",
  ],
  [
    "element-pickle",
    ".config/Element/config.json",
    "your Element session configuration",
    "critical",
  ],
];
