// What the machine remembers about you, and what it tells anyone else.
//
// Note what is NOT here: `remove-old-temp-files` and `remove-old-trash-files`
// look like privacy wins, and they are — but switching them on tells the
// desktop to start deleting your files on a timer. Those live in `manual.ts`,
// reported and explained, never applied by a button.
import type { SettingPolicy } from "../../type/policy.ts";
import {
  LOCATION,
  MINT_MENU_APPS,
  MINT_MENU_RECENT,
  MINT_REPORT,
  PRIVACY,
  SEARCH_PROVIDERS,
  THUMB_CACHE,
} from "./schemas.ts";

export const PRIVACY_POLICIES: SettingPolicy[] = [
  {
    id: "usage-stats",
    title: "Software usage statistics are sent",
    category: "privacy",
    severity: "minor",
    weight: 46,
    schemas: PRIVACY,
    key: "send-software-usage-stats",
    bad: "true",
    safe: "false",
    detail: "which applications you run is reported upstream",
    because: "Nothing on this machine needs the telemetry to work.",
  },
  {
    id: "problem-reports",
    title: "Technical problem reports are sent automatically",
    category: "privacy",
    severity: "minor",
    weight: 45,
    schemas: PRIVACY,
    key: "report-technical-problems",
    bad: "true",
    safe: "false",
    detail: "crash reports leave the machine without being shown to you",
    because: "You can still send a report by hand when you want to.",
  },
  {
    id: "remember-app-usage",
    title: "Application usage history is recorded",
    category: "privacy",
    severity: "minor",
    weight: 40,
    schemas: PRIVACY,
    key: "remember-app-usage",
    bad: "true",
    safe: "false",
    detail: "how often and how long you use each program is logged",
    because: "Only 'frequently used' lists rely on it.",
  },
  {
    id: "remember-recent-files",
    title: "Every file you open is added to a recent list",
    category: "privacy",
    severity: "minor",
    weight: 39,
    schemas: PRIVACY,
    key: "remember-recent-files",
    bad: "true",
    safe: "false",
    detail: "file names you have opened are readable by anything you run",
    because: "The existing list is kept; nothing new is added to it.",
  },
  {
    id: "recent-files-forever",
    title: "The recent-files list is kept forever",
    category: "privacy",
    severity: "minor",
    weight: 38,
    schemas: PRIVACY,
    key: "recent-files-max-age",
    bad: "=-1",
    safe: "30",
    detail: "every file you have ever opened stays listed (-1 = forever)",
    because:
      "Entries older than 30 days stop being listed. The files themselves " +
      "are never touched.",
  },
  {
    id: "recent-files-long",
    title: "The recent-files list is kept for a long time",
    category: "privacy",
    severity: "minor",
    weight: 20,
    schemas: PRIVACY,
    key: "recent-files-max-age",
    bad: ">90",
    safe: "30",
    detail: "months of file history are retained",
    because: "Thirty days covers 'what was I working on'. Files are untouched.",
  },
  {
    id: "old-files-age",
    title: "Trash and temporary files are kept for a long time",
    category: "privacy",
    severity: "minor",
    weight: 19,
    schemas: PRIVACY,
    key: "old-files-age",
    bad: ">30",
    safe: "30",
    detail: "deleted files linger longer than a month before being purged",
    because:
      "This only sets the age threshold. Automatic purging itself stays " +
      "however you have it — this app never switches deletion on.",
  },
  {
    id: "hide-identity",
    title: "Your identity is shared with applications",
    category: "privacy",
    severity: "minor",
    weight: 30,
    schemas: PRIVACY,
    key: "hide-identity",
    bad: "false",
    safe: "true",
    detail: "your real name is handed to programs that ask the desktop for it",
    because: "Applications that genuinely need a name will ask you for one.",
  },
  {
    id: "full-name-top-bar",
    title: "Your full name is shown in the top bar",
    category: "privacy",
    severity: "minor",
    weight: 15,
    schemas: PRIVACY,
    key: "show-full-name-in-top-bar",
    bad: "true",
    safe: "false",
    detail: "your name is on screen in every screenshot and screen share",
    because: "The account is unchanged; only the label goes.",
  },
  {
    id: "location-services",
    title: "Location services are enabled",
    category: "privacy",
    severity: "minor",
    weight: 37,
    schemas: LOCATION,
    key: "enabled",
    bad: "true",
    safe: "false",
    detail: "applications may ask the system where this machine is",
    because:
      "Turn it back on with Undo if a map or weather app stops locating you.",
  },
  {
    id: "external-search",
    title: "Desktop search sends queries to external providers",
    category: "privacy",
    severity: "major",
    weight: 61,
    schemas: SEARCH_PROVIDERS,
    key: "disable-external",
    bad: "false",
    safe: "true",
    detail: "what you type into the desktop search box can leave the machine",
    because: "Local results — files, applications, settings — are unaffected.",
  },
  {
    id: "menu-internet-search",
    title: "The application menu searches the internet as you type",
    category: "privacy",
    severity: "minor",
    weight: 43,
    schemas: MINT_MENU_APPS,
    key: "enable-internet-search",
    bad: "true",
    safe: "false",
    detail: "keystrokes in the menu are sent to a search engine",
    because: "The menu still searches your applications and files.",
  },
  {
    id: "menu-remember-filter",
    title: "The application menu remembers your last search",
    category: "privacy",
    severity: "minor",
    weight: 12,
    schemas: MINT_MENU_APPS,
    key: "remember-filter",
    bad: "true",
    safe: "false",
    detail: "your last query is on screen the next time you open the menu",
    because: "The menu opens empty instead, which is also faster to use.",
  },
  {
    id: "menu-recent-docs",
    title: "The menu lists a long trail of recent documents",
    category: "privacy",
    severity: "minor",
    weight: 14,
    schemas: MINT_MENU_RECENT,
    key: "num-recent-docs",
    bad: ">10",
    safe: "5",
    detail: "recent file names are on display every time the menu opens",
    because: "The list is shortened, not cleared; nothing is deleted.",
  },
  {
    id: "mint-report-automonitor",
    title: "The system report tool monitors continuously",
    category: "privacy",
    severity: "minor",
    weight: 17,
    schemas: MINT_REPORT,
    key: "automonitor",
    bad: "true",
    safe: "false",
    detail: "a background task inspects the system on a timer",
    because: "The report tool still runs on demand when you open it.",
  },
  {
    id: "temp-files-kept",
    title: "Temporary files are never cleared out",
    category: "privacy",
    severity: "minor",
    weight: 11,
    schemas: PRIVACY,
    key: "remove-old-temp-files",
    bad: "false",
    safe: "true",
    detail: "working copies of documents accumulate indefinitely",
    because: "",
    advisory:
      "No automatic fix. Switching this on tells the desktop to start " +
      "deleting files on a timer, and this app does not turn on deletion of " +
      "your files on your behalf. Enable it yourself in Privacy settings.",
  },
  {
    id: "trash-files-kept",
    title: "The trash is never emptied automatically",
    category: "privacy",
    severity: "minor",
    weight: 10,
    schemas: PRIVACY,
    key: "remove-old-trash-files",
    bad: "false",
    safe: "true",
    detail: "deleted files stay recoverable — and readable — indefinitely",
    because: "",
    advisory:
      "No automatic fix. This is a switch that begins deleting your files " +
      "on a timer. Whether the trash should empty itself is your call, not " +
      "this app's — the setting is in Privacy settings.",
  },
  {
    id: "thumbnail-cache-age",
    title: "Image thumbnails are cached for a long time",
    category: "privacy",
    severity: "minor",
    weight: 21,
    schemas: THUMB_CACHE,
    key: "maximum-age",
    bad: ">180",
    safe: "90",
    detail:
      "small copies of images you have viewed persist long after the originals",
    because:
      "Only the cache lifetime changes. This app does not delete the cache; " +
      "the desktop retires entries on its own schedule.",
  },
  {
    id: "thumbnail-cache-size",
    title: "The thumbnail cache is allowed to grow very large",
    category: "resource",
    severity: "minor",
    weight: 13,
    schemas: THUMB_CACHE,
    key: "maximum-size",
    bad: ">512",
    safe: "256",
    detail: "the cache ceiling is set well above what a desktop needs",
    because: "Lowering the ceiling changes what is kept from now on.",
  },
];
