// Session, power and notification behaviour — the settings that decide how
// much of your work is on screen, and for how long.
import type { SettingPolicy } from "../../type/policy.ts";
import {
  HOUSEKEEPING,
  INTERFACE,
  MINT_UPDATES,
  NOTIFY,
  POWER,
  SOUND,
} from "./schemas.ts";

export const SESSION_POLICIES: SettingPolicy[] = [
  {
    id: "sleep-inactive-ac",
    title: "The machine never suspends on mains power",
    category: "resource",
    severity: "minor",
    weight: 36,
    schemas: POWER,
    key: "sleep-inactive-ac-timeout",
    bad: "=0",
    safe: "3600",
    detail: "an idle desktop draws full power indefinitely",
    because:
      "One hour of genuine idle. Undo if the machine must stay reachable " +
      "overnight.",
    advisory:
      "No automatic fix. `0` here means *never suspend*, and that is a setting people choose deliberately \u2014 for long builds, downloads, servers, or a machine that must stay reachable. This app will not overrule a choice you made. Change it in Power settings if you want a timeout.",
  },
  {
    id: "sleep-display-ac",
    title: "The display never sleeps on mains power",
    category: "resource",
    severity: "minor",
    weight: 32,
    schemas: POWER,
    key: "sleep-display-ac",
    bad: "=0",
    safe: "900",
    detail: "the panel stays lit whether or not anyone is at the desk",
    because:
      "Fifteen minutes. The session is untouched; only the panel sleeps.",
    advisory:
      "No automatic fix. `0` means *never blank the display*, which is a deliberate choice for presentations, monitoring screens and machines you watch from across the room. Change it in Power settings if you want a timeout.",
  },
  {
    id: "sleep-display-long",
    title: "The display stays lit for a very long time",
    category: "resource",
    severity: "minor",
    weight: 9,
    schemas: POWER,
    key: "sleep-display-ac",
    bad: ">1800",
    safe: "900",
    detail: "the panel runs for over half an hour of idle",
    because: "Fifteen minutes. Moving the mouse brings it straight back.",
    advisory:
      "No automatic fix. This is a timeout you chose. Shortening it is a preference, not a correction \u2014 change it in Power settings if it is longer than you meant.",
  },
  {
    id: "idle-dim-ac",
    title: "The screen does not dim when idle",
    category: "resource",
    severity: "minor",
    weight: 8,
    schemas: POWER,
    key: "idle-dim-ac",
    bad: "false",
    safe: "true",
    detail: "full brightness is held even when the machine is unattended",
    because: "Dimming is instantly reversed by any input.",
    advisory:
      "No automatic fix. Whether the screen dims when you step away is a preference, not a fault. Change it in Power settings.",
  },
  {
    id: "critical-battery-late",
    title: "The critical battery threshold is very low",
    category: "resource",
    severity: "major",
    weight: 57,
    schemas: POWER,
    key: "percentage-critical",
    bad: "<5",
    safe: "5",
    detail: "the machine acts on a flat battery with almost no margin",
    because: "Five percent leaves room to save work before the machine acts. " +
      "Nothing is shut down by this change.",
  },
  {
    id: "low-battery-late",
    title: "The low-battery warning comes very late",
    category: "resource",
    severity: "minor",
    weight: 29,
    schemas: POWER,
    key: "percentage-low",
    bad: "<10",
    safe: "15",
    detail: "you are warned with too little charge left to act on it",
    because: "Warning at 15% gives time to find a charger.",
  },
  {
    id: "housekeeping-threshold",
    title: "The low-disk warning triggers too late",
    category: "resource",
    severity: "minor",
    weight: 35,
    schemas: HOUSEKEEPING,
    key: "free-size-gb-no-notify",
    bad: "<2",
    safe: "2",
    detail: "the desktop stays quiet until under a gigabyte is left",
    because: "Warning at 2 GB leaves room to act. Nothing is deleted by this " +
      "setting — it only decides when you are told.",
  },
  {
    id: "notification-timeout",
    title: "Notifications stay on screen for a long time",
    category: "privacy",
    severity: "minor",
    weight: 7,
    schemas: NOTIFY,
    key: "notification-duration",
    bad: ">10",
    safe: "4",
    detail: "message content lingers on screen after you have walked away",
    because: "Four seconds. Nothing is dropped — the tray still holds them.",
  },
  {
    id: "notifications-fullscreen",
    title: "Notifications interrupt full-screen applications",
    category: "privacy",
    severity: "minor",
    weight: 6,
    schemas: NOTIFY,
    key: "fullscreen-notifications",
    bad: "true",
    safe: "false",
    detail: "message previews appear over presentations and screen shares",
    because: "They wait in the tray instead of appearing on the projector.",
  },
  {
    id: "update-notifications-off",
    title: "Update notifications are switched off",
    category: "settings",
    severity: "major",
    weight: 62,
    schemas: MINT_UPDATES,
    key: "tracker-disable-notifications",
    bad: "true",
    safe: "false",
    detail: "you are never told that security updates are waiting",
    because:
      "Restores the reminder. It notifies; it does not install anything.",
  },
  {
    id: "update-grace-period",
    title: "Update reminders are deferred for a long time",
    category: "settings",
    severity: "minor",
    weight: 31,
    schemas: MINT_UPDATES,
    key: "tracker-grace-period",
    bad: ">30",
    safe: "15",
    detail: "an update can sit unmentioned for over a month",
    because: "Fifteen days. Nothing is installed by this change.",
  },
  {
    id: "event-sounds",
    title: "The desktop plays a sound for interface events",
    category: "performance",
    severity: "minor",
    weight: 3,
    schemas: SOUND,
    key: "event-sounds",
    bad: "true",
    safe: "false",
    detail: "every dialog and error wakes the audio stack",
    because: "Alerts and media are unaffected; only UI clicks go quiet.",
  },
  {
    id: "clock-seconds",
    title: "The clock updates every second",
    category: "performance",
    severity: "minor",
    weight: 2,
    schemas: INTERFACE,
    key: "clock-show-seconds",
    bad: "true",
    safe: "false",
    detail: "the panel repaints once a second, all day",
    because: "The clock stays; it repaints once a minute instead.",
  },
];
