// SSH client baseline. Every row here is something a compromised or hostile
// server can otherwise reach back through, or a habit that leaks who you
// connect to.
import type { SshPolicy } from "../../type/policy.ts";

type Row = [
  id: string,
  key: string,
  bad: SshPolicy["bad"],
  safe: string,
  severity: SshPolicy["severity"],
  weight: number,
  title: string,
  detail: string,
  because: string,
];

const AUTO: Row[] = [
  [
    "agent-forward",
    "ForwardAgent",
    "true",
    "no",
    "critical",
    98,
    "SSH agent forwarding is on by default",
    "root on any server you reach can use your private keys as you, for as long as you are connected",
    "Agent forwarding stays available per-host when you actually need it.",
  ],
  [
    "x11-forward",
    "ForwardX11",
    "true",
    "no",
    "critical",
    97,
    "X11 forwarding is on by default",
    "a hostile server can read your keystrokes and screen through the X connection",
    "Turn it on per-host for the few servers whose GUI you actually run.",
  ],
  [
    "x11-trusted",
    "ForwardX11Trusted",
    "true",
    "no",
    "major",
    86,
    "Forwarded X11 clients are treated as trusted",
    "the X security extension is bypassed, so a forwarded app has full access to your display",
    "Untrusted forwarding still works; it is just sandboxed.",
  ],
  [
    "permit-local-command",
    "PermitLocalCommand",
    "true",
    "no",
    "critical",
    96,
    "SSH may run local commands from configuration",
    "a LocalCommand line — including one from an included config — executes on your machine",
    "Nothing in normal use needs it.",
  ],
  [
    "hash-known-hosts",
    "HashKnownHosts",
    "false",
    "yes",
    "major",
    84,
    "known_hosts records every host you connect to in clear text",
    "anything that can read the file gets your entire server inventory",
    "New entries are hashed. Existing ones are left exactly as they are — nothing is rewritten or lost.",
  ],
  [
    "identities-only",
    "IdentitiesOnly",
    "false",
    "yes",
    "major",
    81,
    "SSH offers every key in your agent to every server",
    "each server you touch learns the public half of all your keys, which fingerprints you across providers",
    "ssh uses the key configured for the host instead of trying them all — which also fixes 'too many authentication failures'.",
  ],
  [
    "gssapi-auth",
    "GSSAPIAuthentication",
    "true",
    "no",
    "minor",
    53,
    "Kerberos authentication is attempted on every connection",
    "a needless round-trip that announces your principal to servers that never asked",
    "Only relevant on a Kerberos realm; turn it back on per-host there.",
  ],
  [
    "gssapi-delegate",
    "GSSAPIDelegateCredentials",
    "true",
    "no",
    "major",
    78,
    "Kerberos credentials are delegated to the server",
    "the server can act as you against other Kerberos services",
    "Delegation stays available per-host where it is genuinely needed.",
  ],
  [
    "strict-host-key",
    "StrictHostKeyChecking",
    "~no",
    "ask",
    "critical",
    95,
    "SSH accepts unknown and changed host keys without asking",
    "`StrictHostKeyChecking no` means a machine-in-the-middle looks exactly like a normal connection",
    "You are asked once per new host, which is the behaviour ssh ships with.",
  ],
  [
    "accept-new-host-key",
    "StrictHostKeyChecking",
    "~accept-new",
    "ask",
    "major",
    89,
    "SSH trusts a new host key on sight",
    "`accept-new` skips the one moment you get to compare a fingerprint — the first connection is exactly when an impostor is cheapest",
    "You are asked once per new host. Changed keys were already refused either way.",
  ],
  [
    "update-host-keys",
    "UpdateHostKeys",
    "false",
    "yes",
    "minor",
    48,
    "Host key rotation is not picked up",
    "servers that rotate keys correctly still produce a scary mismatch warning",
    "ssh learns additional host keys over an already-verified connection — the safe half of rotation.",
  ],
  [
    "exit-on-forward-failure",
    "ExitOnForwardFailure",
    "false",
    "yes",
    "minor",
    46,
    "A failed port forward is ignored",
    "you get a shell that looks fine while the tunnel you needed silently is not there",
    "The connection fails loudly instead of half-working.",
  ],
  [
    "server-alive",
    "ServerAliveInterval",
    "=0",
    "60",
    "minor",
    44,
    "Dead SSH sessions are never noticed",
    "a dropped link leaves a frozen terminal until you kill it by hand",
    "ssh sends a keepalive every 60 seconds and gives up after three. It does not keep idle sessions open against a server that wants them closed.",
  ],
  [
    "tunnel-off",
    "Tunnel",
    "~yes",
    "no",
    "major",
    79,
    "SSH sets up a network tunnel device by default",
    "every connection tries to build a tun/tap interface into the remote network",
    "Tunnels stay available per-host where you configure them.",
  ],
];

const ADVISORY: [
  id: string,
  key: string,
  bad: SshPolicy["bad"],
  severity: SshPolicy["severity"],
  weight: number,
  title: string,
  detail: string,
  why: string,
][] = [
  [
    "weak-macs",
    "MACs",
    "~hmac-sha1",
    "major",
    62,
    "SSH still offers SHA-1 message authentication",
    "a downgrade to a deprecated MAC is available to any server that asks for it",
    "No automatic fix: pinning an algorithm list can lock you out of an older server you still need. Add a `MACs` line to a `Host *` block yourself once you know what you connect to — `hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com` is the usual modern set.",
  ],
  [
    "weak-ciphers",
    "Ciphers",
    "~cbc",
    "major",
    61,
    "SSH still offers CBC-mode ciphers",
    "CBC modes have a long history of padding-oracle problems in SSH",
    "No automatic fix: pinning a cipher list can lock you out of an older server. Set `Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com` yourself when you are sure of your fleet.",
  ],
  [
    "weak-kex",
    "KexAlgorithms",
    "~sha1",
    "major",
    60,
    "SSH still offers SHA-1 key exchange",
    "SHA-1 based key exchange is deprecated and removable",
    "No automatic fix: an old server that only speaks these becomes unreachable. Pin `KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org` yourself when your fleet allows it.",
  ],
  [
    "password-auth",
    "PasswordAuthentication",
    "true",
    "minor",
    36,
    "SSH will fall back to password authentication",
    "a password prompt is phishable by a machine-in-the-middle in a way a key is not",
    "No automatic fix: switching this off locks you out of any server where you have not installed a key yet. Do it per-host as you finish setting keys up.",
  ],
];

export const SSH_POLICIES: SshPolicy[] = [
  ...AUTO.map(
    (
      [id, key, bad, safe, severity, weight, title, detail, because],
    ): SshPolicy => ({
      id: `ssh-${id}`,
      title,
      category: "security",
      severity,
      weight,
      key,
      bad,
      safe,
      detail,
      because,
    }),
  ),
  ...ADVISORY.map(
    ([id, key, bad, severity, weight, title, detail, why]): SshPolicy => ({
      id: `ssh-${id}`,
      title,
      category: "security",
      severity,
      weight,
      key,
      bad,
      safe: "",
      detail,
      because: "",
      advisory: why,
    }),
  ),
];
