// Kernel parameters. Reported only — every one of these needs root to change,
// and several change how the network stack treats live connections. This is
// the one family where "absolutely impossible to auto-fix" is literally true
// for an app running as your user.
import type { SysctlPolicy } from "../../type/policy.ts";

const row = (
  id: string,
  key: string,
  safe: string,
  bad: SysctlPolicy["bad"],
  severity: SysctlPolicy["severity"],
  weight: number,
  title: string,
  detail: string,
): SysctlPolicy => ({
  id: `sysctl-${id}`,
  title,
  category: "security",
  severity,
  weight,
  key,
  bad,
  safe,
  detail,
});

export const SYSCTL_POLICIES: SysctlPolicy[] = [
  row(
    "dmesg",
    "kernel.dmesg_restrict",
    "1",
    "=0",
    "major",
    69,
    "Any user can read the kernel log",
    "kernel addresses and device details are readable by every account",
  ),
  row(
    "kptr",
    "kernel.kptr_restrict",
    "1",
    "=0",
    "major",
    68,
    "Kernel pointers are exposed to unprivileged users",
    "/proc leaks kernel addresses, which defeats address-space randomisation",
  ),
  row(
    "ptrace",
    "kernel.yama.ptrace_scope",
    "1",
    "=0",
    "major",
    77,
    "Any process may attach a debugger to any other",
    "one compromised program can read secrets out of every other one you run",
  ),
  row(
    "sysrq",
    "kernel.sysrq",
    "0",
    ">1",
    "minor",
    43,
    "The magic SysRq key is fully enabled",
    "a keyboard combination at the console can kill processes or reboot",
  ),
  row(
    "unprivileged-bpf",
    "kernel.unprivileged_bpf_disabled",
    "1",
    "=0",
    "major",
    75,
    "Unprivileged users may load BPF programs",
    "a large kernel attack surface is reachable without root",
  ),
  row(
    "perf-event",
    "kernel.perf_event_paranoid",
    "2",
    "<2",
    "minor",
    49,
    "Performance counters are open to unprivileged users",
    "hardware counters have been used to observe other processes' work",
  ),
  row(
    "userns",
    "kernel.unprivileged_userns_clone",
    "0",
    "=1",
    "minor",
    51,
    "Unprivileged user namespaces are allowed",
    "a common first step in local privilege-escalation chains",
  ),
  row(
    "protected-hardlinks",
    "fs.protected_hardlinks",
    "1",
    "=0",
    "major",
    63,
    "Hardlink protection is off",
    "a shared directory can be used to trick a privileged program",
  ),
  row(
    "protected-symlinks",
    "fs.protected_symlinks",
    "1",
    "=0",
    "major",
    63,
    "Symlink protection is off",
    "the classic /tmp symlink attack is not blocked",
  ),
  row(
    "protected-fifos",
    "fs.protected_fifos",
    "2",
    "<2",
    "minor",
    50,
    "FIFO protection is not fully on",
    "a FIFO planted in a shared directory can be opened by a victim program",
  ),
  row(
    "protected-regular",
    "fs.protected_regular",
    "2",
    "<2",
    "minor",
    50,
    "Regular-file protection is not fully on",
    "a planted file in a shared directory can be opened by a victim program",
  ),
  row(
    "suid-dumpable",
    "fs.suid_dumpable",
    "0",
    ">0",
    "major",
    60,
    "Privileged programs may write core dumps",
    "a crash can leave secrets from a privileged process on disk",
  ),
  row(
    "rp-filter",
    "net.ipv4.conf.all.rp_filter",
    "1",
    "=0",
    "minor",
    56,
    "Reverse-path filtering is off",
    "spoofed source addresses are accepted on this interface",
  ),
  row(
    "accept-redirects",
    "net.ipv4.conf.all.accept_redirects",
    "0",
    "=1",
    "major",
    59,
    "ICMP redirects are accepted",
    "another host on the network can reroute your traffic through itself",
  ),
  row(
    "secure-redirects",
    "net.ipv4.conf.all.secure_redirects",
    "0",
    "=1",
    "minor",
    45,
    "ICMP redirects from gateways are accepted",
    "a compromised gateway can silently reroute your traffic",
  ),
  row(
    "send-redirects",
    "net.ipv4.conf.all.send_redirects",
    "0",
    "=1",
    "minor",
    44,
    "This machine sends ICMP redirects",
    "a desktop is not a router and has no reason to advertise routes",
  ),
  row(
    "source-route",
    "net.ipv4.conf.all.accept_source_route",
    "0",
    "=1",
    "major",
    58,
    "Source-routed packets are accepted",
    "a sender can dictate the path its packets take to reach you",
  ),
  row(
    "ipv6-ra",
    "net.ipv6.conf.all.accept_ra",
    "0",
    "=1",
    "minor",
    42,
    "IPv6 router advertisements are accepted",
    "anything on the local network can advertise itself as your router",
  ),
  row(
    "ipv6-redirects",
    "net.ipv6.conf.all.accept_redirects",
    "0",
    "=1",
    "minor",
    41,
    "IPv6 ICMP redirects are accepted",
    "the IPv6 half of the redirect problem above",
  ),
  row(
    "tcp-syncookies",
    "net.ipv4.tcp_syncookies",
    "1",
    "=0",
    "minor",
    40,
    "TCP SYN cookies are off",
    "the standard cheap defence against connection-table exhaustion is absent",
  ),
  row(
    "log-martians",
    "net.ipv4.conf.all.log_martians",
    "1",
    "=0",
    "minor",
    30,
    "Impossible packets are dropped without a trace",
    "spoofed traffic leaves no record to notice",
  ),
  row(
    "icmp-broadcast",
    "net.ipv4.icmp_echo_ignore_broadcasts",
    "1",
    "=0",
    "minor",
    39,
    "This machine answers broadcast pings",
    "it can be used to amplify traffic at someone else",
  ),
  row(
    "ip-forward",
    "net.ipv4.ip_forward",
    "0",
    "=1",
    "major",
    64,
    "This machine routes packets between networks",
    "a workstation acting as a router can bridge a hostile network into a trusted one",
  ),
  row(
    "ipv6-forward",
    "net.ipv6.conf.all.forwarding",
    "0",
    "=1",
    "major",
    64,
    "This machine routes IPv6 packets between networks",
    "the IPv6 half of the routing problem above",
  ),
  row(
    "default-rp-filter",
    "net.ipv4.conf.default.rp_filter",
    "1",
    "=0",
    "minor",
    55,
    "New interfaces come up without reverse-path filtering",
    "a network you join later accepts spoofed source addresses",
  ),
  row(
    "default-accept-redirects",
    "net.ipv4.conf.default.accept_redirects",
    "0",
    "=1",
    "major",
    57,
    "New interfaces accept ICMP redirects",
    "joining a network is enough for it to reroute your traffic",
  ),
  row(
    "default-send-redirects",
    "net.ipv4.conf.default.send_redirects",
    "0",
    "=1",
    "minor",
    43,
    "New interfaces send ICMP redirects",
    "a desktop advertising routes it does not own",
  ),
  row(
    "default-source-route",
    "net.ipv4.conf.default.accept_source_route",
    "0",
    "=1",
    "major",
    56,
    "New interfaces accept source-routed packets",
    "a sender can dictate the path its packets take to reach you",
  ),
  row(
    "default-log-martians",
    "net.ipv4.conf.default.log_martians",
    "1",
    "=0",
    "minor",
    29,
    "New interfaces drop impossible packets without a trace",
    "spoofed traffic on a network you join leaves no record",
  ),
  row(
    "ipv6-default-ra",
    "net.ipv6.conf.default.accept_ra",
    "0",
    "=1",
    "minor",
    38,
    "New interfaces accept IPv6 router advertisements",
    "anything on a network you join can advertise itself as your router",
  ),
  row(
    "ipv6-default-redirects",
    "net.ipv6.conf.default.accept_redirects",
    "0",
    "=1",
    "minor",
    37,
    "New interfaces accept IPv6 ICMP redirects",
    "the IPv6 half of the redirect problem, for networks you join later",
  ),
  row(
    "ipv6-default-source-route",
    "net.ipv6.conf.default.accept_source_route",
    "0",
    "=1",
    "minor",
    36,
    "New interfaces accept IPv6 source routing",
    "a sender can dictate the path its IPv6 packets take",
  ),
  row(
    "bogus-icmp",
    "net.ipv4.icmp_ignore_bogus_error_responses",
    "1",
    "=0",
    "minor",
    27,
    "Malformed ICMP errors are logged in full",
    "a trivial way to fill your logs from the network",
  ),
  row(
    "tcp-rfc1337",
    "net.ipv4.tcp_rfc1337",
    "1",
    "=0",
    "minor",
    35,
    "TIME-WAIT sockets can be killed from the network",
    "an off-path attacker can tear down connections that are closing",
  ),
  row(
    "shared-media",
    "net.ipv4.conf.all.shared_media",
    "0",
    "=1",
    "minor",
    26,
    "Interfaces assume they share a medium with other subnets",
    "ICMP redirects between subnets are accepted more readily",
  ),
  row(
    "arp-ignore",
    "net.ipv4.conf.all.arp_ignore",
    "1",
    "=0",
    "minor",
    34,
    "The machine answers ARP for addresses it does not own",
    "a mapping of your interfaces is available to anyone on the segment",
  ),
  row(
    "arp-announce",
    "net.ipv4.conf.all.arp_announce",
    "2",
    "<2",
    "minor",
    33,
    "ARP announcements use an address from the wrong interface",
    "your interface layout leaks onto every attached network",
  ),
  row(
    "tempaddr",
    "net.ipv6.conf.all.use_tempaddr",
    "2",
    "<2",
    "major",
    67,
    "IPv6 privacy extensions are not preferred",
    "your outbound IPv6 address is derived from your MAC, so every site you visit can follow this exact machine across networks",
  ),
  row(
    "tempaddr-default",
    "net.ipv6.conf.default.use_tempaddr",
    "2",
    "<2",
    "major",
    66,
    "New interfaces do not prefer IPv6 privacy addresses",
    "the same MAC-derived tracking, on any network you join later",
  ),
  row(
    "kexec",
    "kernel.kexec_load_disabled",
    "1",
    "=0",
    "minor",
    52,
    "A new kernel can be loaded without a reboot",
    "kexec is a way to replace the running kernel that bypasses Secure Boot",
  ),
  row(
    "ldisc-autoload",
    "dev.tty.ldisc_autoload",
    "0",
    "=1",
    "minor",
    47,
    "TTY line disciplines load on demand",
    "a long-standing source of local privilege-escalation bugs",
  ),
  row(
    "userfaultfd",
    "vm.unprivileged_userfaultfd",
    "0",
    "=1",
    "minor",
    46,
    "Unprivileged processes may use userfaultfd",
    "it makes several kernel race conditions far easier to win",
  ),
  row(
    "mmap-min-addr",
    "vm.mmap_min_addr",
    "65536",
    "<65536",
    "major",
    65,
    "Low memory can be mapped by unprivileged processes",
    "NULL-pointer-dereference bugs in the kernel become exploitable",
  ),
  row(
    "io-uring",
    "kernel.io_uring_disabled",
    "2",
    "<2",
    "minor",
    54,
    "Unprivileged io_uring is available",
    "a young, large kernel interface with a heavy CVE record, that almost no desktop program needs",
  ),
  row(
    "inotify-watches",
    "fs.inotify.max_user_watches",
    "524288",
    "<65536",
    "major",
    59,
    "The file-watch limit is low enough to break editors and build tools",
    "watchers fail with ENOSPC once a project is large, and the tool usually reports it as something else entirely",
  ),
  row(
    "inotify-instances",
    "fs.inotify.max_user_instances",
    "512",
    "<256",
    "minor",
    45,
    "The file-watcher limit is low",
    "several editors and sync tools open one instance each and then stop working",
  ),
  row(
    "qdisc",
    "net.core.default_qdisc",
    "fq_codel",
    "~pfifo_fast",
    "minor",
    31,
    "The network queue has no bufferbloat control",
    "a large upload makes every other connection on the machine feel broken",
  ),
  row(
    "swappiness",
    "vm.swappiness",
    "10",
    ">60",
    "minor",
    32,
    "The kernel swaps eagerly",
    "pages are pushed to disk while memory is still free, which is felt as stutter",
  ),
  row(
    "max-map-count",
    "vm.max_map_count",
    "1048576",
    "<262144",
    "minor",
    30,
    "The memory-map limit is low",
    "games, JVMs and some databases fail with an allocation error that names nothing useful",
  ),
  row(
    "tcp-timestamps",
    "net.ipv4.tcp_timestamps",
    "0",
    "=1",
    "minor",
    24,
    "TCP timestamps reveal this machine's uptime",
    "a passive observer can tell how long the machine has been running, and correlate it across networks",
  ),
  row(
    "icmp-ratelimit",
    "net.ipv4.icmp_ratelimit",
    "100",
    "=0",
    "minor",
    23,
    "ICMP replies are not rate-limited",
    "the machine will answer as fast as it is asked, which is a free amplifier",
  ),
  row(
    "igmp-max",
    "net.ipv4.igmp_max_memberships",
    "20",
    ">20",
    "minor",
    12,
    "The multicast group limit is unusually high",
    "more multicast state than a desktop has any use for",
  ),
  row(
    "tcp-max-syn",
    "net.ipv4.tcp_max_syn_backlog",
    "4096",
    "<1024",
    "minor",
    22,
    "The half-open connection queue is small",
    "a modest burst of connections is enough to start dropping them",
  ),
  row(
    "somaxconn",
    "net.core.somaxconn",
    "4096",
    "<1024",
    "minor",
    21,
    "The listen backlog is small",
    "a server on this machine drops connections under a burst it could have held",
  ),
  row(
    "netdev-backlog",
    "net.core.netdev_max_backlog",
    "16384",
    "<1000",
    "minor",
    20,
    "The device receive queue is small",
    "packets are dropped at the interface under load rather than being processed",
  ),
  row(
    "tcp-fastopen",
    "net.ipv4.tcp_fastopen",
    "3",
    "<3",
    "minor",
    19,
    "TCP Fast Open is not fully enabled",
    "every connection pays an extra round-trip it could have skipped",
  ),
  row(
    "tcp-mtu-probing",
    "net.ipv4.tcp_mtu_probing",
    "1",
    "=0",
    "minor",
    18,
    "Path MTU black holes are not worked around",
    "some connections hang instead of falling back, which reads as a broken site",
  ),
  row(
    "tcp-slow-start",
    "net.ipv4.tcp_slow_start_after_idle",
    "0",
    "=1",
    "minor",
    17,
    "Idle connections restart from a cold window",
    "a resumed connection is slow for no reason on a good link",
  ),
  row(
    "dirty-ratio",
    "vm.dirty_ratio",
    "10",
    ">20",
    "minor",
    16,
    "A large amount of writing is buffered before it reaches disk",
    "a big write stalls everything else when the kernel finally flushes it",
  ),
  row(
    "dirty-bg-ratio",
    "vm.dirty_background_ratio",
    "5",
    ">10",
    "minor",
    15,
    "Background writeback starts late",
    "writes pile up and then land in one burst",
  ),
  row(
    "vfs-cache-pressure",
    "vm.vfs_cache_pressure",
    "50",
    ">100",
    "minor",
    14,
    "Directory and inode caches are dropped aggressively",
    "file operations re-read metadata the kernel had already cached",
  ),
  row(
    "min-free-kbytes",
    "vm.min_free_kbytes",
    "65536",
    "<16384",
    "minor",
    13,
    "The kernel keeps almost no free memory in reserve",
    "allocation under pressure fails rather than waiting",
  ),
  row(
    "panic-on-oops",
    "kernel.panic_on_oops",
    "1",
    "=0",
    "minor",
    11,
    "The kernel continues after an internal error",
    "a machine running on after an oops produces corrupt results rather than a clean restart",
  ),
  row(
    "nmi-watchdog",
    "kernel.nmi_watchdog",
    "1",
    "=0",
    "minor",
    10,
    "The hard-lockup detector is off",
    "a wedged CPU is never noticed or reported",
  ),
  row(
    "pid-max",
    "kernel.pid_max",
    "4194304",
    "<65536",
    "minor",
    9,
    "The process id space is small",
    "a busy build can exhaust process ids",
  ),
  row(
    "file-max",
    "fs.file-max",
    "2097152",
    "<131072",
    "minor",
    26,
    "The system-wide open-file limit is low",
    "editors, browsers and language servers run out of file descriptors together",
  ),
  row(
    "aio-max",
    "fs.aio-max-nr",
    "1048576",
    "<65536",
    "minor",
    8,
    "The asynchronous IO limit is low",
    "databases and virtual machines fail to start with a limit error",
  ),
  row(
    "printk-console",
    "kernel.printk",
    "3",
    ">4",
    "minor",
    7,
    "Kernel messages are printed to the console",
    "log spam over the top of whatever is on screen",
  ),
  row(
    "bpf-jit-harden",
    "net.core.bpf_jit_harden",
    "2",
    "<2",
    "minor",
    53,
    "The BPF just-in-time compiler is not hardened",
    "JIT-sprayed code is a known route to kernel execution",
  ),
  row(
    "randomize-va",
    "kernel.randomize_va_space",
    "2",
    "<2",
    "critical",
    97,
    "Address-space layout randomisation is weakened",
    "the single most load-bearing exploit mitigation on the machine is reduced",
  ),
  row(
    "route-localnet",
    "net.ipv4.conf.all.route_localnet",
    "0",
    "=1",
    "major",
    61,
    "Loopback addresses are routable from outside",
    "a remote packet can reach a service bound only to 127.0.0.1",
  ),
  row(
    "proxy-arp",
    "net.ipv4.conf.all.proxy_arp",
    "0",
    "=1",
    "minor",
    25,
    "The machine answers ARP for other hosts",
    "it advertises reachability it has no business advertising",
  ),
  row(
    "accept-local",
    "net.ipv4.conf.all.accept_local",
    "0",
    "=1",
    "minor",
    24,
    "Packets claiming a local source are accepted from the wire",
    "a trivially spoofable path into local-only services",
  ),
  row(
    "icmp-redirect-secure-def",
    "net.ipv4.conf.default.secure_redirects",
    "0",
    "=1",
    "minor",
    23,
    "New interfaces accept gateway redirects",
    "a compromised gateway can reroute traffic on any network you join",
  ),
  row(
    "bootp-relay",
    "net.ipv4.conf.all.bootp_relay",
    "0",
    "=1",
    "minor",
    22,
    "BOOTP relaying is enabled",
    "a workstation is relaying boot protocol traffic",
  ),
  row(
    "forwarding-default",
    "net.ipv4.conf.default.forwarding",
    "0",
    "=1",
    "minor",
    26,
    "New interfaces forward packets",
    "every network joined later is bridged by default",
  ),
  row(
    "tcp-syn-retries",
    "net.ipv4.tcp_syn_retries",
    "3",
    "<3",
    "minor",
    13,
    "Connection attempts give up quickly",
    "a brief network hiccup becomes a failed connection",
  ),
  row(
    "tcp-keepalive-time",
    "net.ipv4.tcp_keepalive_time",
    "300",
    ">7200",
    "minor",
    14,
    "Dead connections are detected only after hours",
    "a dropped link leaves sockets hanging for two hours",
  ),
  row(
    "tcp-fin-timeout",
    "net.ipv4.tcp_fin_timeout",
    "30",
    ">60",
    "minor",
    12,
    "Closing sockets are held for a long time",
    "connection slots stay occupied after the peer has gone",
  ),
  row(
    "tcp-tw-reuse",
    "net.ipv4.tcp_tw_reuse",
    "2",
    "=0",
    "minor",
    11,
    "Closing sockets cannot be reused",
    "a machine that opens many short connections runs out of ports",
  ),
  row(
    "rmem-max",
    "net.core.rmem_max",
    "16777216",
    "<4194304",
    "minor",
    16,
    "The receive buffer ceiling is small",
    "high-bandwidth transfers cannot open their window fully",
  ),
  row(
    "wmem-max",
    "net.core.wmem_max",
    "16777216",
    "<4194304",
    "minor",
    15,
    "The send buffer ceiling is small",
    "uploads plateau below the link speed",
  ),
  row(
    "udp-rmem-min",
    "net.ipv4.udp_rmem_min",
    "16384",
    "<8192",
    "minor",
    9,
    "The UDP receive floor is small",
    "bursty UDP traffic is dropped before it is read",
  ),
  row(
    "netfilter-conntrack-max",
    "net.netfilter.nf_conntrack_max",
    "262144",
    "<65536",
    "minor",
    17,
    "The connection tracking table is small",
    "under load the firewall starts dropping new connections and logs a table-full message",
  ),
  row(
    "core-uses-pid",
    "kernel.core_uses_pid",
    "1",
    "=0",
    "minor",
    8,
    "Core dumps overwrite each other",
    "the second crash destroys the evidence from the first",
  ),
  row(
    "panic-timeout",
    "kernel.panic",
    "10",
    "=0",
    "minor",
    19,
    "The machine hangs forever after a kernel panic",
    "an unattended machine stays down until somebody notices",
  ),
  row(
    "modules-autoload",
    "kernel.modules_disabled",
    "0",
    "=1",
    "minor",
    7,
    "Module loading is permanently disabled",
    "reported so an unexpected lockdown is visible — it also blocks legitimate drivers",
  ),
  row(
    "overcommit-memory",
    "vm.overcommit_memory",
    "0",
    "=2",
    "minor",
    18,
    "Memory overcommit is disabled",
    "large allocations fail even when the memory would never be touched",
  ),
  row(
    "watermark-scale",
    "vm.watermark_scale_factor",
    "100",
    "<10",
    "minor",
    10,
    "Reclaim starts too late under memory pressure",
    "the machine stalls rather than reclaiming gradually",
  ),
  row(
    "compaction-proactive",
    "vm.compaction_proactiveness",
    "20",
    ">50",
    "minor",
    6,
    "Memory compaction runs aggressively",
    "background compaction competes with your work for CPU",
  ),
  row(
    "page-cluster",
    "vm.page-cluster",
    "0",
    ">1",
    "minor",
    5,
    "Swap reads pull in large clusters",
    "on zram this wastes decompression work on pages nothing asked for",
  ),
  row(
    "max-user-namespaces",
    "user.max_user_namespaces",
    "0",
    ">0",
    "minor",
    43,
    "Unprivileged user namespaces are available",
    "a common first step in local privilege-escalation chains, and also what rootless containers need",
  ),
  row(
    "icmp-echo-all",
    "net.ipv4.icmp_echo_ignore_all",
    "0",
    "=1",
    "minor",
    4,
    "The machine ignores all pings",
    "reported so a machine that appears offline to your own monitoring is explained",
  ),
  row(
    "tcp-abort-overflow",
    "net.ipv4.tcp_abort_on_overflow",
    "0",
    "=1",
    "minor",
    5,
    "Connections are reset when the accept queue is full",
    "clients see a reset instead of a retry, which reads as an application error",
  ),
  row(
    "ip-local-port-range",
    "net.ipv4.ip_local_port_range",
    "1024 65535",
    "~32768 60999",
    "minor",
    6,
    "The ephemeral port range is narrow",
    "a machine opening many connections runs out of source ports",
  ),
  row(
    "tcp-orphan-retries",
    "net.ipv4.tcp_orphan_retries",
    "1",
    ">3",
    "minor",
    3,
    "Orphaned sockets are retried for a long time",
    "closed connections hold kernel memory longer than they need to",
  ),
  row(
    "neigh-gc-thresh",
    "net.ipv4.neigh.default.gc_thresh3",
    "4096",
    "<1024",
    "minor",
    7,
    "The neighbour table is small",
    "on a large network the machine starts dropping ARP entries and connections stall",
  ),
  row(
    "nf-conntrack-timeout",
    "net.netfilter.nf_conntrack_tcp_timeout_established",
    "86400",
    ">432000",
    "minor",
    2,
    "Connection tracking entries are held for days",
    "the table fills with connections that ended long ago",
  ),
  row(
    "ipv6-autoconf",
    "net.ipv6.conf.all.autoconf",
    "0",
    "=1",
    "minor",
    9,
    "Interfaces configure IPv6 addresses automatically",
    "an address is taken from whatever router advertises on the network you join",
  ),
  row(
    "ipv6-router-solicit",
    "net.ipv6.conf.all.router_solicitations",
    "0",
    ">0",
    "minor",
    1,
    "The machine actively solicits IPv6 routers",
    "it announces its presence when joining a network",
  ),
  row(
    "kptr-restrict-strict",
    "net.core.bpf_jit_enable",
    "0",
    "=1",
    "minor",
    10,
    "The BPF just-in-time compiler is enabled",
    "JIT-sprayed code is a known route to kernel execution; disabling it costs packet-filter performance",
  ),
];
