// Thunderbird, second pass: what a message may do, and what the client keeps.
import type { MozPolicy } from "../../type/policy.ts";

type Row = [
  string,
  string,
  string,
  MozPolicy["bad"],
  string,
  MozPolicy["category"],
  number,
  string,
  string,
  string,
];

const ROWS: Row[] = [
  [
    "remote-in-feeds",
    "rss.show.content-base",
    "0",
    "<1",
    "1",
    "privacy",
    52,
    "Feed items load content from their source",
    "subscribing to a feed makes your client fetch from that site on a timer, confirming you read it",
    "Feeds render their supplied text instead.",
  ],
  [
    "auto-download-images",
    "permissions.default.image",
    "1",
    "=1",
    "3",
    "privacy",
    62,
    "Images load automatically in messages",
    "the tracking pixel that tells a sender you opened their mail",
    "Images load on the button you press per message; senders you trust can be excepted.",
  ],
  [
    "link-preview",
    "mail.inline_attachments",
    "true",
    "true",
    "false",
    "security",
    50,
    "Attachments are rendered inline",
    "a malformed attachment is parsed by the renderer simply because you selected the message",
    "Attachments are listed and opened on request.",
  ],
  [
    "remote-fonts",
    "gfx.downloadable_fonts.enabled",
    "true",
    "true",
    "false",
    "security",
    49,
    "Messages may load remote fonts",
    "font parsing has a long history of memory-safety bugs, reachable from a message you merely open",
    "Messages render with local fonts.",
  ],
  [
    "auto-update-addons",
    "extensions.update.autoUpdateDefault",
    "true",
    "false",
    "true",
    "stability",
    44,
    "Extensions do not update themselves",
    "an extension with a known bug stays as it is",
    "Updates install in the background.",
  ],
  [
    "send-format",
    "mail.default_send_format",
    "0",
    "=0",
    "1",
    "privacy",
    30,
    "Replies are sent in the sender's format",
    "an HTML message pulls your reply into HTML too, carrying its tracking surface back",
    "Replies are composed as plain text unless you choose otherwise.",
  ],
  [
    "cookie-lifetime",
    "network.cookie.lifetimePolicy",
    "0",
    "=0",
    "2",
    "privacy",
    48,
    "Cookies from message content persist",
    "a tracker in one message recognises you in the next",
    "They are dropped when the client closes.",
  ],
  [
    "idn-punycode",
    "network.IDN_show_punycode",
    "false",
    "false",
    "true",
    "security",
    60,
    "Lookalike domains render as real text in links",
    "a link to a Cyrillic lookalike is indistinguishable from the real one",
    "Internationalised domains show as punycode, which is the only way to see the difference.",
  ],
  [
    "ssl-required",
    "mail.smtpserver.default.try_ssl",
    "0",
    "<2",
    "2",
    "security",
    63,
    "Outgoing mail may be sent without encryption",
    "your password and your message cross the network in clear text if the server allows it",
    "Requires an encrypted connection. A server that cannot do TLS should not be receiving your password.",
  ],
  [
    "imap-ssl",
    "mail.server.default.socketType",
    "0",
    "<3",
    "3",
    "security",
    64,
    "Mail is fetched without encryption",
    "your password and every message cross the network in clear text",
    "Requires TLS for retrieval.",
  ],
  [
    "chat-enabled",
    "mail.chat.enabled",
    "true",
    "true",
    "false",
    "security",
    42,
    "The built-in chat client is enabled",
    "an extra network-facing protocol stack running inside your mail client",
    "Mail is unaffected.",
  ],
  [
    "telemetry-server-tb",
    "toolkit.telemetry.server",
    '"https://incoming.telemetry.mozilla.org"',
    "~mozilla",
    '"data:,"',
    "privacy",
    40,
    "A telemetry endpoint is configured",
    "the destination remains set even when individual pings are off",
    "Points it at nothing. Mail is unaffected.",
  ],
];

export const THUNDERBIRD2_POLICIES: MozPolicy[] = ROWS.map(
  (
    [id, pref, fallback, bad, safe, category, weight, title, detail, because],
  ) => ({
    id: `tb2-${id}`,
    title,
    category,
    severity: weight >= 50 ? "major" as const : "minor" as const,
    weight,
    product: "thunderbird" as const,
    pref,
    fallback,
    bad,
    safe,
    detail,
    because,
  }),
);
