// Thunderbird preferences. A mail client is the one program that opens content
// sent by strangers, every day, on purpose — so the rows here are about what a
// message is allowed to do when you open it.
import type { MozPolicy } from "../../type/policy.ts";

/** [id, pref, fallback, bad, safe, cat, weight, title, detail, because] */
type Row = [
  string,
  string,
  string,
  MozPolicy["bad"],
  string,
  MozPolicy["category"],
  number,
  string,
  string,
  string,
];

const ROWS: Row[] = [
  [
    "remote-content",
    "mailnews.message_display.disable_remote_image",
    "true",
    "false",
    "true",
    "privacy",
    74,
    "Messages load remote images automatically",
    "a tracking pixel tells the sender you opened the message, when, and from which address",
    "Images load on the button you press per message. Nothing is deleted, and senders you trust can be excepted.",
  ],
  [
    "html-as-plain",
    "mailnews.display.prefer_plaintext",
    "false",
    "false",
    "true",
    "security",
    58,
    "Messages are rendered as HTML by default",
    "HTML mail is the delivery vehicle for tracking, obfuscated links, and rendering bugs",
    "Messages display as text where a text part exists. The original is still there and one click away.",
  ],
  [
    "js-in-mail",
    "javascript.enabled",
    "false",
    "true",
    "false",
    "security",
    80,
    "JavaScript is enabled in message display",
    "a message could run code when you open it",
    "Mail does not need scripting. Nothing you can legitimately receive stops working.",
  ],
  [
    "sanitize-html",
    "mailnews.display.html_as",
    "0",
    "=0",
    "3",
    "security",
    57,
    "HTML in messages is displayed unsanitised",
    "the full HTML of a hostile message is handed to the renderer",
    "Messages display as sanitised HTML — the layout survives, the active parts do not.",
  ],
  [
    "telemetry",
    "toolkit.telemetry.enabled",
    "false",
    "true",
    "false",
    "privacy",
    40,
    "Thunderbird telemetry is enabled",
    "measurements of how you use your mail client are collected",
    "Mail is unaffected. Only the collection stops.",
  ],
  [
    "health-report",
    "datareporting.healthreport.uploadEnabled",
    "true",
    "true",
    "false",
    "privacy",
    41,
    "Thunderbird uploads a health report",
    "usage data about this machine is sent on a schedule",
    "Mail is unaffected. Only the upload stops.",
  ],
  [
    "data-submission",
    "datareporting.policy.dataSubmissionEnabled",
    "true",
    "true",
    "false",
    "privacy",
    42,
    "Thunderbird data submission is enabled",
    "the master switch permitting data upload is on",
    "This is the one switch that turns the rest off with it.",
  ],
  [
    "crash-autosubmit",
    "browser.crashReports.unsubmittedCheck.autoSubmit2",
    "false",
    "true",
    "false",
    "privacy",
    39,
    "Pending crash reports are submitted automatically",
    "crash data — which can contain message content — is sent without asking",
    "You can still submit a report deliberately.",
  ],
  [
    "rss-scripts",
    "rss.display.disallow_mime_handlers",
    "0",
    "<3",
    "3",
    "security",
    56,
    "Feed content is rendered with full handlers",
    "a subscribed feed is untrusted remote content rendered with more privilege than it needs",
    "Feeds render as sanitised text. Reading them is unchanged.",
  ],
  [
    "return-receipts",
    "mail.mdn.report.enabled",
    "true",
    "true",
    "false",
    "privacy",
    38,
    "Read receipts may be sent",
    "a sender can learn exactly when you opened their message",
    "You are no longer asked, and nothing is sent. You can still reply.",
  ],
  [
    "cookies-in-mail",
    "network.cookie.cookieBehavior",
    "0",
    "=0",
    "1",
    "privacy",
    55,
    "Remote content in messages may set cookies",
    "a mail tracker can correlate you across messages and across senders",
    "Third-party cookies stop being accepted in message display.",
  ],
  [
    "no-startup-check",
    "mail.shell.checkDefaultClient",
    "true",
    "true",
    "false",
    "performance",
    12,
    "Thunderbird checks the default mail client at every start",
    "a startup dialog that interrupts the thing you opened the program to do",
    "Thunderbird still works as the default client if it is one.",
  ],
  [
    "phishing-detect",
    "mail.phishing.detection.enabled",
    "true",
    "false",
    "true",
    "security",
    59,
    "Phishing detection is off",
    "a link whose text and destination disagree passes without a warning",
    "The warning bar returns. It never blocks a message, only flags it.",
  ],
  [
    "link-mismatch",
    "mail.phishing.detection.disallow_form_actions",
    "true",
    "false",
    "true",
    "security",
    58,
    "Forms inside messages may submit anywhere",
    "a login form rendered inside a message can post your credentials to any address",
    "Form submission from messages is refused.",
  ],
  [
    "openpgp-fetch",
    "mail.openpgp.fetch_pubkeys_from_gnupg",
    "false",
    "true",
    "false",
    "privacy",
    37,
    "Thunderbird fetches keys through GnuPG automatically",
    "opening a signed message can trigger a network lookup that identifies you to a keyserver",
    "Keys can still be imported when you choose to.",
  ],
  [
    "addons-recommend",
    "extensions.getAddons.showPane",
    "true",
    "true",
    "false",
    "privacy",
    20,
    "Add-on recommendations are fetched",
    "the add-ons panel makes a request every time you open it",
    "Searching for an add-on still works.",
  ],
  [
    "startup-page",
    "mailnews.start_page.enabled",
    "true",
    "true",
    "false",
    "privacy",
    19,
    "A start page is loaded when Thunderbird opens",
    "a remote page fetched at every start, before you read anything",
    "Thunderbird opens on your mail instead.",
  ],
  [
    "compose-html",
    "mail.identity.default.compose_html",
    "true",
    "true",
    "false",
    "privacy",
    18,
    "New messages are composed as HTML",
    "your mail carries the same tracking surface you do not want to receive",
    "Messages are composed as plain text. You can switch per message.",
  ],
  [
    "cookies-thirdparty",
    "network.cookie.thirdparty.sessionOnly",
    "false",
    "false",
    "true",
    "privacy",
    36,
    "Third-party cookies in message display persist",
    "a tracker in one message recognises you in the next",
    "They are dropped when Thunderbird closes.",
  ],
];

export const THUNDERBIRD_POLICIES: MozPolicy[] = ROWS.map(
  (
    [id, pref, fallback, bad, safe, category, weight, title, detail, because],
  ) => ({
    id: `tb-${id}`,
    title,
    category,
    severity: weight >= 60 ? "major" as const : "minor" as const,
    weight,
    product: "thunderbird" as const,
    pref,
    fallback,
    bad,
    safe,
    detail,
    because,
  }),
);
