// Flatpak sandbox defaults, container and cloud tooling, and the rest of the
// shell environment.
//
// The Flatpak rows are the highest-value group here: a global override applies
// to every sandboxed application at once, so one row closes a hole across the
// whole set rather than app by app.
import type { ConfPolicy } from "../../type/policy.ts";

/** [id, file, format, section, key, safe, missingIsBad, cat, band, weight,
 *   title, detail, because, needs?] */
type Row = [
  string,
  string,
  ConfPolicy["format"],
  string | undefined,
  string,
  string,
  boolean,
  ConfPolicy["category"],
  ConfPolicy["severity"],
  number,
  string,
  string,
  string,
  string?,
];

const FP = ".local/share/flatpak/overrides/global";

const FLATPAK: Row[] = [
  [
    "fp-host-fs",
    FP,
    "ini",
    "Context",
    "filesystems",
    "!host;!host-os;!host-etc",
    true,
    "security",
    "critical",
    97,
    "Sandboxed applications may read your whole filesystem",
    "an app granted `filesystem=host` is not sandboxed in any meaningful sense — it can read every file you own",
    "Writes a global override that denies host filesystem access to every Flatpak. Apps that genuinely need a folder can be granted it individually with `flatpak override --user --filesystem=~/Documents <app>`.",
    "flatpak",
  ],
  [
    "fp-devices",
    FP,
    "ini",
    "Context",
    "devices",
    "!all",
    true,
    "security",
    "major",
    86,
    "Sandboxed applications may reach every device",
    "`device=all` includes raw input devices, which is enough to read your keyboard",
    "Writes a global override. `dri` (graphics) is unaffected, so rendering still works; grant individual apps what they need.",
    "flatpak",
  ],
  [
    "fp-x11-fallback",
    FP,
    "ini",
    "Context",
    "sockets",
    "!x11;!fallback-x11",
    true,
    "security",
    "major",
    85,
    "Sandboxed applications may talk to the X server",
    "X11 has no isolation between clients: any app on it can read every keystroke you type into any window",
    "Writes a global override. Wayland apps are unaffected; X11-only apps need the socket granted back individually.",
    "flatpak",
  ],
  [
    "fp-session-bus",
    FP,
    "ini",
    "Context",
    "shared",
    "!network",
    false,
    "privacy",
    "minor",
    20,
    "Sandboxed applications share the network namespace",
    "reported so you can see the global default; most apps genuinely need network",
    "Reported only in the sense that you may well want it — Undo restores it immediately.",
    "flatpak",
  ],
  [
    "fp-talk-flatpak",
    FP,
    "ini",
    "Session Bus Policy",
    "org.freedesktop.Flatpak",
    "none",
    true,
    "security",
    "critical",
    98,
    "Sandboxed applications may talk to the Flatpak service",
    "an app that can call org.freedesktop.Flatpak can start a process outside its own sandbox — the sandbox becomes decorative",
    "Writes a global override denying that one bus name. Development tools that genuinely need it can be granted it individually.",
    "flatpak",
  ],
  [
    "fp-talk-a11y",
    FP,
    "ini",
    "Session Bus Policy",
    "org.a11y.Bus",
    "none",
    false,
    "security",
    "minor",
    34,
    "Sandboxed applications may use the accessibility bus",
    "the accessibility bus can read the contents of other applications' windows",
    "Writes a global override. Undo immediately if you use a screen reader.",
    "flatpak",
  ],
];

const CLOUD: Row[] = [
  [
    "docker-content-trust",
    ".docker/config.json",
    "equals",
    undefined,
    "DOCKER_CONTENT_TRUST",
    "1",
    false,
    "security",
    "major",
    84,
    "Docker does not verify image signatures",
    "an image pulled by tag can be replaced with another",
    "Reported where the variable is set to 0. Signed images are verified; unsigned ones must be pulled explicitly.",
    "docker",
  ],
  [
    "aws-metadata",
    ".aws/config",
    "ini",
    "default",
    "ec2_metadata_service_endpoint_mode",
    "IPv6",
    false,
    "security",
    "minor",
    15,
    "The AWS CLI uses the legacy metadata endpoint",
    "IMDSv1-style access is the one that server-side request forgery abuses",
    "Reported only where the setting exists.",
    "aws",
  ],
  [
    "gcloud-usage",
    ".config/gcloud/configurations/config_default",
    "ini",
    "core",
    "disable_usage_reporting",
    "True",
    true,
    "privacy",
    "minor",
    33,
    "The gcloud CLI reports usage",
    "which commands you run against which projects is sent to Google",
    "Commands work exactly the same.",
    "gcloud",
  ],
  [
    "kubectl-noproxy",
    ".kube/config",
    "ini",
    undefined,
    "insecure-skip-tls-verify",
    "false",
    false,
    "security",
    "critical",
    93,
    "A Kubernetes cluster is configured to skip TLS verification",
    "the connection to your cluster accepts any certificate",
    "Reported where it is set — the fix is to add the cluster's certificate authority rather than to trust everything.",
    "kubectl",
  ],
];

const SHELL2: Row[] = [
  [
    "tmux-lock",
    ".tmux.conf",
    "line",
    undefined,
    "set -g lock-after-time 900",
    "",
    true,
    "security",
    "minor",
    32,
    "tmux sessions never lock on idle",
    "a detached terminal on a shared machine is an open shell",
    "Adds one line to ~/.tmux.conf. Existing sessions are unaffected until reloaded.",
    "tmux",
  ],
  [
    "screen-lock",
    ".screenrc",
    "line",
    undefined,
    "idle 900 lockscreen",
    "",
    true,
    "security",
    "minor",
    31,
    "screen sessions never lock on idle",
    "the same open shell, in the other multiplexer",
    "Adds one line to ~/.screenrc.",
    "screen",
  ],
  [
    "gpg-agent-ttl",
    ".gnupg/gpg-agent.conf",
    "space",
    undefined,
    "default-cache-ttl",
    "600",
    true,
    "security",
    "minor",
    49,
    "The GnuPG agent caches your passphrase for a long time",
    "your key stays unlocked long after you stopped using it",
    "Ten minutes of inactivity. You are asked again after that.",
    "gpg",
  ],
  [
    "gpg-agent-max-ttl",
    ".gnupg/gpg-agent.conf",
    "space",
    undefined,
    "max-cache-ttl",
    "3600",
    true,
    "security",
    "minor",
    48,
    "The GnuPG agent has no upper bound on caching",
    "an actively used key never needs re-entering, however long the session lasts",
    "One hour, then the passphrase is asked for again.",
    "gpg",
  ],
  [
    "ssh-agent-ttl",
    ".bashrc",
    "line",
    undefined,
    "export SSH_ASKPASS_REQUIRE=prefer",
    "",
    false,
    "security",
    "minor",
    11,
    "Key passphrase prompts go to the terminal",
    "reported for awareness; this is usually what you want",
    "Adds one line to ~/.bashrc.",
    "bash",
  ],
];

const ROWS: Row[] = [...FLATPAK, ...CLOUD, ...SHELL2];

export const TOOL3_POLICIES: ConfPolicy[] = ROWS.map(
  (
    [
      id,
      file,
      format,
      section,
      key,
      safe,
      missingIsBad,
      category,
      severity,
      weight,
      title,
      detail,
      because,
      needs,
    ],
  ): ConfPolicy => ({
    id: `t3-${id}`,
    title,
    category,
    severity,
    weight,
    file,
    format,
    section,
    key,
    safe,
    missingIsBad,
    needs,
    detail,
    because,
  }),
);
