// Shell, editor and language-tool configuration.
//
// The theme: a config file is a program that runs before you type anything.
// These rows are the lines that decide whether a pasted string can execute,
// whether a directory you `cd` into gets to configure your editor, and whether
// the tool you just installed phones home.
import type { ConfPolicy } from "../../type/policy.ts";

/** [id, file, format, key, safe, missingIsBad, cat, band, weight, title,
 *   detail, because, needs?] */
type Row = [
  string,
  string,
  ConfPolicy["format"],
  string,
  string,
  boolean,
  ConfPolicy["category"],
  ConfPolicy["severity"],
  number,
  string,
  string,
  string,
  string?,
];

const SHELL: Row[] = [
  [
    "umask-bashrc",
    ".bashrc",
    "line",
    "umask 077",
    "",
    true,
    "security",
    "major",
    82,
    "New files you create are readable by other accounts",
    "every file you make starts world-readable until something narrows it — which is the finding half this catalogue reports",
    "Adds one line to ~/.bashrc. It applies to files created in new shells; nothing existing is touched, and Undo removes the line.",
    "bash",
  ],
  [
    "histcontrol",
    ".bashrc",
    "line",
    "export HISTCONTROL=ignoreboth",
    "",
    true,
    "privacy",
    "minor",
    44,
    "Commands you prefix with a space are still recorded",
    "the usual way to keep a password out of your history does nothing",
    "Adds one line to ~/.bashrc. A leading space keeps a command out of the history file, and duplicates stop piling up.",
    "bash",
  ],
  [
    "histfile-perms-cmd",
    ".bashrc",
    "line",
    "export HISTTIMEFORMAT='%F %T '",
    "",
    true,
    "settings",
    "minor",
    12,
    "Shell history has no timestamps",
    "you cannot tell when a command in your history was actually run",
    "Adds one line to ~/.bashrc. Existing history entries stay as they are.",
    "bash",
  ],
  [
    "less-history",
    ".bashrc",
    "line",
    "export LESSHISTFILE=-",
    "",
    true,
    "privacy",
    "minor",
    36,
    "`less` records what you have paged through",
    "a file listing everything you have read, including files you opened once",
    "Adds one line to ~/.bashrc. `less` still works; it stops writing ~/.lesshst.",
    "bash",
  ],
];

const VIM: Row[] = [
  [
    "vim-modeline",
    ".vimrc",
    "line",
    "set nomodeline",
    "",
    true,
    "security",
    "major",
    81,
    "Vim honours modelines in files it opens",
    "a line inside a file you merely open can change Vim's settings, and modeline handling has a long history of being exploitable",
    "Adds one line to ~/.vimrc. Editing is unchanged; only in-file setting directives stop being obeyed.",
    "vim",
  ],
  [
    "vim-secure",
    ".vimrc",
    "line",
    "set noexrc",
    "",
    true,
    "security",
    "critical",
    90,
    "Vim reads configuration from the directory you start it in",
    "cloning a repository and opening a file in it can run that repository's Vim configuration",
    "Adds one line to ~/.vimrc. Your own ~/.vimrc is unaffected.",
    "vim",
  ],
  [
    "vim-viminfo",
    ".vimrc",
    "line",
    "set viminfo='20,<50,s10,h",
    "",
    true,
    "privacy",
    "minor",
    35,
    "Vim remembers an unlimited amount about what you edited",
    "file marks, registers and search terms accumulate without bound",
    "Adds one line to ~/.vimrc bounding what is kept. Existing viminfo is left alone.",
    "vim",
  ],
];

const GO: Row[] = [
  [
    "go-telemetry",
    ".config/go/telemetry/mode",
    "line",
    "off",
    "",
    true,
    "privacy",
    "minor",
    34,
    "The Go toolchain uploads telemetry",
    "counters describing what you build are sent to the Go team",
    "Writes `off` into the telemetry mode file. Building is unaffected.",
    "go",
  ],
  [
    "go-sumdb",
    ".config/go/env",
    "equals",
    "GOSUMDB",
    "sum.golang.org",
    false,
    "security",
    "critical",
    92,
    "Go module checksum verification is disabled",
    "a tampered module is indistinguishable from the real one",
    "Restores the checksum database. Modules you have already downloaded are unaffected.",
    "go",
  ],
  [
    "go-noproxy-insecure",
    ".config/go/env",
    "equals",
    "GOINSECURE",
    "",
    false,
    "security",
    "major",
    76,
    "Go is told to fetch some modules without TLS",
    "the modules matching that pattern arrive over plain HTTP",
    "Clears the exception. If one internal host needs it, list that host rather than a wildcard.",
    "go",
  ],
];

const NPM2: Row[] = [
  [
    "npm-registry-https",
    ".npmrc",
    "equals",
    "registry",
    "https://registry.npmjs.org/",
    false,
    "security",
    "critical",
    91,
    "npm fetches packages over plain HTTP",
    "every package you install can be replaced in transit",
    "Points the registry at its HTTPS address. Private registries should be set per-scope.",
    "npm",
  ],
];

const WGET2: Row[] = [
  [
    "wget-content-disposition",
    ".wgetrc",
    "ini",
    "content_disposition",
    "off",
    false,
    "security",
    "minor",
    43,
    "wget lets the server choose the filename",
    "a download can land under a name you did not choose, including one that hides its extension",
    "Filenames come from the URL again. Pass --content-disposition per command when you want it.",
    "wget",
  ],
  [
    "wget-secure-protocol",
    ".wgetrc",
    "ini",
    "secure_protocol",
    "TLSv1_2",
    false,
    "security",
    "major",
    77,
    "wget will negotiate an obsolete TLS version",
    "downloads can be protected by a protocol that is no longer considered safe",
    "Sets a TLS 1.2 floor. Servers older than that become unreachable — undo if you need one.",
    "wget",
  ],
];

const CURL2: Row[] = [
  [
    "curl-sslv2",
    ".curlrc",
    "space",
    "sslv3",
    "",
    false,
    "security",
    "major",
    78,
    "curl is configured to use SSLv3",
    "a protocol broken beyond repair, forced on for every request",
    "The line is commented out, not deleted.",
    "curl",
  ],
  [
    "curl-doh",
    ".curlrc",
    "space",
    "doh-url",
    "",
    false,
    "privacy",
    "minor",
    11,
    "curl resolves names through a fixed DNS-over-HTTPS server",
    "one provider sees every hostname curl looks up on this account",
    "Reported so you know it is set — it may well be deliberate.",
    "curl",
  ],
];

const ROWS: Row[] = [...SHELL, ...VIM, ...GO, ...NPM2, ...WGET2, ...CURL2];

export const TOOL2_POLICIES: ConfPolicy[] = ROWS.map(
  (
    [
      id,
      file,
      format,
      key,
      safe,
      missingIsBad,
      category,
      severity,
      weight,
      title,
      detail,
      because,
      needs,
    ],
  ): ConfPolicy => ({
    id: `tool-${id}`,
    title,
    category,
    severity,
    weight,
    file,
    format,
    key,
    safe,
    missingIsBad,
    // A row whose safe value is empty is asking for the key to be gone.
    presentIsBad: safe === "" && format !== "line" ? true : undefined,
    needs,
    detail,
    because,
  }),
);
