// A last pass over system configuration: the units, rules and policy files
// that decide what runs, what may talk to what, and what is written down.
import type { SysPolicy } from "../../../type/policy.ts";

const sh = (script: string) => ({
  kind: "cmd" as const,
  cmd: "sh",
  args: ["-c", script] as const,
});

/** [id, script, bad, cat, band, weight, title, detail, how] */
type Row = [
  string,
  string,
  SysPolicy["bad"],
  SysPolicy["category"],
  SysPolicy["severity"],
  number,
  string,
  string,
  string,
];

const ROWS: Row[] = [
  [
    "udev-writable",
    "find /etc/udev/rules.d -type f -perm -o+w 2>/dev/null | wc -l",
    ">0",
    "security",
    "critical",
    94,
    "A device rule file is writable by other accounts",
    "udev rules run as root when hardware appears, so a writable rule is root on the next plug-in",
    "`sudo chmod 644 /etc/udev/rules.d/*`.",
  ],
  [
    "polkit-permissive",
    "grep -rl 'ResultAny=yes' /etc/polkit-1/ 2>/dev/null | wc -l",
    ">0",
    "security",
    "critical",
    93,
    "A polkit rule grants an action to anyone",
    "`ResultAny=yes` means any user, including a remote session, can perform that privileged action without authenticating",
    "`sudo grep -rl ResultAny=yes /etc/polkit-1/` and narrow each rule to the group that needs it.",
  ],
  [
    "systemd-writable-units",
    "find /etc/systemd/system -maxdepth 1 -name '*.service' -perm -o+w 2>/dev/null | wc -l",
    ">0",
    "security",
    "critical",
    95,
    "A service unit file is writable by other accounts",
    "a unit file is a command line that runs as root at boot",
    "`sudo chmod 644 /etc/systemd/system/*.service`.",
  ],
  [
    "systemd-relative-exec",
    "grep -rhE '^ExecStart=[^/]' /etc/systemd/system/*.service 2>/dev/null | wc -l",
    ">0",
    "security",
    "major",
    78,
    "A service starts a command by relative path",
    "which program runs then depends on the search path at boot",
    "Use an absolute path in ExecStart.",
  ],
  [
    "cron-writable",
    "find /etc/cron.d /etc/cron.daily /etc/cron.hourly -type f -perm -o+w 2>/dev/null | wc -l",
    ">0",
    "security",
    "critical",
    96,
    "A scheduled job file is writable by other accounts",
    "the file runs as root on a timer",
    "`sudo chmod 700` on the directories and `644` on the files.",
  ],
  [
    "profile-d-writable",
    "find /etc/profile.d -type f -perm -o+w 2>/dev/null | wc -l",
    ">0",
    "security",
    "critical",
    92,
    "A login script is writable by other accounts",
    "every user's shell sources these at login",
    "`sudo chmod 644 /etc/profile.d/*`.",
  ],
  [
    "ld-so-conf-writable",
    "find /etc/ld.so.conf.d -type f -perm -o+w 2>/dev/null | wc -l",
    ">0",
    "security",
    "critical",
    97,
    "A library search path file is writable by other accounts",
    "it decides where every program on the machine loads its libraries from",
    "`sudo chmod 644 /etc/ld.so.conf.d/*`.",
  ],
  [
    "ld-preload-global",
    "[ -s /etc/ld.so.preload ] && echo present || echo absent",
    "~present",
    "security",
    "critical",
    98,
    "A library is force-loaded into every program on the machine",
    "/etc/ld.so.preload injects code system-wide — a classic and effective rootkit technique",
    "`cat /etc/ld.so.preload`. If you did not put it there, treat the machine as compromised.",
  ],
  [
    "sudoers-includedir",
    "grep -c '^#includedir' /etc/sudoers 2>/dev/null",
    "=0",
    "settings",
    "minor",
    24,
    "sudoers does not include its drop-in directory",
    "rules in /etc/sudoers.d are silently ignored, which is confusing in both directions",
    "Add `#includedir /etc/sudoers.d` with `sudo visudo`.",
  ],
  [
    "shadow-group",
    "stat -c %G /etc/shadow 2>/dev/null",
    "~root",
    "security",
    "minor",
    40,
    "The password file is owned by the root group",
    "reported for awareness; `shadow` is the more common owner and allows tighter modes",
    "Either is defensible. `sudo chown root:shadow /etc/shadow && sudo chmod 640 /etc/shadow` is the usual arrangement.",
  ],
  [
    "home-perm-default",
    "stat -c %a /home 2>/dev/null",
    ">755",
    "security",
    "major",
    74,
    "The /home directory is more open than it needs to be",
    "the list of accounts on the machine is readable, and in some modes writable, by anyone",
    "`sudo chmod 755 /home`.",
  ],
  [
    "tmp-not-tmpfs",
    "findmnt -no FSTYPE /tmp 2>/dev/null || echo none",
    "~none",
    "performance",
    "minor",
    30,
    "/tmp is on disk rather than in memory",
    "temporary files are written to the SSD and survive reboots, which costs write endurance and leaks state",
    "A tmpfs /tmp is faster and self-clearing: `sudo systemctl enable --now tmp.mount`. Check first that nothing you use writes large files there.",
  ],
  [
    "var-log-perm",
    "stat -c %a /var/log 2>/dev/null",
    ">755",
    "privacy",
    "major",
    70,
    "The log directory is more open than it needs to be",
    "logs name users, addresses and occasionally secrets",
    "`sudo chmod 755 /var/log`.",
  ],
  [
    "etc-writable",
    "find /etc -maxdepth 1 -type f -perm -o+w 2>/dev/null | wc -l",
    ">0",
    "security",
    "critical",
    99,
    "A file directly under /etc is writable by other accounts",
    "system configuration that any account can rewrite",
    "`sudo find /etc -maxdepth 1 -type f -perm -o+w -ls` names them; `sudo chmod o-w` on each.",
  ],
  [
    "binaries-writable",
    "find /usr/local/bin /usr/local/sbin -type f -perm -o+w 2>/dev/null | wc -l",
    ">0",
    "security",
    "critical",
    99,
    "A program in /usr/local is writable by other accounts",
    "anything on the machine can replace a command that everyone runs, including root",
    "`sudo chmod o-w` on each.",
  ],
  [
    "setuid-unexpected-system",
    "find /usr/local -type f -perm -4000 2>/dev/null | wc -l",
    ">0",
    "security",
    "major",
    80,
    "There are setuid programs in /usr/local",
    "locally installed setuid binaries are outside the package manager's checks",
    "`find /usr/local -perm -4000 -ls`. Remove the bit unless the program genuinely needs it.",
  ],
  [
    "capabilities-set",
    "getcap -r /usr/bin /usr/local/bin 2>/dev/null | wc -l",
    ">6",
    "security",
    "minor",
    46,
    "Several programs carry elevated capabilities",
    "a capability is a narrower form of setuid, and each one is still a privilege boundary",
    "`getcap -r /usr /bin /sbin` lists them. Check each is one you expect.",
  ],
  [
    "motd-writable",
    "find /etc/update-motd.d -type f -perm -o+w 2>/dev/null | wc -l",
    ">0",
    "security",
    "critical",
    91,
    "A login-message script is writable by other accounts",
    "these run as root each time somebody logs in",
    "`sudo chmod 755 /etc/update-motd.d/*`.",
  ],
  [
    "network-scripts-writable",
    "find /etc/NetworkManager -type f -perm -o+r -name '*.nmconnection' 2>/dev/null | wc -l",
    ">0",
    "security",
    "critical",
    90,
    "A saved network profile is readable by other accounts",
    "these files hold Wi-Fi passphrases and VPN credentials in clear text",
    "`sudo chmod 600 /etc/NetworkManager/system-connections/*`.",
  ],
  [
    "resolvconf-writable",
    "find /etc/resolv.conf -perm -o+w 2>/dev/null | wc -l",
    ">0",
    "security",
    "critical",
    89,
    "The resolver configuration is writable by other accounts",
    "whoever writes it decides where every name lookup goes",
    "`sudo chmod 644 /etc/resolv.conf` (or let systemd-resolved own it as a symlink).",
  ],
  [
    "hosts-writable",
    "find /etc/hosts -perm -o+w 2>/dev/null | wc -l",
    ">0",
    "security",
    "critical",
    88,
    "The hosts file is writable by other accounts",
    "an entry there overrides DNS for every program on the machine",
    "`sudo chmod 644 /etc/hosts`.",
  ],
  [
    "apt-conf-writable",
    "find /etc/apt -type f -perm -o+w 2>/dev/null | wc -l",
    ">0",
    "security",
    "critical",
    94,
    "An apt configuration file is writable by other accounts",
    "it decides where packages come from and whether signatures are checked",
    "`sudo chmod 644` on the file.",
  ],
  [
    "keyring-writable",
    "find /etc/apt/trusted.gpg.d /etc/apt/keyrings -type f -perm -o+w 2>/dev/null | wc -l",
    ">0",
    "security",
    "critical",
    97,
    "A package signing key is writable by other accounts",
    "whoever writes it decides which packages the machine will accept as genuine",
    "`sudo chmod 644` on the keyring files.",
  ],
  [
    "initramfs-perm",
    "stat -c %a /boot/initrd.img-$(uname -r) 2>/dev/null",
    ">644",
    "security",
    "minor",
    42,
    "The initial ramdisk is more open than it needs to be",
    "it can contain the keyfile that unlocks an encrypted disk",
    "`sudo chmod 600 /boot/initrd.img-*` if your setup embeds a key.",
  ],
  [
    "fstab-writable",
    "find /etc/fstab -perm -o+w 2>/dev/null | wc -l",
    ">0",
    "security",
    "critical",
    95,
    "The filesystem table is writable by other accounts",
    "it decides what gets mounted where, with which options, at boot",
    "`sudo chmod 644 /etc/fstab`.",
  ],
];

export const ETC4_POLICIES: SysPolicy[] = ROWS.map(
  (
    [id, script, bad, category, severity, weight, title, detail, how],
  ): SysPolicy => ({
    id: `sysetc-${id}`,
    title,
    category,
    severity,
    weight,
    source: sh(script),
    bad,
    detail,
    how,
  }),
);
