// Listening TCP and UDP ports.
//
// One row per well-known service, and the question each asks is the same: is
// this reachable from the network, on a machine that is a workstation? A port
// bound to 127.0.0.1 is not a finding; a port on 0.0.0.0 is.
import type { SysPolicy } from "../../../type/policy.ts";
import type { Severity } from "../../../type/issue.ts";

/** [port, service, why it matters here, band, weight] */
type Row = [number, string, string, Severity, number];

const remote = (what: string) => `${what} is reachable from the network`;

const TCP: Row[] = [
  [20, "FTP data", remote("clear-text file transfer"), "critical", 95],
  [69, "TFTP", remote("unauthenticated file transfer"), "critical", 94],
  [79, "finger", "the account list is queryable from the network", "major", 70],
  [110, "POP3", remote("clear-text mail retrieval"), "major", 72],
  [119, "NNTP", remote("a news server"), "minor", 30],
  [143, "IMAP", remote("clear-text mail access"), "major", 71],
  [
    161,
    "SNMP",
    "SNMP is reachable, and its default community strings are public knowledge",
    "critical",
    90,
  ],
  [389, "LDAP", remote("a directory service, unencrypted"), "major", 74],
  [512, "rexec", remote("unauthenticated remote execution"), "critical", 97],
  [513, "rlogin", remote("clear-text remote login"), "critical", 97],
  [514, "rsh", remote("unauthenticated remote shell"), "critical", 97],
  [515, "LPD", remote("a legacy print service"), "minor", 32],
  [
    873,
    "rsync",
    "an rsync daemon is reachable, and its default is anonymous",
    "major",
    76,
  ],
  [
    1080,
    "SOCKS proxy",
    "an open proxy relays traffic for anyone who finds it",
    "critical",
    89,
  ],
  [1194, "OpenVPN", remote("a VPN server"), "minor", 40],
  [1433, "MSSQL", remote("a database"), "critical", 88],
  [1521, "Oracle", remote("a database"), "critical", 88],
  [
    1723,
    "PPTP",
    "PPTP is reachable, and its encryption is broken",
    "critical",
    91,
  ],
  [2049, "NFS", remote("filesystem export"), "major", 75],
  [
    2375,
    "Docker API",
    "the Docker API is reachable UNENCRYPTED, and it is equivalent to root on this machine",
    "critical",
    99,
  ],
  [
    2376,
    "Docker TLS",
    "the Docker API is reachable; it is equivalent to root on this machine",
    "critical",
    98,
  ],
  [3000, "dev server", remote("a development server"), "minor", 41],
  [3128, "Squid", "a proxy is reachable from the network", "major", 69],
  [
    4444,
    "alt",
    "a port commonly used by remote-access tooling is open",
    "major",
    73,
  ],
  [5000, "dev server", remote("a development server"), "minor", 41],
  [5001, "dev server", remote("a development server"), "minor", 40],
  [5060, "SIP", remote("a telephony service"), "minor", 38],
  [
    5353,
    "mDNS",
    "the machine answers name queries for the whole local segment",
    "minor",
    34,
  ],
  [5432, "PostgreSQL", remote("a database"), "critical", 93],
  [
    5555,
    "ADB",
    "the Android debug bridge is reachable, and it grants shell access",
    "critical",
    96,
  ],
  [5601, "Kibana", remote("a log console, often unauthenticated"), "major", 77],
  [5672, "AMQP", remote("a message broker"), "major", 68],
  [5800, "VNC http", remote("a remote desktop"), "critical", 92],
  [5984, "CouchDB", remote("a database"), "critical", 87],
  [
    6000,
    "X11",
    "the X server accepts network clients, which can read every keystroke you type",
    "critical",
    99,
  ],
  [6001, "X11", "a second X display accepts network clients", "critical", 98],
  [6443, "Kubernetes API", remote("a cluster API"), "critical", 90],
  [6667, "IRC", remote("an IRC service"), "minor", 30],
  [7000, "alt", remote("a service on a commonly probed port"), "minor", 28],
  [8000, "dev server", remote("a development server"), "minor", 42],
  [8081, "alt HTTP", remote("a web service"), "minor", 39],
  [8086, "InfluxDB", remote("a time-series database"), "major", 67],
  [8123, "Home Assistant", remote("a home automation console"), "major", 66],
  [8443, "HTTPS alt", remote("a web service"), "minor", 37],
  [
    8888,
    "alt HTTP",
    remote("a notebook or web service, often token-authenticated only"),
    "major",
    65,
  ],
  [9000, "alt", remote("a web or admin service"), "minor", 36],
  [9090, "Prometheus", remote("a metrics console"), "minor", 35],
  [
    9200,
    "Elasticsearch",
    "Elasticsearch is reachable, and its default has no authentication",
    "critical",
    89,
  ],
  [9300, "Elasticsearch", remote("a cluster transport port"), "major", 64],
  [
    10000,
    "Webmin",
    "a web administration console is reachable, and it authenticates as root",
    "critical",
    97,
  ],
  [
    11434,
    "Ollama",
    "a local model server is reachable, and its default has no authentication",
    "major",
    63,
  ],
  [
    15672,
    "RabbitMQ UI",
    remote("a broker console with well-known default credentials"),
    "critical",
    86,
  ],
  [27018, "MongoDB", remote("a database"), "critical", 87],
  [27019, "MongoDB", remote("a config server"), "critical", 86],
  [50000, "alt", remote("a service on a commonly probed port"), "minor", 26],
  [23, "telnet", remote("clear-text remote login"), "critical", 99],
  [25, "SMTP", remote("a mail server"), "major", 73],
  [88, "Kerberos", remote("a Kerberos service"), "minor", 31],
  [135, "MSRPC", remote("an RPC endpoint mapper"), "major", 77],
  [445, "SMB", remote("Windows file sharing"), "major", 79],
  [548, "AFP", remote("Apple file sharing"), "minor", 33],
  [631, "IPP", remote("the print service"), "minor", 35],
  [636, "LDAPS", remote("a directory service"), "minor", 29],
  [993, "IMAPS", remote("mail access"), "minor", 28],
  [995, "POP3S", remote("mail retrieval"), "minor", 27],
  [
    1099,
    "Java RMI",
    "Java RMI is reachable, and it deserialises whatever it is sent",
    "critical",
    92,
  ],
  [1414, "IBM MQ", remote("a message queue"), "major", 61],
  [
    2181,
    "ZooKeeper",
    "ZooKeeper is reachable, and its default has no authentication",
    "critical",
    85,
  ],
  [
    2379,
    "etcd",
    "etcd is reachable, and it holds cluster secrets",
    "critical",
    94,
  ],
  [3260, "iSCSI", remote("block storage"), "major", 75],
  [3306, "MySQL", remote("a database"), "critical", 93],
  [3389, "RDP", remote("a remote desktop"), "critical", 92],
  [4369, "epmd", remote("the Erlang port mapper"), "major", 60],
  [5044, "Logstash", remote("a log ingest endpoint"), "minor", 34],
  [5051, "Mesos", remote("a cluster agent"), "major", 59],
  [5498, "Hotline", remote("a legacy service"), "minor", 20],
  [5900, "VNC", remote("a remote desktop"), "critical", 92],
  [5901, "VNC", remote("a second remote desktop"), "critical", 91],
  [5938, "TeamViewer", remote("a remote-support service"), "major", 76],
  [6006, "TensorBoard", remote("a machine-learning console"), "minor", 32],
  [
    6379,
    "Redis",
    "Redis is reachable, and its default is unauthenticated command execution",
    "critical",
    95,
  ],
  [7001, "WebLogic", remote("an application server"), "critical", 84],
  [7077, "Spark", remote("a cluster master"), "major", 57],
  [8020, "Hadoop", remote("a filesystem namenode"), "major", 56],
  [8088, "Hadoop UI", remote("a cluster console"), "major", 55],
  [
    8161,
    "ActiveMQ",
    remote("a broker console with default credentials"),
    "critical",
    83,
  ],
  [
    8500,
    "Consul",
    "Consul is reachable, and it holds service credentials",
    "critical",
    90,
  ],
  [8686, "JMX", remote("a Java management endpoint"), "critical", 88],
  [9042, "Cassandra", remote("a database"), "critical", 82],
  [9092, "Kafka", remote("a message broker"), "major", 54],
  [
    9100,
    "JetDirect",
    remote("a raw print port, which accepts anything"),
    "minor",
    30,
  ],
  [
    9418,
    "git daemon",
    "an unauthenticated git daemon is reachable",
    "major",
    74,
  ],
  [9999, "alt admin", remote("an administrative service"), "minor", 25],
  [
    10250,
    "kubelet",
    "the kubelet API is reachable, and it can run commands in every pod",
    "critical",
    96,
  ],
  [
    11211,
    "memcached",
    "memcached is reachable, and it has no authentication at all",
    "critical",
    95,
  ],
  [16379, "Redis cluster", remote("a Redis cluster bus"), "critical", 81],
  [
    24800,
    "Synergy",
    "a keyboard and mouse sharing service is reachable, unencrypted",
    "critical",
    89,
  ],
  [25565, "Minecraft", remote("a game server"), "minor", 21],
  [
    27017,
    "MongoDB",
    "MongoDB is reachable, and older defaults have no authentication",
    "critical",
    94,
  ],
  [28017, "MongoDB status", remote("a database status page"), "major", 53],
  [32400, "Plex", remote("a media server"), "minor", 23],
  [49152, "UPnP", remote("a UPnP endpoint"), "major", 52],
  [
    7,
    "echo",
    "a legacy echo service is reachable, and it is an amplification source",
    "major",
    70,
  ],
  [9, "discard", "a legacy discard service is reachable", "minor", 20],
  [13, "daytime", "a legacy service that answers with the time", "minor", 19],
  [17, "qotd", "a legacy service that answers with text", "minor", 18],
  [37, "time", "a legacy time service is reachable", "minor", 17],
  [113, "ident", "the machine answers who owns a connection", "minor", 29],
  [179, "BGP", "a routing daemon is reachable", "major", 71],
  [
    427,
    "SLP",
    "a service-location daemon answers, and it amplifies",
    "major",
    69,
  ],
  [543, "klogin", "clear-text Kerberos login is reachable", "critical", 90],
  [544, "kshell", "clear-text Kerberos shell is reachable", "critical", 90],
  [587, "submission", "a mail submission service is reachable", "minor", 27],
  [1352, "Domino", "a groupware server is reachable", "major", 62],
  [1604, "Citrix", "a remote application service is reachable", "major", 73],
  [
    1883,
    "MQTT",
    "an IoT broker is reachable, and its default has no authentication",
    "critical",
    86,
  ],
  [2000, "Cisco SCCP", "a telephony service is reachable", "minor", 24],
  [
    2222,
    "SSH alt",
    "remote login on an alternate port is reachable",
    "major",
    72,
  ],
  [2483, "Oracle TCP", "a database listener is reachable", "critical", 85],
  [2601, "zebra", "a routing daemon console is reachable", "major", 68],
  [3050, "Firebird", "a database is reachable", "major", 64],
  [3299, "SAP", "an SAP router is reachable", "major", 63],
  [
    3632,
    "distcc",
    "a distributed compiler is reachable, and it executes what it is sent",
    "critical",
    94,
  ],
  [4022, "dnsx", "a management service is reachable", "minor", 22],
  [
    4505,
    "Salt",
    "a configuration master is reachable, and it runs commands on minions",
    "critical",
    93,
  ],
  [4506, "Salt", "the Salt return port is reachable", "critical", 93],
  [4840, "OPC UA", "an industrial control endpoint is reachable", "major", 67],
  [5061, "SIP TLS", "a telephony endpoint is reachable", "minor", 21],
  [5222, "XMPP", "a chat service is reachable", "minor", 25],
  [5269, "XMPP s2s", "a chat federation port is reachable", "minor", 23],
  [5357, "WSD", "web services discovery announces this machine", "minor", 30],
  [
    5666,
    "NRPE",
    "a monitoring agent is reachable, and it runs commands",
    "critical",
    91,
  ],
  [5985, "WinRM", "a remote management endpoint is reachable", "critical", 88],
  [
    5986,
    "WinRM TLS",
    "a remote management endpoint is reachable",
    "critical",
    88,
  ],
  [6060, "debug", "a debug port is reachable", "major", 66],
  [
    7777,
    "alt",
    "a service on a commonly probed port is reachable",
    "minor",
    14,
  ],
  [
    8009,
    "AJP",
    "an application connector is reachable, and AJP has a request-smuggling history",
    "critical",
    87,
  ],
  [8010, "alt HTTP", "a web service is reachable", "minor", 13],
  [8060, "alt HTTP", "a web service is reachable", "minor", 12],
  [8080, "HTTP proxy", "a web or proxy service is reachable", "minor", 31],
  [8090, "alt HTTP", "a web service is reachable", "minor", 11],
  [8140, "Puppet", "a configuration master is reachable", "critical", 84],
  [8200, "Vault", "a secret store is reachable", "critical", 96],
  [8291, "Winbox", "a router management service is reachable", "critical", 83],
  [8333, "Bitcoin", "a blockchain node is reachable", "minor", 10],
  [8834, "Nessus", "a vulnerability scanner console is reachable", "major", 65],
  [9001, "Tor", "a Tor relay port is reachable", "minor", 20],
  [
    9051,
    "Tor control",
    "the Tor control port is reachable, and it can reconfigure the relay",
    "critical",
    92,
  ],
  [9443, "HTTPS alt", "a web service is reachable", "minor", 9],
  [10051, "Zabbix", "a monitoring server is reachable", "major", 60],
  [11371, "HKP", "a keyserver is reachable", "minor", 8],
  [18080, "Monero", "a blockchain node is reachable", "minor", 7],
  [
    19999,
    "Netdata",
    "a metrics console is reachable, and it exposes detailed host state",
    "major",
    59,
  ],
  [50070, "Hadoop", "a namenode console is reachable", "major", 58],
  [61616, "ActiveMQ", "a broker is reachable", "major", 57],
  [
    11,
    "systat",
    "a legacy service that lists running processes to the network",
    "major",
    68,
  ],
  [
    15,
    "netstat",
    "a legacy service that lists connections to the network",
    "major",
    67,
  ],
  [43, "whois", "a whois service is reachable", "minor", 12],
  [49, "TACACS", "an authentication service is reachable", "major", 66],
  [80, "HTTP", "a web server is reachable, unencrypted", "minor", 40],
  [
    109,
    "POP2",
    "a legacy clear-text mail service is reachable",
    "critical",
    88,
  ],
  [115, "SFTP legacy", "a legacy transfer service is reachable", "major", 65],
  [117, "UUCP", "a legacy transfer protocol is reachable", "minor", 11],
  [194, "IRC", "an IRC service is reachable", "minor", 10],
  [443, "HTTPS", "a web server is reachable", "minor", 39],
  [465, "SMTPS", "a mail submission service is reachable", "minor", 24],
  [540, "UUCP", "a legacy transfer daemon is reachable", "minor", 9],
  [554, "RTSP", "a streaming service is reachable", "minor", 19],
  [563, "NNTPS", "a news service is reachable", "minor", 8],
  [777, "multiling", "a service on an unusual port is reachable", "minor", 7],
  [902, "VMware", "a hypervisor agent is reachable", "major", 64],
  [1050, "CORBA", "an object broker is reachable", "major", 63],
  [1234, "alt", "a service on a commonly probed port is reachable", "minor", 6],
  [2086, "WHM", "a hosting control panel is reachable", "critical", 84],
  [2095, "webmail", "a webmail interface is reachable", "major", 61],
  [2121, "FTP alt", "clear-text file transfer is reachable", "critical", 85],
  [2302, "game", "a game server is reachable", "minor", 5],
  [3690, "Subversion", "a version control daemon is reachable", "major", 60],
  [4000, "alt", "a service on a commonly probed port is reachable", "minor", 4],
  [4200, "dev server", "a development server is reachable", "minor", 23],
  [4567, "dev server", "a development server is reachable", "minor", 22],
  [5100, "alt", "a service on a commonly probed port is reachable", "minor", 3],
  [6543, "dev server", "a development server is reachable", "minor", 21],
  [7071, "admin", "an administration console is reachable", "major", 59],
  [8181, "alt HTTP", "a web service is reachable", "minor", 18],
  [8222, "NATS monitor", "a broker console is reachable", "major", 58],
  [
    8384,
    "Syncthing UI",
    "the file-sync console is reachable, and it can add folders",
    "critical",
    82,
  ],
  [8765, "alt", "a service on a commonly probed port is reachable", "minor", 2],
  [
    9091,
    "Transmission",
    "the torrent client console is reachable, and it can write files anywhere it can reach",
    "critical",
    81,
  ],
  [9993, "ZeroTier", "a mesh networking service is reachable", "minor", 17],
  [10809, "NBD", "a network block device is reachable", "critical", 80],
  [
    11111,
    "alt",
    "a service on a commonly probed port is reachable",
    "minor",
    1,
  ],
  [
    24678,
    "Vite HMR",
    "a development hot-reload socket is reachable",
    "minor",
    16,
  ],
  [
    32768,
    "RPC",
    "a dynamically allocated RPC service is reachable",
    "major",
    57,
  ],
  [
    44818,
    "EtherNet/IP",
    "an industrial control endpoint is reachable",
    "major",
    56,
  ],
  [
    49664,
    "RPC",
    "a dynamically allocated RPC service is reachable",
    "major",
    55,
  ],
  [51820, "WireGuard", "a VPN endpoint is reachable", "minor", 15],
];

const UDP: Row[] = [
  [
    53,
    "DNS",
    "a resolver answers the network, which makes it an amplification source",
    "critical",
    88,
  ],
  [
    67,
    "DHCP server",
    "this machine hands out addresses to the network",
    "major",
    72,
  ],
  [69, "TFTP", remote("unauthenticated file transfer"), "critical", 93],
  [
    123,
    "NTP",
    "a time server answers the network, which is a classic amplifier",
    "major",
    71,
  ],
  [
    137,
    "NetBIOS name",
    "the machine announces its name and shares",
    "major",
    70,
  ],
  [
    138,
    "NetBIOS datagram",
    "the second half of the NetBIOS announcement",
    "major",
    69,
  ],
  [
    161,
    "SNMP",
    "SNMP answers the network with default community strings",
    "critical",
    90,
  ],
  [162, "SNMP trap", remote("an SNMP trap receiver"), "minor", 33],
  [500, "IKE", remote("a VPN key exchange endpoint"), "minor", 36],
  [
    514,
    "syslog",
    "the machine accepts log records from anyone on the network",
    "major",
    62,
  ],
  [1194, "OpenVPN", remote("a VPN server"), "minor", 39],
  [
    1900,
    "SSDP",
    "the machine answers UPnP discovery, which is both an amplifier and an inventory leak",
    "major",
    68,
  ],
  [3478, "STUN", remote("a NAT traversal service"), "minor", 27],
  [
    5353,
    "mDNS",
    "the machine answers multicast name queries for the whole segment",
    "minor",
    34,
  ],
  [
    5355,
    "LLMNR",
    "LLMNR answers are the classic credential-relay path on a local network",
    "major",
    76,
  ],
  [
    11211,
    "memcached",
    "memcached answers UDP, the single most abused amplification source there is",
    "critical",
    96,
  ],
  [27015, "game server", remote("a game server"), "minor", 24],
  [
    68,
    "DHCP client",
    "the DHCP client port is open to the network",
    "minor",
    18,
  ],
  [111, "portmap", "the RPC port mapper answers the network", "major", 67],
  [
    177,
    "XDMCP",
    "the display manager offers remote logins over an unencrypted protocol",
    "critical",
    92,
  ],
  [
    623,
    "IPMI",
    "the baseboard controller answers the network, and IPMI authentication is historically weak",
    "critical",
    94,
  ],
  [
    1434,
    "MSSQL browser",
    "the database browser answers, which is an amplification source",
    "major",
    66,
  ],
  [1701, "L2TP", remote("a VPN endpoint"), "minor", 26],
  [4500, "IPsec NAT-T", remote("a VPN endpoint"), "minor", 25],
  [5060, "SIP", remote("a telephony endpoint"), "minor", 29],
  [5683, "CoAP", remote("an IoT endpoint"), "major", 65],
  [
    6881,
    "BitTorrent",
    "a peer-to-peer port is open, which advertises this machine widely",
    "minor",
    22,
  ],
  [10000, "Webmin", remote("an administration console"), "critical", 93],
  [17185, "VxWorks", "a debug service is reachable", "critical", 95],
  [26000, "Quake", remote("a game server"), "minor", 15],
  [47808, "BACnet", remote("a building automation endpoint"), "major", 64],
  [
    19,
    "chargen",
    "the character generator is a classic amplification source",
    "critical",
    95,
  ],
  [37, "time", "a legacy time service answers the network", "minor", 14],
  [49, "TACACS", "an authentication service answers the network", "major", 64],
  [135, "MSRPC", "an RPC endpoint mapper answers the network", "major", 66],
  [
    139,
    "NetBIOS session",
    "Windows networking answers the network",
    "major",
    65,
  ],
  [389, "LDAP", "a directory service answers the network", "major", 63],
  [445, "SMB", "Windows file sharing answers the network", "major", 67],
  [520, "RIP", "a routing daemon answers the network", "major", 61],
  [521, "RIPng", "an IPv6 routing daemon answers the network", "major", 60],
  [631, "IPP", "the print service answers the network", "minor", 25],
  [
    1645,
    "RADIUS",
    "an authentication service answers the network",
    "major",
    59,
  ],
  [
    1812,
    "RADIUS",
    "an authentication service answers the network",
    "major",
    58,
  ],
  [
    1985,
    "HSRP",
    "a router redundancy protocol answers the network",
    "minor",
    20,
  ],
  [2049, "NFS", "filesystem export answers the network", "major", 68],
  [
    3283,
    "ARD",
    "Apple remote desktop discovery answers the network",
    "major",
    57,
  ],
  [
    3702,
    "WS-Discovery",
    "service discovery announces this machine, and it amplifies",
    "major",
    56,
  ],
  [
    4444,
    "alt",
    "a port commonly used by remote-access tooling answers",
    "major",
    55,
  ],
  [5000, "UPnP", "a UPnP endpoint answers the network", "major", 54],
  [5432, "PostgreSQL", "a database answers the network", "critical", 90],
  [6343, "sFlow", "a flow collector answers the network", "minor", 19],
  [9987, "TeamSpeak", "a voice server answers the network", "minor", 13],
  [
    17500,
    "Dropbox LAN",
    "the sync client announces this machine to the local network",
    "minor",
    22,
  ],
  [
    32410,
    "Plex discovery",
    "the media server announces itself to the local network",
    "minor",
    12,
  ],
  [
    33848,
    "Jenkins discovery",
    "a build server announces itself to the local network",
    "major",
    52,
  ],
  [37777, "DVR", "a camera recorder answers the network", "critical", 88],
  [54321, "alt", "a service on a commonly probed port answers", "minor", 11],
];

/** `/proc/net/{tcp,udp}` — the dependency-free reading. `00000000` is 0.0.0.0,
 *  state `0A` is LISTEN for TCP; a UDP socket has no listen state, so an
 *  unconnected socket bound to a wildcard address is the equivalent. */
const row = (proto: "tcp" | "udp") =>
(
  [port, name, why, severity, weight]: Row,
): SysPolicy => ({
  id: `port-${proto}-${port}`,
  title: `${proto.toUpperCase()} port ${port} (${name}) is open to the network`,
  category: "security",
  severity,
  weight,
  source: { kind: "file", path: `/proc/net/${proto}` },
  // The engine matches on text, so the port is encoded the way the file spells
  // it: a wildcard local address followed by the port in upper-case hex.
  bad: `~00000000:${
    port.toString(16).toUpperCase().padStart(4, "0")
  } ` as const,
  detail: why,
  how: `Find the owner with \`sudo ss -lnp${proto === "tcp" ? "t" : "u"} ` +
    `'sport = :${port}'\`, then either stop it, bind it to 127.0.0.1 in its ` +
    `own configuration, or block the port at the firewall. Do not simply ` +
    `kill it — something on this machine opened it deliberately.`,
});

export const PORT_POLICIES: SysPolicy[] = [
  ...TCP.map(row("tcp")),
  ...UDP.map(row("udp")),
];
