// Data safety and machine reliability — the two categories the catalogue was
// thinnest on, and the two whose failures are the least recoverable.
import type { SysPolicy } from "../../../type/policy.ts";

const sh = (script: string) => ({
  kind: "cmd" as const,
  cmd: "sh",
  args: ["-c", script] as const,
});

/** [id, script, bad, cat, band, weight, title, detail, how] */
type Row = [
  string,
  string,
  SysPolicy["bad"],
  SysPolicy["category"],
  SysPolicy["severity"],
  number,
  string,
  string,
  string,
];

const ROWS: Row[] = [
  // ------------------------------------------------------------- data safety
  [
    "git-uncommitted",
    'find "$HOME" -maxdepth 5 -type d -name .git -prune 2>/dev/null | head -60 | while read -r g; do d=$(dirname "$g"); [ -n "$(git -C "$d" status --porcelain 2>/dev/null)" ] && echo x; done | wc -l',
    ">3",
    "safety",
    "major",
    84,
    "Several repositories have uncommitted work",
    "changes that exist only in your working tree — a disk failure, a mistaken checkout or a stray `git clean` takes them",
    "`git status` in each. Commit or stash what matters; the point is that it should exist somewhere other than one directory on one disk.",
  ],
  [
    "git-unpushed",
    'find "$HOME" -maxdepth 5 -type d -name .git -prune 2>/dev/null | head -60 | while read -r g; do d=$(dirname "$g"); c=$(git -C "$d" log --branches --not --remotes --oneline 2>/dev/null | wc -l); [ "$c" -gt 0 ] && echo x; done | wc -l',
    ">3",
    "safety",
    "major",
    86,
    "Several repositories have commits that exist only on this machine",
    "the work is committed, which feels safe, and it is still on exactly one disk",
    "`git log --branches --not --remotes` in each. Push them, or at least make sure the backup covers those directories.",
  ],
  [
    "trash-autoempty",
    "gsettings get org.gnome.desktop.privacy remove-old-trash-files 2>/dev/null || gsettings get org.cinnamon.desktop.privacy remove-old-trash-files 2>/dev/null",
    "true",
    "safety",
    "major",
    80,
    "The trash empties itself on a timer",
    "a file you deleted by mistake is recoverable only until the timer runs, and the timer gives no warning",
    "Turn it off in Privacy settings if you would rather empty the trash deliberately.",
  ],
  [
    "trash-old-items",
    "find ~/.local/share/Trash/files -maxdepth 1 -mtime +30 2>/dev/null | wc -l",
    ">20",
    "safety",
    "minor",
    40,
    "There are old items in the trash",
    "either they matter and should be restored, or they do not and are occupying the disk — leaving them decides neither",
    "Look through it, then empty it.",
  ],
  [
    "backup-not-encrypted",
    "grep -rl 'encryption *= *none\\|--no-encryption' ~/.config/borgmatic ~/.config/restic 2>/dev/null | wc -l",
    ">0",
    "safety",
    "major",
    82,
    "A backup is configured without encryption",
    "the backup contains everything the machine does, and it usually lives somewhere you control less than the machine",
    "Turn on encryption in the backup tool. An unencrypted offsite backup is a copy of your data in somebody else's building.",
  ],
  [
    "backup-never-restored",
    'f=$(ls -1t ~/.cache/*restore* ~/.config/*/last-restore 2>/dev/null | head -1); [ -n "$f" ] && echo tested || echo never',
    "~never",
    "safety",
    "major",
    79,
    "No restore has ever been tested",
    "a backup that has never been restored is a hypothesis, and the moment you find out is the worst possible moment",
    "Restore one file to a scratch directory today. It takes minutes and it is the only thing that turns a backup into a plan.",
  ],
  [
    "fs-no-journal",
    "for d in $(lsblk -pnro NAME,FSTYPE | awk '$2 ~ /^ext[34]$/{print $1}'); do tune2fs -l $d 2>/dev/null | grep -qi 'has_journal' || echo x; done | wc -l",
    ">0",
    "safety",
    "critical",
    90,
    "A filesystem has no journal",
    "an unclean shutdown can leave it inconsistent, and recovery means fsck guessing",
    "`sudo tune2fs -O has_journal /dev/…` on an unmounted filesystem.",
  ],
  [
    "single-disk",
    "lsblk -dno TYPE 2>/dev/null | grep -c '^disk$'",
    "<2",
    "safety",
    "minor",
    44,
    "There is one disk in this machine",
    "no redundancy: a single failure takes the system and the data together — which is only a problem if the backup is not real",
    "Nothing to change here; it is a reason to take the backup rows above seriously.",
  ],
  [
    "smart-selftest-never",
    "for d in /dev/sd? /dev/nvme?n?; do [ -e $d ] && smartctl -l selftest $d 2>/dev/null; done | grep -ci 'No self-tests have been logged'",
    ">0",
    "safety",
    "minor",
    42,
    "A disk has never run a self-test",
    "the drive's own diagnostics have never been exercised, so its health report is based on passive counters only",
    "`sudo smartctl -t short /dev/…` takes a couple of minutes and runs in the background.",
  ],
  [
    "editor-autosave-off",
    'grep -l \'"files.autoSave": *"off"\' ~/.config/Code/User/settings.json ~/.config/VSCodium/User/settings.json 2>/dev/null | wc -l',
    ">0",
    "safety",
    "minor",
    36,
    "The editor does not save automatically",
    "a crash or a power cut loses everything since your last keystroke on Ctrl-S",
    'Set `"files.autoSave": "afterDelay"` in settings.json.',
  ],
  [
    "downloads-old",
    "find ~/Downloads -maxdepth 1 -mtime +180 2>/dev/null | wc -l",
    ">50",
    "resource",
    "minor",
    26,
    "Downloads has a lot of old files",
    "months of installers and attachments, some of which are the only copy of something",
    "Sort by date and work through it. Move what matters somewhere the backup covers.",
  ],

  // -------------------------------------------------------------- stability
  [
    "dkms-failed",
    "dkms status 2>/dev/null | grep -ci 'error\\|failed'",
    ">0",
    "stability",
    "critical",
    92,
    "An out-of-tree kernel module failed to build",
    "a driver — usually graphics, wireless or virtualisation — is missing for the current kernel, and the failure only shows when you use that hardware",
    "`dkms status` names it; `sudo dkms autoinstall` retries. Check the build log in /var/lib/dkms/.",
  ],
  [
    "units-activating",
    "systemctl list-units --state=activating --no-legend 2>/dev/null | wc -l",
    ">2",
    "stability",
    "minor",
    54,
    "Services are stuck starting",
    "a unit that never finishes starting holds up everything ordered after it, including sometimes the login screen",
    "`systemctl list-units --state=activating` names them; `systemd-analyze blame` shows what they cost.",
  ],
  [
    "etc-broken-symlinks",
    "find /etc -maxdepth 3 -xtype l 2>/dev/null | wc -l",
    ">3",
    "stability",
    "minor",
    38,
    "There are broken links in the system configuration",
    "each one is a file something expects to find and will not",
    "`sudo find /etc -xtype l -ls` lists them. Most are leftovers from removed packages.",
  ],
  [
    "fstab-duplicate",
    "awk '!/^#|^$/{print $1}' /etc/fstab 2>/dev/null | sort | uniq -d | wc -l",
    ">0",
    "stability",
    "major",
    76,
    "A device appears twice in the filesystem table",
    "which mount wins is decided by ordering, and the result changes between boots",
    "`cat /etc/fstab` and remove the duplicate entry.",
  ],
  [
    "edac-errors",
    "grep -h . /sys/devices/system/edac/mc/mc*/ce_count 2>/dev/null | awk '{s+=$1} END{print s+0}'",
    ">0",
    "stability",
    "critical",
    94,
    "Memory has reported correctable errors",
    "ECC caught and repaired a bit flip — the memory is degrading, and uncorrectable errors are what comes next",
    "Note the count and watch it. If it rises, replace the module. `sudo edac-util -v` identifies which one.",
  ],
  [
    "fan-stopped",
    'sensors 2>/dev/null | awk \'/fan[0-9]/{gsub("RPM",""); if($2+0==0) c++} END{print c+0}\'',
    ">0",
    "stability",
    "major",
    78,
    "A fan is reporting zero speed",
    "either the sensor is wrong or a fan has stopped — and if it has, the thermal throttling starts shortly after",
    "Listen to the machine and check `sensors`. A stopped fan on a loaded machine is a matter of minutes, not days.",
  ],
  [
    "apt-source-unreachable",
    "timeout 8 apt-get -s -q -o Debug::NoLocking=1 update 2>&1 | grep -ci '^Err\\|Failed to fetch'",
    ">0",
    "stability",
    "major",
    72,
    "A software source cannot be reached",
    "updates from that source stop arriving, silently, and the machine looks up to date because nothing failed loudly",
    "`sudo apt update` shows which. A repository that has moved or expired needs its entry removed or corrected.",
  ],
  [
    "flatpak-remote-unreachable",
    "timeout 8 flatpak remote-ls --updates 2>&1 | grep -ci 'error\\|failed'",
    ">0",
    "stability",
    "minor",
    48,
    "A Flatpak remote cannot be reached",
    "applications from it stop receiving updates",
    "`flatpak remotes` and `flatpak remote-ls <remote>` show the state.",
  ],
  [
    "boot-failed-last",
    "journalctl -b -1 -p err --no-pager 2>/dev/null | grep -ci 'Failed to start'",
    ">5",
    "stability",
    "minor",
    46,
    "Several services failed to start on the previous boot",
    "an intermittent boot failure is easy to miss because the machine came up anyway",
    "`journalctl -b -1 -p err | grep 'Failed to start'`.",
  ],

  // ------------------------------------------------------------ performance
  [
    "scaling-driver",
    "cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_driver 2>/dev/null",
    "~acpi-cpufreq",
    "performance",
    "minor",
    34,
    "The processor uses the generic frequency driver",
    "on recent Intel and AMD parts the native driver gives finer control and better idle behaviour",
    "Check whether `intel_pstate` or `amd-pstate` is available for your processor; on AMD, `amd_pstate=active` on the kernel command line enables it.",
  ],
  [
    "aspm-off",
    "cat /sys/module/pcie_aspm/parameters/policy 2>/dev/null",
    "~[performance]",
    "resource",
    "minor",
    24,
    "PCIe power management is set to performance",
    "devices never enter low-power states, which costs battery for no gain on a desktop workload",
    "`pcie_aspm.policy=powersave` on the kernel command line. Some devices misbehave with it — test before making it permanent.",
  ],
  [
    "nvme-apst",
    "cat /sys/module/nvme_core/parameters/default_ps_max_latency_us 2>/dev/null",
    "=0",
    "resource",
    "minor",
    22,
    "NVMe power saving is disabled",
    "the drive stays in its highest power state, which is heat and battery for nothing when idle",
    "Remove `nvme_core.default_ps_max_latency_us=0` from the kernel command line unless it was added to work around a specific drive bug.",
  ],
  [
    "readahead-low",
    "cat /sys/block/nvme0n1/queue/read_ahead_kb 2>/dev/null",
    "<128",
    "performance",
    "minor",
    20,
    "Read-ahead is small",
    "sequential reads issue more requests than they need to",
    "`echo 256 | sudo tee /sys/block/nvme0n1/queue/read_ahead_kb`, made permanent with a udev rule.",
  ],
  [
    "font-cache-stale",
    "f=/var/cache/fontconfig; [ -d $f ] && echo $(( ( $(date +%s) - $(stat -c %Y $f) ) / 86400 )) || echo ''",
    ">180",
    "performance",
    "minor",
    14,
    "The font cache has not been rebuilt in a long time",
    "applications re-scan fonts at startup when the cache does not match what is installed",
    "`fc-cache -f` rebuilds it in seconds.",
  ],
  [
    "icon-cache-stale",
    'for d in /usr/share/icons/*/; do [ -f "$d/icon-theme.cache" ] || echo x; done 2>/dev/null | wc -l',
    ">2",
    "performance",
    "minor",
    12,
    "Icon caches are missing for some themes",
    "every application that draws an icon walks the directory instead of reading the cache",
    "`sudo gtk-update-icon-cache /usr/share/icons/<theme>`.",
  ],
  [
    "desktop-db-stale",
    "[ -f ~/.local/share/applications/mimeinfo.cache ] && echo ok || echo missing",
    "~missing",
    "performance",
    "minor",
    10,
    "The application database is not built for your user directory",
    "opening a file searches every desktop entry instead of a lookup",
    "`update-desktop-database ~/.local/share/applications`.",
  ],
  [
    "shader-cache-large",
    "du -sm ~/.cache/mesa_shader_cache ~/.cache/nvidia 2>/dev/null | awk '{s+=$1} END{print s+0}'",
    ">4096",
    "resource",
    "minor",
    18,
    "The GPU shader cache is large",
    "gigabytes of compiled shaders for programs you may no longer run",
    "Safe to delete — it rebuilds on demand, at the cost of one slower first run per application.",
  ],
  [
    "swappiness-high-ssd",
    "cat /proc/sys/vm/swappiness 2>/dev/null",
    ">60",
    "performance",
    "minor",
    28,
    "The kernel swaps eagerly",
    "pages are pushed to disk while memory is still free, which is felt as stutter when you return to an application",
    "`vm.swappiness=10` in /etc/sysctl.d/99-local.conf. With zram, a higher value is correct — this row assumes disk swap.",
  ],
  [
    "cpu-idle-disabled",
    "grep -c 'processor.driver: none' /sys/devices/system/cpu/cpuidle/current_driver 2>/dev/null || cat /sys/devices/system/cpu/cpuidle/current_driver 2>/dev/null",
    "~none",
    "resource",
    "minor",
    16,
    "Processor idle states are unavailable",
    "the processor never enters a deep idle state, which is constant heat and power draw",
    "Check for `intel_idle.max_cstate=0` or `processor.max_cstate=1` on the kernel command line; both are usually workarounds someone added years ago.",
  ],
  [
    "home-growth",
    'du -sm "$HOME" 2>/dev/null | cut -f1',
    ">500000",
    "resource",
    "minor",
    30,
    "Your home directory is very large",
    "half a terabyte in one account makes every backup slower and every restore longer",
    "`du -h --max-depth=2 ~ | sort -h | tail -20` shows where it is. Caches and container images are usually most of it.",
  ],
  [
    "large-files",
    'find "$HOME" -maxdepth 6 -type f -size +5G 2>/dev/null | head -20 | wc -l',
    ">2",
    "resource",
    "minor",
    28,
    "There are several very large files in your home directory",
    "a handful of multi-gigabyte files, which are usually disk images or downloads nobody meant to keep",
    "`find ~ -maxdepth 6 -type f -size +5G -exec ls -lh {} +` lists them.",
  ],
  [
    "ups-absent",
    "systemctl is-active nut-monitor apcupsd 2>/dev/null | grep -c active",
    "=0",
    "safety",
    "minor",
    34,
    "No uninterruptible power supply is being monitored",
    "a power cut during a write is how filesystems get corrupted, and a laptop battery is the only thing standing in for one on a desktop",
    "If there is a UPS attached, install `nut` or `apcupsd` so the machine shuts down cleanly. If there is not, this is a reason the backup matters more.",
  ],
  [
    "swap-file-on-backup",
    's=$(awk \'NR>1{print $1}\' /proc/swaps 2>/dev/null | head -1); [ -n "$s" ] && findmnt -no TARGET --target "$s" 2>/dev/null || echo none',
    "~/home",
    "performance",
    "minor",
    20,
    "Swap lives on the same filesystem as your data",
    "swap traffic competes with your own reads and writes for the same device",
    "Not worth moving on an SSD; on a spinning disk a separate device helps.",
  ],
  [
    "journald-per-boot",
    "journalctl --list-boots --no-pager 2>/dev/null | wc -l",
    "<2",
    "stability",
    "minor",
    16,
    "Only one boot is recorded in the journal",
    "logs do not survive a reboot, so a crash erases the evidence of what caused it",
    "Set `Storage=persistent` under [Journal] in /etc/systemd/journald.conf.",
  ],
  [
    "snap-old-revisions",
    "snap list --all 2>/dev/null | grep -c disabled",
    ">6",
    "resource",
    "minor",
    18,
    "Several old snap revisions are retained",
    "each disabled revision is a full copy of the application",
    "`sudo snap set system refresh.retain=2`, then remove the old ones with `snap remove --revision`.",
  ],
  [
    "docker-dangling",
    "docker images -f dangling=true -q 2>/dev/null | wc -l",
    ">10",
    "resource",
    "minor",
    22,
    "There are dangling container image layers",
    "layers no image references any more, occupying disk for nothing",
    "`docker image prune` removes them. It does not touch tagged images.",
  ],
  [
    "old-logs",
    "find /var/log -type f -name '*.gz' -o -name '*.[0-9]' 2>/dev/null | wc -l",
    ">80",
    "resource",
    "minor",
    14,
    "There are many rotated log files",
    "months of compressed history that nothing reads",
    "logrotate's own settings decide this — `maxage` in /etc/logrotate.conf bounds it.",
  ],
];

export const SAFETY_POLICIES: SysPolicy[] = ROWS.map(
  (
    [id, script, bad, category, severity, weight, title, detail, how],
  ): SysPolicy => ({
    id: `safe-${id}`,
    title,
    category,
    severity,
    weight,
    source: sh(script),
    bad,
    detail,
    how,
  }),
);
