// VPN posture: the settings that decide whether traffic can escape the tunnel,
// and whether the client is reporting on you while it protects you.
//
// NordVPN's settings are read through its own CLI. None of them is written
// automatically — a killswitch enabled at the wrong moment cuts every
// connection on the machine, which is exactly the harm this app refuses to do.
import type { SysPolicy } from "../../../type/policy.ts";

const nord = (
  id: string,
  key: string,
  bad: SysPolicy["bad"],
  severity: SysPolicy["severity"],
  weight: number,
  title: string,
  detail: string,
  how: string,
): SysPolicy => ({
  id: `vpn-nord-${id}`,
  title,
  category: "privacy",
  severity,
  weight,
  source: { kind: "cmd", cmd: "nordvpn", args: ["settings"], needs: "nordvpn" },
  extract: `^\\s*${key}\\s*:\\s*(\\S+)`,
  bad,
  detail,
  how,
});

export const VPN_POLICIES: SysPolicy[] = [
  nord(
    "killswitch",
    "Kill Switch",
    "false",
    "critical",
    88,
    "The VPN kill switch is off",
    "if the tunnel drops, traffic keeps flowing over the ordinary connection — usually without any sign on screen",
    "`nordvpn set killswitch on`. Turn it on when you are somewhere you can afford to lose connectivity: with it on, a dropped tunnel means no network at all until it comes back.",
  ),
  nord(
    "autoconnect",
    "Auto-connect",
    "false",
    "major",
    74,
    "The VPN does not connect automatically",
    "every network you join is used unprotected until you remember to connect",
    "`nordvpn set autoconnect on`. Consider `nordvpn whitelist` for networks where a captive portal has to load first.",
  ),
  nord(
    "dns",
    "DNS",
    "~disabled",
    "major",
    78,
    "VPN DNS is not configured",
    "name lookups can leave over the ordinary resolver while the traffic itself is tunnelled, which tells your ISP every site you visit",
    "`nordvpn set dns on` (or set explicit servers). Verify afterwards with `resolvectl status` — the tunnel interface should carry the DNS server.",
  ),
  nord(
    "threatprotection",
    "Threat Protection Lite",
    "false",
    "minor",
    44,
    "VPN-level tracker and malware blocking is off",
    "known tracker and malware domains resolve normally",
    "`nordvpn set threatprotectionlite on`. It is DNS-level blocking, so it can break a site that hosts its own assets on a flagged domain.",
  ),
  nord(
    "obfuscate",
    "Obfuscate",
    "false",
    "minor",
    30,
    "VPN traffic is not obfuscated",
    "the traffic is recognisable as VPN traffic, which matters only on networks that block it",
    "`nordvpn set obfuscate on`. It costs throughput and needs an OpenVPN server, so leave it off unless a network is blocking you.",
  ),
  nord(
    "analytics",
    "Analytics",
    "true",
    "major",
    76,
    "The VPN client sends usage analytics",
    "the tool you installed for privacy is reporting on how you use it",
    "`nordvpn set analytics off`.",
  ),
  nord(
    "notify",
    "Notify",
    "false",
    "minor",
    22,
    "The VPN gives no connection notifications",
    "you cannot tell at a glance whether the tunnel is up",
    "`nordvpn set notify on`.",
  ),
  nord(
    "lan",
    "LAN Discovery",
    "true",
    "minor",
    40,
    "LAN discovery is allowed while connected",
    "devices on the local network remain reachable through the tunnel, which is convenient and is also a path around it",
    "`nordvpn set lan-discovery off` when you are on a network you do not trust.",
  ),
  nord(
    "meshnet",
    "Meshnet",
    "true",
    "minor",
    38,
    "Meshnet is enabled",
    "this machine is reachable by other devices linked to your account, wherever they are",
    "`nordvpn set meshnet off` if you are not using it.",
  ),
  nord(
    "tray",
    "Tray",
    "false",
    "minor",
    12,
    "The VPN has no tray indicator",
    "there is nothing on screen showing whether you are protected",
    "`nordvpn set tray on`.",
  ),
  {
    id: "vpn-dns-leak",
    title: "DNS is not going through the VPN while it is connected",
    category: "privacy",
    severity: "critical",
    weight: 87,
    source: {
      kind: "cmd",
      cmd: "resolvectl",
      args: ["status"],
      needs: "resolvectl",
    },
    bad: "~Current DNS Server: 192.168.",
    detail:
      "the tunnel carries your traffic while your router still sees every name you look up",
    how:
      "With the VPN up, `resolvectl status` should show the tunnel interface carrying the DNS server. If it does not, enable the client's own DNS option, or set `DNS=` on the tunnel link.",
  },
  {
    id: "vpn-ipv6-leak",
    title: "IPv6 is up while the VPN carries IPv4 only",
    category: "privacy",
    severity: "major",
    weight: 79,
    source: { kind: "file", path: "/proc/sys/net/ipv6/conf/all/disable_ipv6" },
    bad: "=0",
    detail:
      "a site reachable over IPv6 is reached outside the tunnel, revealing your real address — the classic leak that a VPN's own connection test does not catch",
    how:
      "Check whether your VPN carries IPv6. If it does not, either disable IPv6 while connected (`sysctl net.ipv6.conf.all.disable_ipv6=1`) or use a client that blocks it for you. Do not disable IPv6 permanently without checking what on your network needs it.",
  },
  {
    id: "vpn-wg-conf-perms",
    title: "A WireGuard configuration is readable by other accounts",
    category: "security",
    severity: "critical",
    weight: 90,
    source: {
      kind: "cmd",
      cmd: "sh",
      args: [
        "-c",
        "stat -c '%a %n' /etc/wireguard/*.conf 2>/dev/null | grep -v '^600' | head -3",
      ],
    },
    bad: "~conf",
    detail:
      "a WireGuard config contains the private key in clear text, and that key is the whole tunnel",
    how: "`sudo chmod 600 /etc/wireguard/*.conf`.",
  },
  {
    id: "vpn-openvpn-auth-perms",
    title: "An OpenVPN credentials file is readable by other accounts",
    category: "security",
    severity: "critical",
    weight: 89,
    source: {
      kind: "cmd",
      cmd: "sh",
      args: [
        "-c",
        "stat -c '%a %n' /etc/openvpn/*auth* /etc/openvpn/**/*auth* 2>/dev/null | grep -v '^600' | head -3",
      ],
    },
    bad: "~auth",
    detail: "the file holds a VPN username and password in clear text",
    how:
      "`sudo chmod 600` on the file, and check that the directory above it is not world-readable either.",
  },
];
